In [1]:
import pandas as pd
# import censusdata
import glob
import os
from tqdm import tqdm
# import matplotlib.pyplot as plt
import random
import geopandas as gpd
from datetime import datetime
import numpy as np

tqdm.pandas()

# from matplotlib.font_manager import FontManager
# fm = FontManager()
# mat_fonts = set(f.name for f in fm.ttflist)
# print(mat_fonts)

import matplotlib.pyplot as plt

# plt.rcParams['font.sans-serif'] = ['DengXian']
plt.rcParams.update({'font.size': 16})
pd.set_option('display.max_columns', None)  # show all columns
pd.set_option("display.max_colwidth", 100)

In [2]:
data_dir = r'F:\Research\Safegraph_bias\20230916'
save_dir = r'F:\Research\Safegraph_bias\figures_20230917'

In [7]:
columns = ['Female', 'Male',
        '15–17', '18–24', '25–34', '35–44', '45–54', '55–64', '>65',
       'White', 'Black', 'Hispanic', 'Asian', 'NoSchool', 'HighSchool',
       'NoCollege', 'Bachelor', 'Graduate', '<20K', '20K–30K', '30K–50K',
       '50K–100K', '>100K']

In [54]:
urban_rural_county_xls = os.path.join(data_dir, 'ruralurbancodes2013.xls')
urban_rural_county_df = pd.read_excel(urban_rural_county_xls, dtype={'FIPS':str})
# add the urban column
urban_rural_county_df['Urban'] = urban_rural_county_df['Description'].str[:5].replace({'Metro': 'Urban', 'Nonme': 'Rural'})
 
urban_rural_county_df

,FIPS,State,County_Name,Population_2010,RUCC_2013,Description,Urban
0,01001,AL,Autauga County,54571,2.0,"Metro - Counties in metro areas of 250,000 to 1 million population ...",Urban
1,01003,AL,Baldwin County,182265,3.0,"Metro - Counties in metro areas of fewer than 250,000 population ...",Urban
2,01005,AL,Barbour County,27457,6.0,"Nonmetro - Urban population of 2,500 to 19,999, adjacent to a metro area ...",Rural
3,01007,AL,Bibb County,22915,1.0,Metro - Counties in metro areas of 1 million population or more ...,Urban
4,01009,AL,Blount County,57322,1.0,Metro - Counties in metro areas of 1 million population or more ...,Urban
...,...,...,...,...,...,...,...
3229,72151,PR,Yabucoa Municipio,37941,1.0,Metro - Counties in metro areas of 1 million population or more ...,Urban
3230,72153,PR,Yauco Municipio,42043,2.0,"Metro - Counties in metro areas of 250,000 to 1 million population ...",Urban
3231,78010,VI,St. Croix Island,50601,5.0,"Nonmetro - Urban population of 20,000 or more, not adjacent to a metro area ...",Rural
3232,78020,VI,St. John Island,4170,7.0,"Nonmetro - Urban population of 2,500 to 19,999, not adjacent to a metro area ...",Rural
3233,78030,VI,St. Thomas Island,51634,5.0,"Nonmetro - Urban population of 20,000 or more, not adjacent to a metro area ...",Rural

In [73]:
years = [2018, 2019, 2020, 2021, 2022]
df_new = pd.DataFrame()

# level = 'state'
level = 'county'

for year in years[:]:
    print(year)
    # region_name = r'deep_south'
    csv_file = os.path.join(data_dir, f'monthly_bias_{level}_{year}.csv')
    df = pd.read_csv(csv_file)
    df['variable'] = pd.Categorical(df['variable'], categories=columns, ordered=True)  
    if level == 'state':
        
        df = df.groupby('variable', as_index=True, observed=True).agg(bias_median=('bias', 'median'),
                                                                  bias_max=('bias', 'max'),
                                                                  bias_min=('bias', 'min'),
                                                                 )
        # df_new['variable'] =  df['variable']

    if level == 'county':
        df['FIPS'] = df['county_fips'].astype(str).str.zfill(5)
        df = df.merge(urban_rural_county_df[['FIPS', 'Urban']], on='FIPS')
        df = df.groupby(['variable'], as_index=True, observed=True).agg(bias_median=('bias', 'median'),
        # df = df.groupby(['variable', 'Urban'], as_index=True, observed=True).agg(bias_median=('bias', 'median'),
                                                                  bias_max=('bias', 'max'),
                                                                  bias_min=('bias', 'min'),
                                                                 )
        # df_new[r'Urban/Rural'] = df.iloc[:, 0]
        
 
    df_new[f'{year}'] = df[f'bias_median'].apply('{:.3f}'.format) + ' [' + df[f'bias_min'].apply('{:.3f}'.format).astype(str) + ', ' +  df[f'bias_max'].apply('{:.3f}'.format).astype(str)+ ']'
    # break
    # bias_df
# df_new.set_index('variable', inplace=True)
    
# df_new = df_new.loc[columns]

print("level:", level)
df_new.to_csv(os.path.join(save_dir, f'bias_{level}_2018-2022_table_no_urban.csv'),  index=True)    
df_new

2018
2019
2020
2021
2022

,2018,2019,2020,2021,2022
variable,,,,,
Female,"0.001 [-0.168, 0.840]","0.001 [-0.188, 0.661]","0.001 [-0.137, 0.672]","0.002 [-0.108, 0.623]","0.002 [-0.109, 0.539]"
Male,"-0.001 [-0.258, 0.129]","-0.001 [-0.256, 0.145]","-0.001 [-0.261, 0.106]","-0.002 [-0.270, 0.115]","-0.002 [-0.266, 0.107]"
15–17,"-0.009 [-0.568, 0.488]","-0.010 [-0.514, 0.912]","-0.007 [-0.460, 0.921]","-0.008 [-0.520, 4.317]","-0.010 [-0.552, 4.044]"
18–24,"-0.006 [-0.566, 0.662]","-0.011 [-0.552, 0.494]","-0.020 [-0.570, 0.656]","-0.016 [-0.503, 1.898]","-0.013 [-0.624, 1.872]"
25–34,"-0.003 [-0.626, 0.285]","-0.006 [-0.625, 0.375]","-0.011 [-0.644, 0.371]","-0.011 [-0.629, 0.398]","-0.009 [-0.586, 0.466]"
35–44,"-0.004 [-0.551, 0.195]","-0.005 [-0.546, 0.263]","-0.004 [-0.559, 0.256]","-0.006 [-0.546, 0.319]","-0.007 [-0.512, 0.311]"
45–54,"0.001 [-0.308, 0.341]","0.002 [-0.281, 0.355]","0.006 [-0.219, 0.404]","0.003 [-0.288, 0.491]","0.002 [-0.363, 0.534]"
55–64,"0.009 [-0.230, 0.449]","0.011 [-0.268, 0.515]","0.016 [-0.245, 0.421]","0.012 [-0.266, 0.421]","0.011 [-0.273, 0.514]"
>65,"0.013 [-0.237, 0.820]","0.015 [-0.388, 0.642]","0.020 [-0.250, 0.647]","0.019 [-0.399, 0.819]","0.016 [-0.456, 1.029]"
White,"0.001 [-0.152, 0.507]","0.002 [-0.275, 0.591]","0.004 [-0.398, 0.813]","0.003 [-0.527, 1.055]","0.003 [-0.373, 0.867]"
Black,"-0.008 [-0.961, 1.629]","-0.030 [-0.955, 2.970]","-0.054 [-0.970, 2.644]","-0.048 [-0.963, 3.857]","-0.049 [-0.942, 3.838]"
Hispanic,"-0.009 [-0.648, 1.294]","-0.022 [-0.720, 1.846]","-0.034 [-0.734, 1.223]","-0.031 [-0.728, 1.319]","-0.026 [-0.710, 2.349]"
Asian,"0.010 [-0.724, 3.246]","-0.003 [-0.713, 2.294]","-0.009 [-0.768, 4.057]","-0.010 [-0.801, 5.730]","-0.027 [-0.780, 4.716]"
NoSchool,"-0.009 [-0.451, 0.619]","-0.015 [-0.474, 0.564]","-0.020 [-0.460, 0.373]","-0.015 [-0.458, 0.433]","-0.008 [-0.492, 0.543]"
HighSchool,"0.000 [-0.346, 0.228]","-0.000 [-0.367, 0.254]","0.002 [-0.357, 0.232]","0.002 [-0.345, 0.265]","0.005 [-0.357, 0.342]"
NoCollege,"-0.003 [-0.341, 0.237]","-0.005 [-0.355, 0.177]","-0.004 [-0.346, 0.209]","-0.002 [-0.336, 0.224]","0.001 [-0.347, 0.377]"
Bachelor,"0.018 [-0.288, 0.656]","0.020 [-0.438, 0.815]","0.024 [-0.493, 0.670]","0.019 [-0.465, 0.842]","0.009 [-0.470, 0.988]"
Graduate,"0.022 [-0.457, 0.874]","0.024 [-0.302, 2.603]","0.028 [-0.342, 1.670]","0.022 [-0.381, 1.062]","0.007 [-0.456, 1.168]"
<20K,"0.004 [-0.460, 0.507]","-0.002 [-0.541, 0.580]","-0.012 [-0.518, 0.508]","-0.005 [-0.506, 0.602]","0.000 [-0.495, 0.682]"
20K–30K,"0.001 [-0.391, 0.490]","-0.002 [-0.598, 0.494]","-0.007 [-0.607, 0.580]","-0.003 [-0.395, 0.725]","0.000 [-0.605, 0.883]"
30K–50K,"0.000 [-0.465, 0.262]","-0.002 [-0.292, 0.358]","-0.004 [-0.276, 0.355]","-0.003 [-0.336, 0.597]","-0.000 [-0.374, 0.865]"
50K–100K,"-0.003 [-0.295, 0.361]","-0.002 [-0.268, 0.375]","0.001 [-0.239, 0.456]","-0.001 [-0.235, 0.483]","-0.001 [-0.223, 0.412]"
>100K,"0.001 [-0.424, 0.764]","0.007 [-0.361, 1.074]","0.015 [-0.361, 1.296]","0.007 [-0.395, 0.821]","-0.001 [-0.386, 1.663]"