In [3]:
# ! pip install censusdata
# ! pip install census
# ! pip install us

In [28]:
import pandas as pd
# import censusdata
import glob
import os
from tqdm import tqdm
# import matplotlib.pyplot as plt
import random
import geopandas as gpd
from datetime import datetime
import numpy as np

# from matplotlib.font_manager import FontManager
# fm = FontManager()
# mat_fonts = set(f.name for f in fm.ttflist)
# print(mat_fonts)

import matplotlib.pyplot as plt

# plt.rcParams['font.sans-serif'] = ['DengXian']
plt.rcParams.update({'font.size': 16})
pd.set_option('display.max_columns', None)  # show all columns
pd.set_option("display.max_colwidth", 100)

# Load demographic data

In [2]:
# # weekly residing files
# weekly_residing_all_df = pd.read_csv(r'J:\weekly_patterns_20211211\Panel_overview_data\WeeklyPattern\weekly_home_panel_summary.csv', dtype={'census_block_group':str})
# # weekly_residing_df = weekly_residing_df.merge(sociala_variable_df, left_on='census_block_group', right_on='fips')
# weekly_residing_all_df['census_block_group'] = weekly_residing_all_df['census_block_group'].str.zfill(12)
# weekly_residing_all_df = weekly_residing_all_df.sort_values(['date_range_start', 'date_range_end'])
# weekly_residing_all_df

In [3]:
# ACS_csv = r'H:\covid_mobility_results\new_census_data\ACS_2019_5YR_BG\ACS_race_cbsa_income_2019_county_decile.csv'
# ACS_df = pd.read_csv(ACS_csv)

# YEAR = '2022'

# if YEAR > "2019":
#     acs_year = 2019
# else:
#     acs_year = YEAR
    
# social_variable_df = pd.read_csv(fr'P:\Shared drives\T5\safegraph_bias\cbg_acs_{acs_year}_county_tract.csv', dtype={'fips':str})
# social_variable_df['fips'] = social_variable_df['fips'].astype(str).str.zfill(12)
# social_variable_df.columns
# print("US population, male, female:")
# social_variable_df['totalpopulation'].sum(), social_variable_df['male'].sum(), social_variable_df['female'].sum(), len(social_variable_df)

In [29]:
def compose_variables(ACS_df):
    ACS_df['Female'] = ACS_df['female'] / ACS_df['totalpopulation']
    ACS_df['Male'] = ACS_df['male'] / ACS_df['totalpopulation']
    ACS_df['<15'] = (ACS_df['under5years'] + ACS_df['5to9years'] + \
                                        ACS_df['10to14years']) / ACS_df['totalpopulation'] 

    ACS_df['15–17'] = (ACS_df['15to17years']) / ACS_df['totalpopulation'] # ACS_df['under5years'] + ACS_df['5to9years'] + \                                     ACS_df['10to14years'] + 

    ACS_df['18–24'] = ACS_df['18to24years'] / ACS_df['totalpopulation']
    ACS_df['25–34'] = ACS_df['25to34years'] / ACS_df['totalpopulation'] 
    ACS_df['35–44'] = ACS_df['35to44years'] / ACS_df['totalpopulation'] 
    ACS_df['45–54'] = ACS_df['45to54years'] / ACS_df['totalpopulation'] 
    ACS_df['55–64'] = ACS_df['55to64years'] / ACS_df['totalpopulation'] 
    ACS_df['>65'] = (ACS_df['65to74years'] + ACS_df['75to84years'] \
                                           + ACS_df['85yearsandover']) / ACS_df['totalpopulation']

    ACS_df['White'] = ACS_df['whitealone'] / ACS_df['totalpopulation'] 
    ACS_df['Black'] = ACS_df['blackorafricanamericanalone'] / ACS_df['totalpopulation'] 
    ACS_df['Hispanic'] = ACS_df['Hispanic_or_Latino'] / ACS_df['totalpopulation'] 
    ACS_df['Asian'] = ACS_df['asianalone'] / ACS_df['totalpopulation']
    # Hispanic/Latino
    
    #  # ACS_df['population25yearsandover'] was change to  ACS_df['totalpopulation'] 
    ACS_df['NoSchool'] = ACS_df['population25yearsandoverlessthanhighschool'] / ACS_df['totalpopulation']   # ACS_df['population25yearsandover']
    ACS_df['HighSchool'] = ACS_df['population25yearsandoverhighschoolgraduateincludesequivalency'] / ACS_df['totalpopulation']    # ACS_df['population25yearsandover']
    ACS_df['NoCollege'] = (ACS_df['population25yearsandoverlessthanhighschool'] + \
                                                ACS_df['population25yearsandoverhighschoolgraduateincludesequivalency']) \
                                                / ACS_df['totalpopulation']   # ACS_df['population25yearsandover']

    ACS_df['Bachelor'] = ACS_df['population25yearsandoverbachelorsdegree'] / ACS_df['totalpopulation']    # ACS_df['population25yearsandover']
    ACS_df['Graduate'] = (ACS_df['population25yearsandovermastersdegree'] + ACS_df['population25yearsandoverprofessionalschooldegree'] + \
                                                   ACS_df['population25yearsandoverdoctoratedegree']) / ACS_df['totalpopulation'] 
      # ACS_df['population25yearsandover']
    
    
    # convert household to population
    ACS_df['household_size'] = ACS_df['totalpopulation']  / ACS_df['households']
    ACS_df['<20K'] = ACS_df['household_size'] * (ACS_df['householdslessthan10000'] + ACS_df['households10000to14999'] + \
                                                   ACS_df['households15000to19999']) / ACS_df['totalpopulation']   
    ACS_df['20K–30K'] = ACS_df['household_size'] * (ACS_df['households20000to24999'] + ACS_df['households25000to29999']) / ACS_df['totalpopulation']  
    ACS_df['30K–50K'] = ACS_df['household_size'] * (ACS_df['households30000to34999'] + ACS_df['households35000to39999'] + \
                                           ACS_df['households40000to44999'] + ACS_df['households45000to49999']) / ACS_df['totalpopulation']
    ACS_df['50K–100K'] = ACS_df['household_size'] * (ACS_df['households50000to59999'] + ACS_df['households60000to74999'] + \
                                            ACS_df['households75000to99999']) / ACS_df['totalpopulation']   # 

    ACS_df['>100K'] = ACS_df['household_size'] * (ACS_df['households100000to124999'] + ACS_df['households125000to149999'] + \
                                            ACS_df['households150000to199999'] + ACS_df['households200000ormore']) / ACS_df['totalpopulation']

    ACS_df['fips'] = ACS_df['fips'].astype(str).str.zfill(12)
    
    
    ACS_df['cbg_fips'] = ACS_df['fips'] 
    ACS_df['tract_fips'] = ACS_df['cbg_fips'].str[:11]
    ACS_df['county_fips'] = ACS_df['cbg_fips'].str[:5]
    ACS_df['state_fips'] = ACS_df['cbg_fips'].str[:2]
    
    ACS_df['nation_fips'] = 0
    ACS_df['nation_fips'] = ACS_df['nation_fips'].astype(str)
    
    ACS_df = ACS_df.replace(np.inf, np.nan)
    
    # print(ACS_df[columns].describe())
    # print(len(ACS_df))
    
    return ACS_df

In [30]:
# load monthly or weekly device sampling data


data_dir = r'L:\SafeGraph_monthly_patterns_2018-2022'
save_dir = r'P:\Shared drives\T5\safegraph_bias\refined_20230309'
svae_path = save_dir

os.makedirs(save_dir, exist_ok=True)

years = [2018, 2019, 2020, 2021, 2022]

columns = ['Female', 'Male',
       '<15', '15–17', '18–24', '25–34', '35–44', '45–54', '55–64', '>65',
       'White', 'Black', 'Hispanic', 'Asian', 'NoSchool', 'HighSchool',
       'NoCollege', 'Bachelor', 'Graduate', '<20K', '20K–30K', '30K–50K',
       '50K–100K', '>100K']

def load_data(year):
    file_name = os.path.join(data_dir, str(year), f'US_monthly_home_panel_summary_{year}.csv')
    try:
        residing_df = pd.read_csv(file_name, dtype={'census_block_group':str}, encoding='utf16')
    except:
        residing_df = pd.read_csv(file_name, dtype={'census_block_group':str}, encoding='utf8')
    residing_df['census_block_group'] = residing_df['census_block_group'].astype(str).str.zfill(12)
    
    residing_df['date_range_start'] = residing_df['year'].astype(str).str.zfill(4)  + residing_df['month'].astype(str).str.zfill(2) 
    
    if year > 2019:
        acs_year = 2019
    else:
        acs_year = year

    social_variable_df = pd.read_csv(fr'P:\Shared drives\T5\safegraph_bias\cbg_acs_{acs_year}_county_tract.csv', 
                                     dtype={'fips':str, 'tract_fips':str, 'totalpopulation':int})
    social_variable_df['fips'] = social_variable_df['fips'].astype(str).str.zfill(12)
    
    print(f"US population: {social_variable_df['totalpopulation'].sum()}, male, female:", 
          social_variable_df['female'].sum(), social_variable_df['male'].sum(), '\n')
    # social_variable_df['totalpopulation'].sum(), social_variable_df['male'].sum(), social_variable_df['female'].sum(), len(social_variable_df)
    social_variable_df = compose_variables(ACS_df=social_variable_df)
    
    # return social_variable_df
    
    fips_SafeGraph = residing_df['census_block_group'].unique()
    fips_ACS = social_variable_df['fips'].unique()
    
    print(f"FIPS count in SafeGraph：{len(fips_SafeGraph)}, in ACS: {len(fips_ACS)}", '\n')
    
    
    diff1 = sorted(set(fips_SafeGraph) - set(fips_ACS))
    print(f"FIPS only in SafeGraph but NOT in ACS:, {len(diff1)}", diff1, '\n')
    
    # print()
    diff2 = sorted(set(fips_ACS) - set(fips_SafeGraph))
    print(f"FIPS only in ACS but NOT in SafeGraph:, {len(diff2)}", diff2, '\n')
    discarded_ACS_df = social_variable_df[social_variable_df['fips'].isin(diff2)]
    extra_residing_df = residing_df[residing_df['census_block_group'].isin(diff1)]
    
    print(f"Removed devices only in {len(diff1)} SafeGraph FIPS: {extra_residing_df['number_devices_residing'].sum()} devices.", '\n')
    
    print(f"Removed these {len(discarded_ACS_df) } block groups, {discarded_ACS_df['totalpopulation'].sum()} people.", '\n')
    # social_variable_df = social_variable_df[~social_variable_df['fips'].isin(diff2)]
    
    print("Before merge ACS data row count:", len(residing_df), '\n')    
    residing_merged_df = residing_df.merge(social_variable_df, 
                                           left_on='census_block_group', 
                                           right_on='cbg_fips', how='inner')#.fillna(0)  # 'how' is very important to keep all devices and population !
    print("After merge ACS data row count: ", len(residing_merged_df), '\n')
    
    assert residing_merged_df['census_block_group'].isin(diff1).sum() == 0, 'The CBGs only in SafeGraph are not removed! '
    assert residing_merged_df['cbg_fips'].isin(diff2).sum() == 0, 'The CBGs only in ACS are not removed! '
   
    print("ACS columns:")
    print(social_variable_df.columns)

    return residing_merged_df, social_variable_df

# Note: the nan value will be ignored! 
# Note: CBGs have popultion=0 will have nan in population ratio.

# test    
year = 2022
residing_variable_df, ACS_df = load_data(year = year)
# residing_variable_df
residing_variable_df

US population: 327939105, male, female: 166551005 161465237

FIPS count in SafeGraph：220786, in ACS: 220333

FIPS only in SafeGraph but NOT in ACS:, 516 ['0CA:13020068', '0CA:13020069', '0CA:13020071', '0CA:13020079', '0CA:13020085', '0CA:13020090', '0CA:13020091', '0CA:13020092', '0CA:13020096', '0CA:13100277', '0CA:13130093', '0CA:13130094', '0CA:13130095', '0CA:13130096', '0CA:13130100', '0CA:13130101', '0CA:13130102', '0CA:13130103', '0CA:13130105', '0CA:13130106', '0CA:13130115', '0CA:13130119', '0CA:13130132', '0CA:24170059', '0CA:24170060', '0CA:24170065', '0CA:24290142', '0CA:24440063', '0CA:24450147', '0CA:24450148', '0CA:24450149', '0CA:24450150', '0CA:24690094', '0CA:24690108', '0CA:35010304', '0CA:35010306', '0CA:35010307', '0CA:35010308', '0CA:35010309', '0CA:35010310', '0CA:35010323', '0CA:35010407', '0CA:35010408', '0CA:35070201', '0CA:35070202', '0CA:35070203', '0CA:35070204', '0CA:35070205', '0CA:35070207', '0CA:35070215', '0CA:35070216', '0CA:35070222', '0CA:35070236', '0CA:35070237', '0CA:35070238', '0CA:35070241', '0CA:35070242', '0CA:35070243', '0CA:35070244', '0CA:35070248', '0CA:35070249', '0CA:35070250', '0CA:35070317', '0CA:35070324', '0CA:35100292', '0CA:35260093', '0CA:35260094', '0CA:35260095', '0CA:35260096', '0CA:35260133', '0CA:35260716', '0CA:35260718', '0CA:35260719', '0CA:35260754', '0CA:35380142', '0CA:35380326', '0CA:35380327', '0CA:35380353', '0CA:35570068', '0CA:35570070', '0CA:35570073', '0CA:35570074', '0CA:35570075', '0CA:35570076', '0CA:35570077', '0CA:35570078', '0CA:35570079', '0CA:35570080', '0CA:35570081', '0CA:35570082', '0CA:35570083', '0CA:35570084', '0CA:35570086', '0CA:35570087', '0CA:35570103', '0CA:35570105', '0CA:35570106', '0CA:35570107', '0CA:35570109', '0CA:35570111', '0CA:35570112', '0CA:35570113', '0CA:35570114', '0CA:35570121', '0CA:35570123', '0CA:35570124', '0CA:35570125', '0CA:35570127', '0CA:35570128', '0CA:35570129', '0CA:35570136', '0CA:35570137', '0CA:35570138', '0CA:35570279', '0CA:35570314', '0CA:35570375', '0CA:35570387', '0CA:35570388', '0CA:35570389', '0CA:35570414', '0CA:35570415', '0CA:35570416', '0CA:35570417', '0CA:35590066', '0CA:35590067', '0CA:35590068', '0CA:35590073', '0CA:35590076', '0CA:35590081', '0CA:35590087', '0CA:35590089', '0CA:35590090', '0CA:35590091', '0CA:35590092', '0CA:35590093', '0CA:35590094', '0CA:35590095', '0CA:35590124', '0CA:59090159', '600109501002', '600109503001', '600109503003', '600109505001', '600109505002', '600109506001', '600109506002', '600109506003', '600109507001', '600109507002', '600109507003', '600109509002', '600109509003', '600209518002', '600509510001', '600509510002', '600509511001', '600509511002', '600509511003', '600509512011', '600509512012', '600509512021', '600509512022', '600509512031', '600509512032', '600509513001', '600509513002', '600509515001', '600509516001', '600509516003', '600509516004', '660109501001', '660109501002', '660109501003', '660109501004', '660109501005', '660109502003', '660109502004', '660109502005', '660109503001', '660109503002', '660109503003', '660109503004', '660109503005', '660109503006', '660109503007', '660109503008', '660109503009', '660109504011', '660109504012', '660109504013', '660109504014', '660109504015', '660109504016', '660109504021', '660109504022', '660109504023', '660109505011', '660109505012', '660109505021', '660109505022', '660109505023', '660109505024', '660109505025', '660109507011', '660109507012', '660109507013', '660109507014', '660109507015', '660109507016', '660109507017', '660109507021', '660109507022', '660109507023', '660109507024', '660109507025', '660109508011', '660109508012', '660109508013', '660109508014', '660109508021', '660109508022', '660109508023', '660109508024', '660109509001', '660109509002', '660109509003', '660109509004', '660109509005', '660109509006', '660109509007', '660109510001', '660109510002', '660109510003', '660109510004', '660109510005', '660109510006', '660109510007', '660109510008', '660109511001', '660109511002', '660109511003', '660109511004', '660109511005', '660109511006', '660109516001', '660109516002', '660109517001', '660109517002', '660109518001', '660109519011', '660109519012', '660109519013', '660109519014', '660109519021', '660109519022', '660109519023', '660109519024', '660109522001', '660109522002', '660109522003', '660109522004', '660109523001', '660109523002', '660109523003', '660109524001', '660109524002', '660109527001', '660109527002', '660109527003', '660109527004', '660109527005', '660109528002', '660109529001', '660109529002', '660109529003', '660109529004', '660109529005', '660109529006', '660109530001', '660109530002', '660109530003', '660109530004', '660109530005', '660109531011', '660109531012', '660109531013', '660109531021', '660109531022', '660109531023', '660109532001', '660109532002', '660109532003', '660109533001', '660109533002', '660109533003', '660109533004', '660109534001', '660109534002', '660109535001', '660109536001', '660109536002', '660109536003', '660109536004', '660109536005', '660109539001', '660109539002', '660109539003', '660109539004', '660109540001', '660109540002', '660109543001', '660109543002', '660109544001', '660109544003', '660109544004', '660109544005', '660109544006', '660109545001', '660109545002', '660109545003', '660109545004', '660109547001', '660109547002', '660109547003', '660109548001', '660109548002', '660109548003', '660109548004', '660109551001', '660109551002', '660109551003', '660109551004', '660109552001', '660109552002', '660109552003', '660109553001', '660109553002', '660109554001', '660109556001', '660109556002', '660109557001', '660109557002', '660109557003', '660109557004', '660109557005', '660109557006', '660109558001', '660109558002', '660109558003', '660109558004', '660109558005', '660109558006', '660109558007', '660109558008', '660109558009', '660109559001', '660109559002', '660109559003', '660109560001', '660109560002', '660109561001', '660109561002', '660109561004', '660109562001', '660109562002', '660109562003', '660109562004', '660109562005', '660109563001', '660109563004', '660109563005', '660109801001', '660109804001', '660109900000', '691009501001', '691009501002', '691009501003', '691009900000', '691100001001', '691100001002', '691100002001', '691100002002', '691100003001', '691100003002', '691100004001', '691100004002', '691100005001', '691100005002', '691100006001', '691100006002', '691100006003', '691100007001', '691100007002', '691100007003', '691100008001', '691100008002', '691100009001', '691100009002', '691100009003', '691100010001', '691100010002', '691100011001', '691100012001', '691100012002', '691100013001', '691100013002', '691100013003', '691100014001', '691100014002', '691100014003', '691100015001', '691100015002', '691100015003', '691100015004', '691100015005', '691100016001', '691100016002', '691100017001', '691100017002', '691100017003', '691100017004', '691109900000', '691209501011', '691209501012', '691209501013', '691209502001', '691209502002', '780109701001', '780109701002', '780109702001', '780109702002', '780109703001', '780109703002', '780109703003', '780109704001', '780109704002', '780109704003', '780109704004', '780109705001', '780109705002', '780109705003', '780109706001', '780109706002', '780109706003', '780109706004', '780109706005', '780109707001', '780109707002', '780109707003', '780109708001', '780109708002', '780109709001', '780109710001', '780109710002', '780109711001', '780109711002', '780109711003', '780109711004', '780109712001', '780109712002', '780109712003', '780109712004', '780109713001', '780109713002', '780109713003', '780109714001', '780109715001', '780109715002', '780109715003', '780109900000', '780209501001', '780209501002', '780209501003', '780209502001', '780209502002', '780209502003', '780209502004', '780209900000', '780309601001', '780309601002', '780309601003', '780309602001', '780309602002', '780309602003', '780309603001', '780309603002', '780309603003', '780309604001', '780309604002', '780309604003', '780309604004', '780309605001', '780309605002', '780309605003', '780309605004', '780309605005', '780309606001', '780309606002', '780309606003', '780309607001', '780309607002', '780309607003', '780309608001', '780309608002', '780309609001', '780309609002', '780309610001', '780309610002', '780309610003', '780309610004', '780309610005', '780309611001', '780309611002', '780309612001', '780309612002', '780309900000']

FIPS only in ACS but NOT in SafeGraph:, 63 ['060374300033', '060374604012', '060759804011', '120659900000', '120839801001', '131919900000', '150019900000', '150019901000', '150019906000', '150019909000', '150019910000', '150019911000', '150019914000', '150039812001', '150070412002', '150079902000', '150079903000', '160439701002', '220870301053', '260099900000', '260539900000', '260619901000', '260959900000', '261579900000', '300290017002', '325109900000', '340297310020', '340297360010', '350010047421', '350439403001', '360050319000', '360599902000', '360639401001', '360850081000', '360850223003', '361190056001', '370159604000', '370559701020', '371379901000', '410459400001', '440050401031', '480719900000', '482619900000', '484899900000', '511039901000', '530619901000', '550519900000', '720039900000', '720059900000', '720119900000', '720179900000', '720339800081', '720519900210', '720539901030', '720599900010', '720719900000', '720919900250', '720959900000', '721039900130', '721099900000', '721119900000', '721139930000', '721159900000']

Removed devices only in 516 SafeGraph FIPS: 73689 devices.

Removed these 63 block groups, 3 people.

Before merge ACS data row count: 2644588

After merge ACS data row count:  2640121

ACS columns:
Index(['state_fips', 'county_fips', 'tract_fips', 'fips', 'state',
       'totalpopulation', 'male', 'female', 'under5years', '5to9years',
       '10to14years', '15to17years', '18to24years', '25to34years',
       '35to44years', '45to54years', '55to64years', '65to74years',
       '75to84years', '85yearsandover', 'whitealone',
       'blackorafricanamericanalone', 'americanindianandalaskanativealone',
       'asianalone', 'nativehawaiianandotherpacificislanderalone',
       'someotherracealone', 'twoormoreraces', 'Hispanic_or_Latino',
       'population25yearsandover',
       'population25yearsandoverlessthanhighschool',
       'population25yearsandoverhighschoolgraduateincludesequivalency',
       'population25yearsandoversomecollege',
       'population25yearsandoverbachelorsdegree',
       'population25yearsandovermastersdegree',
       'population25yearsandoverprofessionalschooldegree',
       'population25yearsandoverdoctoratedegree', 'households',
       'householdslessthan10000', 'households10000to14999',
       'households15000to19999', 'households20000to24999',
       'households25000to29999', 'households30000to34999',
       'households35000to39999', 'households40000to44999',
       'households45000to49999', 'households50000to59999',
       'households60000to74999', 'households75000to99999',
       'households100000to124999', 'households125000to149999',
       'households150000to199999', 'households200000ormore', 'Female', 'Male',
       '<15', '15–17', '18–24', '25–34', '35–44', '45–54', '55–64', '>65',
       'White', 'Black', 'Hispanic', 'Asian', 'NoSchool', 'HighSchool',
       'NoCollege', 'Bachelor', 'Graduate', 'household_size', '<20K',
       '20K–30K', '30K–50K', '50K–100K', '>100K', 'cbg_fips', 'nation_fips'],
      dtype='object')

,year,month,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime,date_range_start,state_fips,county_fips,tract_fips,fips,state,totalpopulation,male,female,under5years,5to9years,10to14years,15to17years,18to24years,25to34years,35to44years,45to54years,55to64years,65to74years,75to84years,85yearsandover,whitealone,blackorafricanamericanalone,americanindianandalaskanativealone,asianalone,nativehawaiianandotherpacificislanderalone,someotherracealone,twoormoreraces,Hispanic_or_Latino,population25yearsandover,population25yearsandoverlessthanhighschool,population25yearsandoverhighschoolgraduateincludesequivalency,population25yearsandoversomecollege,population25yearsandoverbachelorsdegree,population25yearsandovermastersdegree,population25yearsandoverprofessionalschooldegree,population25yearsandoverdoctoratedegree,households,householdslessthan10000,households10000to14999,households15000to19999,households20000to24999,households25000to29999,households30000to34999,households35000to39999,households40000to44999,households45000to49999,households50000to59999,households60000to74999,households75000to99999,households100000to124999,households125000to149999,households150000to199999,households200000ormore,Female,Male,<15,15–17,18–24,25–34,35–44,45–54,55–64,>65,White,Black,Hispanic,Asian,NoSchool,HighSchool,NoCollege,Bachelor,Graduate,household_size,<20K,20K–30K,30K–50K,50K–100K,>100K,cbg_fips,nation_fips
0,2022,1,ak,US,020200002021,211,91,202201,02,02020,02020000202,020200002021,ak,1189,585,604,89,76,22,41,127,127,86,127,116,117,80,39,1074,0,5,60,0,50,0,0,824,99,175,127,127,62,0,0,616,19,83,59,0,18,72,35,0,21,13,127,36,0,72,33,19,0.508,0.492,0.157,0.034,0.107,0.107,0.072,0.107,0.098,0.198,0.903,0.000,0.000,0.050,0.083,0.147,0.230,0.107,0.052,1.930,0.261,0.029,0.208,0.286,0.201,020200002021,0
1,2022,2,ak,US,020200002021,198,95,202202,02,02020,02020000202,020200002021,ak,1189,585,604,89,76,22,41,127,127,86,127,116,117,80,39,1074,0,5,60,0,50,0,0,824,99,175,127,127,62,0,0,616,19,83,59,0,18,72,35,0,21,13,127,36,0,72,33,19,0.508,0.492,0.157,0.034,0.107,0.107,0.072,0.107,0.098,0.198,0.903,0.000,0.000,0.050,0.083,0.147,0.230,0.107,0.052,1.930,0.261,0.029,0.208,0.286,0.201,020200002021,0
2,2022,3,ak,US,020200002021,259,184,202203,02,02020,02020000202,020200002021,ak,1189,585,604,89,76,22,41,127,127,86,127,116,117,80,39,1074,0,5,60,0,50,0,0,824,99,175,127,127,62,0,0,616,19,83,59,0,18,72,35,0,21,13,127,36,0,72,33,19,0.508,0.492,0.157,0.034,0.107,0.107,0.072,0.107,0.098,0.198,0.903,0.000,0.000,0.050,0.083,0.147,0.230,0.107,0.052,1.930,0.261,0.029,0.208,0.286,0.201,020200002021,0
3,2022,4,ak,US,020200002021,222,231,202204,02,02020,02020000202,020200002021,ak,1189,585,604,89,76,22,41,127,127,86,127,116,117,80,39,1074,0,5,60,0,50,0,0,824,99,175,127,127,62,0,0,616,19,83,59,0,18,72,35,0,21,13,127,36,0,72,33,19,0.508,0.492,0.157,0.034,0.107,0.107,0.072,0.107,0.098,0.198,0.903,0.000,0.000,0.050,0.083,0.147,0.230,0.107,0.052,1.930,0.261,0.029,0.208,0.286,0.201,020200002021,0
4,2022,5,ak,US,020200002021,281,260,202205,02,02020,02020000202,020200002021,ak,1189,585,604,89,76,22,41,127,127,86,127,116,117,80,39,1074,0,5,60,0,50,0,0,824,99,175,127,127,62,0,0,616,19,83,59,0,18,72,35,0,21,13,127,36,0,72,33,19,0.508,0.492,0.157,0.034,0.107,0.107,0.072,0.107,0.098,0.198,0.903,0.000,0.000,0.050,0.083,0.147,0.230,0.107,0.052,1.930,0.261,0.029,0.208,0.286,0.201,020200002021,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2640116,2022,10,ca,US,060374303012,0,1,202210,06,06037,06037430301,060374303012,ca,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,060374303012,0
2640117,2022,11,ca,US,060374303012,0,2,202211,06,06037,06037430301,060374303012,ca,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,060374303012,0
2640118,2022,11,md,US,240359902000,2,1,202211,24,24035,24035990200,240359902000,md,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,240359902000,0
2640119,2022,11,ny,US,360850074000,1,0,202211,36,36085,36085007400,360850074000,ny,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,360850074000,0
2640120,2022,12,ny,US,360850074000,1,0,202212,36,36085,36085007400,360850074000,ny,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,360850074000,0

In [31]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)

residing_variable_df[columns + ['household_size']].describe()

,Female,Male,<15,15–17,18–24,25–34,35–44,45–54,55–64,>65,White,Black,Hispanic,Asian,NoSchool,HighSchool,NoCollege,Bachelor,Graduate,<20K,20K–30K,30K–50K,50K–100K,>100K,household_size
count,2629960.000,2629960.000,2629960.000,2629960.000,2629960.000,2629960.000,2629960.000,2629960.000,2629960.000,2629960.000,2629960.000,2629960.000,2629960.000,2629960.000,2629960.000,2629960.000,2629960.000,2629960.000,2629960.000,2624514.000,2624514.000,2624514.000,2624514.000,2624514.000,2624514.000
mean,0.509,0.491,0.154,0.035,0.065,0.086,0.084,0.089,0.093,0.144,0.730,0.048,0.172,0.026,0.062,0.195,0.257,0.078,0.071,0.158,0.094,0.172,0.283,0.258,2.943
std,0.066,0.066,0.065,0.026,0.038,0.044,0.039,0.042,0.047,0.079,0.266,0.064,0.241,0.038,0.047,0.097,0.120,0.047,0.065,0.132,0.075,0.098,0.113,0.180,10.143
min,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000
25%,0.474,0.455,0.113,0.017,0.041,0.056,0.058,0.060,0.061,0.090,0.596,0.000,0.014,0.000,0.028,0.125,0.173,0.047,0.024,0.061,0.038,0.101,0.208,0.115,2.283
50%,0.509,0.491,0.152,0.033,0.061,0.080,0.080,0.083,0.086,0.133,0.823,0.028,0.067,0.007,0.055,0.191,0.256,0.072,0.053,0.126,0.080,0.164,0.282,0.227,2.608
75%,0.545,0.526,0.193,0.050,0.084,0.108,0.106,0.112,0.117,0.184,0.939,0.073,0.218,0.041,0.086,0.259,0.336,0.102,0.098,0.222,0.134,0.232,0.355,0.376,3.000
max,1.000,1.000,0.768,0.848,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1710.250

In [7]:
residing_variable_df['number_devices_residing'].isna().sum()
residing_variable_df.isna().sum()

year                      0
month                     0
region                    0
iso_country_code          0
census_block_group        0
                      ...
30K–50K               15607
50K–100K              15607
>100K                 15607
cbg_fips                  0
nation_fips               0
Length: 88, dtype: int64

In [ ]:
# residing_merged_df['Female'].mean(), residing_merged_df['Asian'].mean(), residing_merged_df['White'].mean(), residing_merged_df['Black'].mean(), residing_merged_df['Hispanic'].mean(), residing_merged_df['50K–100K'].mean()

In [52]:
# residing_merged_df['Female'].mean(), residing_merged_df['Asian'].mean(), residing_merged_df['White'].mean(), residing_merged_df['Black'].mean(), residing_merged_df['Hispanic'].mean(), residing_merged_df['50K–100K'].mean()

In [80]:
# Issue: the income range cannot sum to 1
# residing_variable_df.sample(10).iloc[:, -5:].sum(axis=1)

# Compute device sampling rate

## Monthly

In [2]:
import numpy as np
def get_sampling_rate(residing_df, ACS_df, aggre_columns):
    # residing_df['date_range_start'] = residing_df['date_range_start'].astype(str).str[:10]
    aggre_columns = ['date_range_start'] + aggre_columns
    
    # device_count_total = # including have
    
    sampling_rate_df = residing_df.groupby(aggre_columns).agg(
                                      
                                      start_date=('date_range_start', 'first'), 
                                      end_date=('date_range_start', 'last'), 
                                      # period_count=('CBG_count', 'count'), 
                                      CBG_count=('totalpopulation', 'count'), 
                                      fips=(aggre_columns[-1], 'first'), 
                                      device_count=('number_devices_residing', 'sum'), 
                                      population=('totalpopulation', 'sum'), 
                                      year=('year', 'first'),
                                      aggre_column_value=(aggre_columns[-1], 'first'), 
                                      # safegraph_ratio_max=('safegraph_ratio', max),
                                      # census_ratio=('census_ratio', 'mean'),
                                      # census_ratio_max=('census_ratio', max),
                                      # census_ratio_min=('census_ratio', min),
                                     )
    
    # sampling_rate_df['fips'] = 
    
    sampling_rate_df['population'] = sampling_rate_df['population'].astype(int)
    
    if aggre_columns[-1] == 'nation_fips':
        sampling_rate_df['population'] = ACS_df['totalpopulation'].sum()
        # sampling_rate_df['population'] = ACS_df['totalpopulation'].sum()
    
    sampling_rate_df['sampling_rate'] = sampling_rate_df['device_count'] / sampling_rate_df['population']
    sampling_rate_df.replace([np.inf], np.nan, inplace=True)

    return sampling_rate_df.reset_index().iloc[:, 2:]

  
def compute_sampling_rates(df, ACS_df, aggre_columns = ['nation_fips', 'state_fips', 'county_fips', 'tract_fips', 'cbg_fips']):
    df_list = []
    for c in aggre_columns:
        sampling_rate_df = get_sampling_rate(df, ACS_df, aggre_columns=[c])
        df_list.append(sampling_rate_df)
        
    df_all = pd.concat(df_list)
    
    return df_all

# df_all = compute_sampling_rates(residing_variable_df, aggre_columns = ['state_fips', 'county_fips', 'tract_fips', 'cbg_fips'])
# df_all = compute_sampling_rates(df,                        aggre_columns = ['state_fips', 'county_fips', 'tract_fips', 'cbg_fips'])
df_all = compute_sampling_rates(residing_variable_df, ACS_df=ACS_df, aggre_columns = ['nation_fips', 'state_fips', 'county_fips', 'tract_fips', 'cbg_fips'])

df_all['fips_len'] = df_all['fips'].astype(str).str.len()
df_all['fips_level'] = df_all['fips_len'].astype(str)
df_all['fips_level'] = df_all['fips_level'].replace({'1': 'nation', '2':"state", '5':"county", '11': 'tract', '12':'CBG'})

sampling_rates_csv_name = fr'P:\Shared drives\T5\safegraph_bias\sampling_rates_{year}_monthly.csv'
df_all.to_csv(sampling_rates_csv_name, index=False)
df_all

NameError: name 'residing_variable_df' is not defined

In [29]:
df_all['fips_level'].value_counts()

CBG       2640121
tract      885862
county      38640
state         624
nation         12
Name: fips_level, dtype: int64

In [30]:
df_all.groupby(['fips_level']).mean()

C:\Users\N\AppData\Local\Temp\ipykernel_10560\2664521766.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_all.groupby(['fips_level']).mean()

,CBG_count,device_count,population,year,sampling_rate,fips_len
fips_level,,,,,,
CBG,1.000,125.135,1490.419,2022.000,0.099,12.000
county,68.326,8549.968,101834.527,2022.000,0.094,5.000
nation,220010.083,27530897.750,327939105.000,2022.000,0.084,1.000
state,4230.963,529440.341,6305907.253,2022.000,0.085,2.000
tract,2.980,372.937,4441.873,2022.000,0.108,11.000

## Aggregate to yearly

In [32]:
def time_aggregate(sampling_rate_df):
    
    rate_gb_df = sampling_rate_df.groupby(['year', 'fips']).agg(
                                      start_date=('start_date', 'first'), 
                                      end_date=('end_date', 'last'), 
                                      period_count=('start_date', 'count'), 
                                      CBG_count=('CBG_count', 'mean'), 
                                      device_count_mean=('device_count', 'mean'), 
                                      population=('population', 'mean'), 
                                      sampling_rate_mean=('sampling_rate', 'mean'),
                                      sampling_rate_max=('sampling_rate', max),
                                      sampling_rate_min=('sampling_rate', min),        
                                     )
    
    return rate_gb_df
    
rate_gb_df = time_aggregate(df_all.iloc[:]).reset_index()# .query(" sampling_rate < 0.5 ")).reset_index()  # remove the outliers
# rate_gb_df.to_csv(r'P:\Shared drives\NJIT_T5\safegraph_bias\sampling_rates_yearly.csv', index=False)
rate_gb_df['fips_len'] = rate_gb_df['fips'].astype(str).str.len()
rate_gb_df['fips_level'] = rate_gb_df['fips_len'].astype(str)
rate_gb_df['fips_level'] = rate_gb_df['fips_level'].replace({'1':'nation', '2':"state", '5':"county", '11': 'tract', '12':'cbg'})

rate_gb_df.to_csv(fr'P:\Shared drives\T5\safegraph_bias\sampling_rates_{year}_monthly_yearly.csv', index=False)
# 
rate_gb_df

,year,fips,start_date,end_date,period_count,CBG_count,device_count_mean,population,sampling_rate_mean,sampling_rate_max,sampling_rate_min,fips_len,fips_level
0,2022,Deep South,202201,202212,12,55145.167,9173446.083,94022781.500,0.098,0.149,0.062,10,10

# Compute bias

In [68]:
from tqdm import tqdm
from datetime import datetime
import os
tqdm.pandas()

columns = ['Female', 'Male',
       '<15', '15–17', '18–24', '25–34', '35–44', '45–54', '55–64', '>65',
       'White', 'Black', 'Hispanic', 'Asian', 'NoSchool', 'HighSchool',
       'NoCollege', 'Bachelor', 'Graduate', '<20K', '20K–30K', '30K–50K',
       '50K–100K', '>100K']

used_columns = ['date_range_start', 'nation_fips', 'state_fips', 'county_fips', 'tract_fips', 'number_devices_residing', 'totalpopulation'] + columns

def get_bias(df, aggre_column):
    
    # if df.isna().sum() > 0:
    #     print(df)
#     now = datetime.now()
#     current_time = now.strftime("%H:%M:%S")
#     if current_time[-2] == '5':
#         print("Current state:", df.iloc[0]['state_fips'])
        
#     if current_time[-2] == '2':
#         print("Current state:", df.iloc[0]['state_fips'])
    
    df = df.dropna()
    
    aggre_total_device = df['number_devices_residing'].sum()
    
    aggre_total_pop = df['totalpopulation'].sum()
    
    if  aggre_column == 'nation_fips':
        aggre_total_pop = ACS_df['totalpopulation'].sum()
#         print(f"Use the US population {aggre_total_pop} the the naion level bias:")
    
    result_df = pd.DataFrame(columns = [ 'start_date', 'census_ratio', 'safegraph_ratio', 'CBG_count', 'device_count', 'populaion', 'safegraph_ratio_to_census', 'bias'],
                   index = columns)
    
    result_df.index.name = 'variable'
    
    
    # return result_df
    for column in columns[:]:
        # print(column)
        start_date = df.iloc[0]['date_range_start'][:10] 
        
        # df[column] = df[column] / df['totalpopulation']  # population group ratio of each CBG
        
        cbg_column_devices = df['number_devices_residing'] * df[column]   # population group device count  of each CBG
        # cbg_device_ratio = cbg_column_devices.sum() / state_total_device  # aggregated population group device count / total_device

        cbg_column_pop = df[column] * df['totalpopulation']  # group population  of each CBG        
        census_ratio = cbg_column_pop.sum() / aggre_total_pop   # group population ratio (to the aggregated population)    
        
        safegraph_ratio = cbg_column_devices.sum() / aggre_total_device   # group population device ratio (to the aggregated device count)    
        
        # result_df.loc[column]['variable'] = column
        result_df.loc[column]['start_date'] = start_date
        result_df.loc[column]['CBG_count'] = len(df)
        result_df.loc[column]['census_ratio'] = census_ratio
        result_df.loc[column]['safegraph_ratio'] = safegraph_ratio
        result_df.loc[column]['populaion'] = cbg_column_pop.sum()
        result_df.loc[column]['device_count'] = cbg_column_devices.sum() 
        result_df.loc[column]['safegraph_ratio_to_census'] = result_df.loc[column]['safegraph_ratio'] / result_df.loc[column]['census_ratio'] 
        result_df.loc[column]['bias'] = result_df.loc[column]['safegraph_ratio_to_census'] - 1
 

    return result_df


def get_aggregated_bias(residing_df, aggre_columns):
    
    residing_df.loc[:, 'state_fips'] = residing_df['state_fips'].astype(str).str.zfill(2)
    
    residing_df['date_range_start'] = residing_df['date_range_start'].astype(str).str[:10]   # have an issue of different starting hours 
    groupby_cols = ['date_range_start'] + aggre_columns
    # return aggre_columns

    bias_df = residing_df.sort_values('date_range_start').groupby(groupby_cols).progress_apply(get_bias, aggre_column=aggre_columns[-1])
    
    # return bias_df

    bias_df.reset_index(drop=False, inplace=True)
    # bias_df['start_date'] = bias_df['date_range_start'].astype(str).str[:10] 
    # bias_df = bias_df.drop(columns=['date_range_start'])
    
    # return aggre_columns + ['variable']
    
    # yearly
    bias_gb_df = bias_df.groupby(aggre_columns + ['variable']).agg(
                                      start_date=('start_date', 'first'), 
                                      end_date=('start_date', 'last'), 
                                      period_count=('CBG_count', 'count'), 
                                      CBG_count=('CBG_count', 'mean'), 
                                      safegraph_ratio_mean=('safegraph_ratio', 'mean'), 
                                      safegraph_ratio_median=('safegraph_ratio', 'median'), 
                                      safegraph_ratio_min=('safegraph_ratio', min), 
                                      safegraph_ratio_max=('safegraph_ratio', max),
                                      census_ratio=('census_ratio', 'mean'),
                                      device_count=('device_count', 'mean'),
                                      population=('populaion', 'mean'),
                                     )
    
    # return bias_gb_df

    # if len(aggre_columns) == 1:
    #     bias_gb_df = bias_gb_df.loc[:, columns, :]  
    # if len(aggre_columns) == 2:
    #     bias_gb_df = bias_gb_df.loc[:, :, columns, :]  
    # if len(aggre_columns) == 3:
    #     bias_gb_df = bias_gb_df.loc[:, :, :, columns, :]  

    bias_gb_df['safegraph_ratio_mean_to_census'] = bias_gb_df['safegraph_ratio_mean'] / bias_gb_df['census_ratio']
    bias_gb_df['safegraph_ratio_median_to_census' ] = bias_gb_df['safegraph_ratio_median' ] / bias_gb_df['census_ratio']
    bias_gb_df['safegraph_ratio_min_to_census' ] = bias_gb_df['safegraph_ratio_min' ] / bias_gb_df['census_ratio']
    bias_gb_df['safegraph_ratio_max_to_census' ] = bias_gb_df['safegraph_ratio_max' ] / bias_gb_df['census_ratio']
    bias_gb_df['bias' ] = bias_gb_df['safegraph_ratio_mean_to_census' ] - 1
    bias_gb_df['bias_median' ] = bias_gb_df['safegraph_ratio_median_to_census' ] - 1
    bias_gb_df['bias_min' ] = bias_gb_df['safegraph_ratio_min_to_census' ] - 1
    bias_gb_df['bias_max' ] = bias_gb_df['safegraph_ratio_max_to_census' ] - 1
    
    bias_gb_df['CBG_count'] = bias_gb_df['CBG_count'].astype(int)
    
    bias_gb_df = bias_gb_df.reset_index()
    bias_gb_df['variable'] = pd.Categorical(bias_gb_df['variable'], categories=columns, ordered=True)

    bias_gb_df = bias_gb_df.sort_values(aggre_columns + ['variable']) #   sort

  
    return bias_gb_df, bias_df

def compute_nation_bias():
    # save_path = r'P:\Shared drives\T5\safegraph_bias'
    new_name = os.path.join(save_dir, f'monthly_bias_nation_{year}.csv')

    aggre_columns = ['nation_fips']
    
    if  aggre_columns[-1] == 'nation_fips':
    # aggre_total_pop = ACS_df['totalpopulation'].sum()
        print(f"Use the US population {ACS_df['totalpopulation'].sum() } for the naion level bias:")

    bias_gb_df, bias_df = get_aggregated_bias(residing_df=residing_variable_df.dropna(), aggre_columns=aggre_columns[:])
    # bias_gb_df = get_aggregated_bias(residing_df=SC_residing_df[used_columns], aggre_columns=aggre_columns[:])
    bias_gb_df.to_csv(new_name, index=False)
    
    new_name = os.path.join(save_dir, f'monthly_bias_nation_{year}_time.csv')
    bias_df.to_csv(new_name, index=False)
    
    return bias_gb_df, bias_df

def compute_state_bias():
    # save_path = r'P:\Shared drives\T5\safegraph_bias'
    new_name = os.path.join(save_dir, f'monthly_bias_state_{year}.csv')
    aggre_columns = ['state_fips']

    # bias_gb_df = get_aggregated_bias(residing_df=SC_residing_df[used_columns], aggre_columns=aggre_columns)
    bias_gb_df, bias_df = get_aggregated_bias(residing_df=residing_variable_df[used_columns].dropna(), aggre_columns=aggre_columns)
    
    bias_gb_df.to_csv(new_name, index=False)
    
    new_name = os.path.join(save_dir, f'monthly_bias_state_{year}_time.csv')
    bias_df.to_csv(new_name, index=False)
    
    return bias_gb_df, bias_df

def compute_county_bias():
    # save_path = r'P:\Shared drives\T5\safegraph_bias'
    new_name = os.path.join(save_dir, f'monthly_bias_county_{year}.csv')

    aggre_columns = ['state_fips', 'county_fips']
    bias_gb_df, bias_df = get_aggregated_bias(residing_df=residing_variable_df.iloc[:].dropna(), aggre_columns=aggre_columns[:])
    # bias_gb_df = get_aggregated_bias(residing_df=SC_residing_df[used_columns], aggre_columns=aggre_columns[:])
    bias_gb_df.to_csv(new_name, index=False)
    
    new_name = os.path.join(save_dir, f'monthly_bias_county_{year}_time.csv')
    bias_df.to_csv(new_name, index=False)
    
    return bias_gb_df, bias_df


def compute_region_bias():
    # save_path = r'P:\Shared drives\T5\safegraph_bias'
    
    

    aggre_columns = ['region_tag']
    
    
    new_name = os.path.join(save_dir, f'monthly_bias_{region_name}_{year}.csv')

    bias_gb_df, bias_df = get_aggregated_bias(residing_df=residing_variable_df.dropna(), aggre_columns=aggre_columns[:])
    # bias_gb_df = get_aggregated_bias(residing_df=SC_residing_df[used_columns], aggre_columns=aggre_columns[:])
    bias_gb_df.to_csv(new_name, index=False)
    
    new_name = os.path.join(save_dir, f'monthly_bias_region_{region_name}_{year}_time.csv')
    
    
    bias_df.to_csv(new_name, index=False)
    
    return bias_gb_df, bias_df

# Not used! 
# def compute_tract_bias():
#     save_path = r'P:\Shared drives\T5\safegraph_bias'
#     # new_name = os.path.join(save_path, f'monthly_bias_tract_{YEAR}.csv')

#     aggre_columns = ['state_fips', 'county_fips', 'tract_fips']
#     bias_gb_df, bias_df = get_aggregated_bias(residing_df=residing_variable_df[used_columns].dropna(), aggre_columns=aggre_columns[:])
#     # bias_gb_df = get_aggregated_bias(residing_df=SC_residing_df.iloc[:1000], aggre_columns=aggre_columns[:])
    
#     bias_gb_df.to_csv(new_name, index=False)
    
#     # new_name = os.path.join(save_path, f'monthly_bias_tract_{YEAR}_time.csv')
#     bias_df.to_csv(new_name, index=False)
    
#     return bias_gb_df, bias_df
# bias_gb_df, bias_df = compute_tract_bias()

# YEAR = year

# bias_gb_df, bias_df = compute_nation_bias()
# bias_gb_df, bias_df = compute_state_bias()
# bias_gb_df, bias_df = compute_county_bias()
# bias_gb_df, bias_df = compute_region_bias()


# bias_gb_df.round(3)

In [429]:
# bias_gb_df.to_csv(r'P:\Shared drives\NJIT_T5\safegraph_bias\weekly_bias_county_2021.csv', index=False)

In [ ]:
stop

# All code

## For a region

In [42]:
residing_variable_df

,year,month,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime,date_range_start,state_fips,county_fips,tract_fips,fips,state,totalpopulation,male,female,under5years,5to9years,10to14years,15to17years,18to24years,25to34years,35to44years,45to54years,55to64years,65to74years,75to84years,85yearsandover,whitealone,blackorafricanamericanalone,americanindianandalaskanativealone,asianalone,nativehawaiianandotherpacificislanderalone,someotherracealone,twoormoreraces,Hispanic_or_Latino,population25yearsandover,population25yearsandoverlessthanhighschool,population25yearsandoverhighschoolgraduateincludesequivalency,population25yearsandoversomecollege,population25yearsandoverbachelorsdegree,population25yearsandovermastersdegree,population25yearsandoverprofessionalschooldegree,population25yearsandoverdoctoratedegree,households,householdslessthan10000,households10000to14999,households15000to19999,households20000to24999,households25000to29999,households30000to34999,households35000to39999,households40000to44999,households45000to49999,households50000to59999,households60000to74999,households75000to99999,households100000to124999,households125000to149999,households150000to199999,households200000ormore,Female,Male,<15,15–17,18–24,25–34,35–44,45–54,55–64,>65,White,Black,Hispanic,Asian,NoSchool,HighSchool,NoCollege,Bachelor,Graduate,household_size,<20K,20K–30K,30K–50K,50K–100K,>100K,cbg_fips,nation_fips,region_tag
6360,2018,1,al,US,010499609002,34,27,201801,01,01049,01049960900,010499609002,al,718,353,365,0,0,84,35,44,17,127,79,126,107,12,0,629,88,0,0,0,0,1,0,555,117,108,127,31,0,0,0,366.000,21.000,19.000,31.000,15.000,55.000,31.000,38.000,16.000,0.000,11.000,22.000,35.000,55.000,6.000,11.000,0.000,0.508,0.492,0.117,0.049,0.061,0.024,0.177,0.110,0.175,0.166,0.876,0.123,0.000,0.000,0.163,0.150,0.313,0.043,0.000,1.962,0.194,0.191,0.232,0.186,0.197,010499609002,0,Deep South
6361,2018,2,al,US,010499609002,29,33,201802,01,01049,01049960900,010499609002,al,718,353,365,0,0,84,35,44,17,127,79,126,107,12,0,629,88,0,0,0,0,1,0,555,117,108,127,31,0,0,0,366.000,21.000,19.000,31.000,15.000,55.000,31.000,38.000,16.000,0.000,11.000,22.000,35.000,55.000,6.000,11.000,0.000,0.508,0.492,0.117,0.049,0.061,0.024,0.177,0.110,0.175,0.166,0.876,0.123,0.000,0.000,0.163,0.150,0.313,0.043,0.000,1.962,0.194,0.191,0.232,0.186,0.197,010499609002,0,Deep South
6362,2018,3,al,US,010499609002,51,40,201803,01,01049,01049960900,010499609002,al,718,353,365,0,0,84,35,44,17,127,79,126,107,12,0,629,88,0,0,0,0,1,0,555,117,108,127,31,0,0,0,366.000,21.000,19.000,31.000,15.000,55.000,31.000,38.000,16.000,0.000,11.000,22.000,35.000,55.000,6.000,11.000,0.000,0.508,0.492,0.117,0.049,0.061,0.024,0.177,0.110,0.175,0.166,0.876,0.123,0.000,0.000,0.163,0.150,0.313,0.043,0.000,1.962,0.194,0.191,0.232,0.186,0.197,010499609002,0,Deep South
6363,2018,4,al,US,010499609002,45,37,201804,01,01049,01049960900,010499609002,al,718,353,365,0,0,84,35,44,17,127,79,126,107,12,0,629,88,0,0,0,0,1,0,555,117,108,127,31,0,0,0,366.000,21.000,19.000,31.000,15.000,55.000,31.000,38.000,16.000,0.000,11.000,22.000,35.000,55.000,6.000,11.000,0.000,0.508,0.492,0.117,0.049,0.061,0.024,0.177,0.110,0.175,0.166,0.876,0.123,0.000,0.000,0.163,0.150,0.313,0.043,0.000,1.962,0.194,0.191,0.232,0.186,0.197,010499609002,0,Deep South
6364,2018,5,al,US,010499609002,42,43,201805,01,01049,01049960900,010499609002,al,718,353,365,0,0,84,35,44,17,127,79,126,107,12,0,629,88,0,0,0,0,1,0,555,117,108,127,31,0,0,0,366.000,21.000,19.000,31.000,15.000,55.000,31.000,38.000,16.000,0.000,11.000,22.000,35.000,55.000,6.000,11.000,0.000,0.508,0.492,0.117,0.049,0.061,0.024,0.177,0.110,0.175,0.166,0.876,0.123,0.000,0.000,0.163,0.150,0.313,0.043,0.000,1.962,0.194,0.191,0.232,0.186,0.197,010499609002,0,Deep South
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2639442,2018,9,nc,US,370879801001,1,0,201809,37,37087,37087980100,370879801001,nc,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,370879801001,0,Deep South
2639443,2018,11,nc,US,370879801001,2,1,201811,37,37087,37087980100,370879801001,nc,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,370879801001,0,Deep South
2639485,2018,11,fl,US,120539900000,1,1,201811,12,12053,12053990000,120539900000,fl,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120539900000,0,Deep South
2639487,2018,11,nc,US,370559701020,1,0,201811,37,37055,37055970102,370559701020,nc,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,370559701020,0,Deep South
2639493,2018,11,sc,US,450899708021,0,1,201811,45,45089,45089970802,450899708021,sc,1363,1363,0,0,0,0,0,102,127,127,228,90,0,0,0,373,127,11,0,0,78,100,374,1261,127,545,127,31,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.075,0.093,0.093,0.167,0.066,0.000,0.274,0.093,0.274,0.000,0.093,0.400,0.493,0.023,0.000,NaN,NaN,NaN,NaN,NaN,NaN,450899708021,0,Deep South

In [43]:
# deep south: Alabama, Florida, Georgia, Louisiana, Mississippi, North Carolina, South Carolina, Tennessee, Texas
def add_region_tag(residing_variable_df):
    region_FIPSs = ['01', '12', '13', '22', '28', '37', '45', '47', '48']
    mask_ids = residing_variable_df['state_fips'].isin(region_FIPSs)
    residing_variable_df = residing_variable_df[mask_ids]
    
    residing_variable_df['region_tag'] = 'Deep South'
    
    return residing_variable_df

add_region_tag(residing_variable_df)

,year,month,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime,date_range_start,state_fips,county_fips,tract_fips,fips,state,totalpopulation,male,female,under5years,5to9years,10to14years,15to17years,18to24years,25to34years,35to44years,45to54years,55to64years,65to74years,75to84years,85yearsandover,whitealone,blackorafricanamericanalone,americanindianandalaskanativealone,asianalone,nativehawaiianandotherpacificislanderalone,someotherracealone,twoormoreraces,Hispanic_or_Latino,population25yearsandover,population25yearsandoverlessthanhighschool,population25yearsandoverhighschoolgraduateincludesequivalency,population25yearsandoversomecollege,population25yearsandoverbachelorsdegree,population25yearsandovermastersdegree,population25yearsandoverprofessionalschooldegree,population25yearsandoverdoctoratedegree,households,householdslessthan10000,households10000to14999,households15000to19999,households20000to24999,households25000to29999,households30000to34999,households35000to39999,households40000to44999,households45000to49999,households50000to59999,households60000to74999,households75000to99999,households100000to124999,households125000to149999,households150000to199999,households200000ormore,Female,Male,<15,15–17,18–24,25–34,35–44,45–54,55–64,>65,White,Black,Hispanic,Asian,NoSchool,HighSchool,NoCollege,Bachelor,Graduate,household_size,<20K,20K–30K,30K–50K,50K–100K,>100K,cbg_fips,nation_fips,region_tag
6360,2018,1,al,US,010499609002,34,27,201801,01,01049,01049960900,010499609002,al,718,353,365,0,0,84,35,44,17,127,79,126,107,12,0,629,88,0,0,0,0,1,0,555,117,108,127,31,0,0,0,366.000,21.000,19.000,31.000,15.000,55.000,31.000,38.000,16.000,0.000,11.000,22.000,35.000,55.000,6.000,11.000,0.000,0.508,0.492,0.117,0.049,0.061,0.024,0.177,0.110,0.175,0.166,0.876,0.123,0.000,0.000,0.163,0.150,0.313,0.043,0.000,1.962,0.194,0.191,0.232,0.186,0.197,010499609002,0,Deep South
6361,2018,2,al,US,010499609002,29,33,201802,01,01049,01049960900,010499609002,al,718,353,365,0,0,84,35,44,17,127,79,126,107,12,0,629,88,0,0,0,0,1,0,555,117,108,127,31,0,0,0,366.000,21.000,19.000,31.000,15.000,55.000,31.000,38.000,16.000,0.000,11.000,22.000,35.000,55.000,6.000,11.000,0.000,0.508,0.492,0.117,0.049,0.061,0.024,0.177,0.110,0.175,0.166,0.876,0.123,0.000,0.000,0.163,0.150,0.313,0.043,0.000,1.962,0.194,0.191,0.232,0.186,0.197,010499609002,0,Deep South
6362,2018,3,al,US,010499609002,51,40,201803,01,01049,01049960900,010499609002,al,718,353,365,0,0,84,35,44,17,127,79,126,107,12,0,629,88,0,0,0,0,1,0,555,117,108,127,31,0,0,0,366.000,21.000,19.000,31.000,15.000,55.000,31.000,38.000,16.000,0.000,11.000,22.000,35.000,55.000,6.000,11.000,0.000,0.508,0.492,0.117,0.049,0.061,0.024,0.177,0.110,0.175,0.166,0.876,0.123,0.000,0.000,0.163,0.150,0.313,0.043,0.000,1.962,0.194,0.191,0.232,0.186,0.197,010499609002,0,Deep South
6363,2018,4,al,US,010499609002,45,37,201804,01,01049,01049960900,010499609002,al,718,353,365,0,0,84,35,44,17,127,79,126,107,12,0,629,88,0,0,0,0,1,0,555,117,108,127,31,0,0,0,366.000,21.000,19.000,31.000,15.000,55.000,31.000,38.000,16.000,0.000,11.000,22.000,35.000,55.000,6.000,11.000,0.000,0.508,0.492,0.117,0.049,0.061,0.024,0.177,0.110,0.175,0.166,0.876,0.123,0.000,0.000,0.163,0.150,0.313,0.043,0.000,1.962,0.194,0.191,0.232,0.186,0.197,010499609002,0,Deep South
6364,2018,5,al,US,010499609002,42,43,201805,01,01049,01049960900,010499609002,al,718,353,365,0,0,84,35,44,17,127,79,126,107,12,0,629,88,0,0,0,0,1,0,555,117,108,127,31,0,0,0,366.000,21.000,19.000,31.000,15.000,55.000,31.000,38.000,16.000,0.000,11.000,22.000,35.000,55.000,6.000,11.000,0.000,0.508,0.492,0.117,0.049,0.061,0.024,0.177,0.110,0.175,0.166,0.876,0.123,0.000,0.000,0.163,0.150,0.313,0.043,0.000,1.962,0.194,0.191,0.232,0.186,0.197,010499609002,0,Deep South
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2639442,2018,9,nc,US,370879801001,1,0,201809,37,37087,37087980100,370879801001,nc,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,370879801001,0,Deep South
2639443,2018,11,nc,US,370879801001,2,1,201811,37,37087,37087980100,370879801001,nc,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,370879801001,0,Deep South
2639485,2018,11,fl,US,120539900000,1,1,201811,12,12053,12053990000,120539900000,fl,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120539900000,0,Deep South
2639487,2018,11,nc,US,370559701020,1,0,201811,37,37055,37055970102,370559701020,nc,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,370559701020,0,Deep South
2639493,2018,11,sc,US,450899708021,0,1,201811,45,45089,45089970802,450899708021,sc,1363,1363,0,0,0,0,0,102,127,127,228,90,0,0,0,373,127,11,0,0,78,100,374,1261,127,545,127,31,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.075,0.093,0.093,0.167,0.066,0.000,0.274,0.093,0.274,0.000,0.093,0.400,0.493,0.023,0.000,NaN,NaN,NaN,NaN,NaN,NaN,450899708021,0,Deep South

In [69]:
# for region only
for year in [2018, 2019, 2020, 2021, 2022][::-1]:
    print(year)
    if year > 2019:
        acs_year = 2019
    else:
        acs_year = year
    
    region_name = 'deep_south'

    residing_variable_df, ACS_df = load_data(year = year)
    residing_variable_df = add_region_tag(residing_variable_df)
    
    df_all = compute_sampling_rates(residing_variable_df, ACS_df=ACS_df, aggre_columns = ['region_tag'])

    df_all['fips_len'] = df_all['fips'].astype(str).str.len()
    df_all['fips_level'] = df_all['fips_len'].astype(str)
    df_all['fips_level'] = df_all['fips_level'].replace({'1': 'nation', '2':"state", '5':"county", '11': 'tract', '12':'CBG'})

    sampling_rates_csv_name = os.path.join(save_dir, fr'sampling_rates_{region_name}_{year}_monthly.csv')
    df_all.to_csv(sampling_rates_csv_name, index=False)
    
    rate_gb_df = time_aggregate(df_all.iloc[:]).reset_index()# .query(" sampling_rate < 0.5 ")).reset_index()  # remove the outliers
    # rate_gb_df.to_csv(r'P:\Shared drives\NJIT_T5\safegraph_bias\sampling_rates_yearly.csv', index=False)
    rate_gb_df['fips_len'] = rate_gb_df['fips'].astype(str).str.len()
    rate_gb_df['fips_level'] = rate_gb_df['fips_len'].astype(str)
    rate_gb_df['fips_level'] = rate_gb_df['fips_level'].replace({'1':'nation', '2':"state", '5':"county", '11': 'tract', '12':'cbg'})

    rate_gb_df.to_csv(os.path.join(save_dir, fr'sampling_rates_{region_name}_{year}_monthly_yearly.csv'), index=False)
    # 
    # bias
    
    # bias_gb_df, bias_df = compute_nation_bias()
    # bias_gb_df, bias_df = compute_state_bias()
    # bias_gb_df, bias_df = compute_county_bias()
    bias_gb_df, bias_df = compute_region_bias()

2022
US population: 327939105, male, female: 166551005 161465237

FIPS count in SafeGraph：220786, in ACS: 220333

FIPS only in SafeGraph but NOT in ACS:, 516 ['0CA:13020068', '0CA:13020069', '0CA:13020071', '0CA:13020079', '0CA:13020085', '0CA:13020090', '0CA:13020091', '0CA:13020092', '0CA:13020096', '0CA:13100277', '0CA:13130093', '0CA:13130094', '0CA:13130095', '0CA:13130096', '0CA:13130100', '0CA:13130101', '0CA:13130102', '0CA:13130103', '0CA:13130105', '0CA:13130106', '0CA:13130115', '0CA:13130119', '0CA:13130132', '0CA:24170059', '0CA:24170060', '0CA:24170065', '0CA:24290142', '0CA:24440063', '0CA:24450147', '0CA:24450148', '0CA:24450149', '0CA:24450150', '0CA:24690094', '0CA:24690108', '0CA:35010304', '0CA:35010306', '0CA:35010307', '0CA:35010308', '0CA:35010309', '0CA:35010310', '0CA:35010323', '0CA:35010407', '0CA:35010408', '0CA:35070201', '0CA:35070202', '0CA:35070203', '0CA:35070204', '0CA:35070205', '0CA:35070207', '0CA:35070215', '0CA:35070216', '0CA:35070222', '0CA:35070236', '0CA:35070237', '0CA:35070238', '0CA:35070241', '0CA:35070242', '0CA:35070243', '0CA:35070244', '0CA:35070248', '0CA:35070249', '0CA:35070250', '0CA:35070317', '0CA:35070324', '0CA:35100292', '0CA:35260093', '0CA:35260094', '0CA:35260095', '0CA:35260096', '0CA:35260133', '0CA:35260716', '0CA:35260718', '0CA:35260719', '0CA:35260754', '0CA:35380142', '0CA:35380326', '0CA:35380327', '0CA:35380353', '0CA:35570068', '0CA:35570070', '0CA:35570073', '0CA:35570074', '0CA:35570075', '0CA:35570076', '0CA:35570077', '0CA:35570078', '0CA:35570079', '0CA:35570080', '0CA:35570081', '0CA:35570082', '0CA:35570083', '0CA:35570084', '0CA:35570086', '0CA:35570087', '0CA:35570103', '0CA:35570105', '0CA:35570106', '0CA:35570107', '0CA:35570109', '0CA:35570111', '0CA:35570112', '0CA:35570113', '0CA:35570114', '0CA:35570121', '0CA:35570123', '0CA:35570124', '0CA:35570125', '0CA:35570127', '0CA:35570128', '0CA:35570129', '0CA:35570136', '0CA:35570137', '0CA:35570138', '0CA:35570279', '0CA:35570314', '0CA:35570375', '0CA:35570387', '0CA:35570388', '0CA:35570389', '0CA:35570414', '0CA:35570415', '0CA:35570416', '0CA:35570417', '0CA:35590066', '0CA:35590067', '0CA:35590068', '0CA:35590073', '0CA:35590076', '0CA:35590081', '0CA:35590087', '0CA:35590089', '0CA:35590090', '0CA:35590091', '0CA:35590092', '0CA:35590093', '0CA:35590094', '0CA:35590095', '0CA:35590124', '0CA:59090159', '600109501002', '600109503001', '600109503003', '600109505001', '600109505002', '600109506001', '600109506002', '600109506003', '600109507001', '600109507002', '600109507003', '600109509002', '600109509003', '600209518002', '600509510001', '600509510002', '600509511001', '600509511002', '600509511003', '600509512011', '600509512012', '600509512021', '600509512022', '600509512031', '600509512032', '600509513001', '600509513002', '600509515001', '600509516001', '600509516003', '600509516004', '660109501001', '660109501002', '660109501003', '660109501004', '660109501005', '660109502003', '660109502004', '660109502005', '660109503001', '660109503002', '660109503003', '660109503004', '660109503005', '660109503006', '660109503007', '660109503008', '660109503009', '660109504011', '660109504012', '660109504013', '660109504014', '660109504015', '660109504016', '660109504021', '660109504022', '660109504023', '660109505011', '660109505012', '660109505021', '660109505022', '660109505023', '660109505024', '660109505025', '660109507011', '660109507012', '660109507013', '660109507014', '660109507015', '660109507016', '660109507017', '660109507021', '660109507022', '660109507023', '660109507024', '660109507025', '660109508011', '660109508012', '660109508013', '660109508014', '660109508021', '660109508022', '660109508023', '660109508024', '660109509001', '660109509002', '660109509003', '660109509004', '660109509005', '660109509006', '660109509007', '660109510001', '660109510002', '660109510003', '660109510004', '660109510005', '660109510006', '660109510007', '660109510008', '660109511001', '660109511002', '660109511003', '660109511004', '660109511005', '660109511006', '660109516001', '660109516002', '660109517001', '660109517002', '660109518001', '660109519011', '660109519012', '660109519013', '660109519014', '660109519021', '660109519022', '660109519023', '660109519024', '660109522001', '660109522002', '660109522003', '660109522004', '660109523001', '660109523002', '660109523003', '660109524001', '660109524002', '660109527001', '660109527002', '660109527003', '660109527004', '660109527005', '660109528002', '660109529001', '660109529002', '660109529003', '660109529004', '660109529005', '660109529006', '660109530001', '660109530002', '660109530003', '660109530004', '660109530005', '660109531011', '660109531012', '660109531013', '660109531021', '660109531022', '660109531023', '660109532001', '660109532002', '660109532003', '660109533001', '660109533002', '660109533003', '660109533004', '660109534001', '660109534002', '660109535001', '660109536001', '660109536002', '660109536003', '660109536004', '660109536005', '660109539001', '660109539002', '660109539003', '660109539004', '660109540001', '660109540002', '660109543001', '660109543002', '660109544001', '660109544003', '660109544004', '660109544005', '660109544006', '660109545001', '660109545002', '660109545003', '660109545004', '660109547001', '660109547002', '660109547003', '660109548001', '660109548002', '660109548003', '660109548004', '660109551001', '660109551002', '660109551003', '660109551004', '660109552001', '660109552002', '660109552003', '660109553001', '660109553002', '660109554001', '660109556001', '660109556002', '660109557001', '660109557002', '660109557003', '660109557004', '660109557005', '660109557006', '660109558001', '660109558002', '660109558003', '660109558004', '660109558005', '660109558006', '660109558007', '660109558008', '660109558009', '660109559001', '660109559002', '660109559003', '660109560001', '660109560002', '660109561001', '660109561002', '660109561004', '660109562001', '660109562002', '660109562003', '660109562004', '660109562005', '660109563001', '660109563004', '660109563005', '660109801001', '660109804001', '660109900000', '691009501001', '691009501002', '691009501003', '691009900000', '691100001001', '691100001002', '691100002001', '691100002002', '691100003001', '691100003002', '691100004001', '691100004002', '691100005001', '691100005002', '691100006001', '691100006002', '691100006003', '691100007001', '691100007002', '691100007003', '691100008001', '691100008002', '691100009001', '691100009002', '691100009003', '691100010001', '691100010002', '691100011001', '691100012001', '691100012002', '691100013001', '691100013002', '691100013003', '691100014001', '691100014002', '691100014003', '691100015001', '691100015002', '691100015003', '691100015004', '691100015005', '691100016001', '691100016002', '691100017001', '691100017002', '691100017003', '691100017004', '691109900000', '691209501011', '691209501012', '691209501013', '691209502001', '691209502002', '780109701001', '780109701002', '780109702001', '780109702002', '780109703001', '780109703002', '780109703003', '780109704001', '780109704002', '780109704003', '780109704004', '780109705001', '780109705002', '780109705003', '780109706001', '780109706002', '780109706003', '780109706004', '780109706005', '780109707001', '780109707002', '780109707003', '780109708001', '780109708002', '780109709001', '780109710001', '780109710002', '780109711001', '780109711002', '780109711003', '780109711004', '780109712001', '780109712002', '780109712003', '780109712004', '780109713001', '780109713002', '780109713003', '780109714001', '780109715001', '780109715002', '780109715003', '780109900000', '780209501001', '780209501002', '780209501003', '780209502001', '780209502002', '780209502003', '780209502004', '780209900000', '780309601001', '780309601002', '780309601003', '780309602001', '780309602002', '780309602003', '780309603001', '780309603002', '780309603003', '780309604001', '780309604002', '780309604003', '780309604004', '780309605001', '780309605002', '780309605003', '780309605004', '780309605005', '780309606001', '780309606002', '780309606003', '780309607001', '780309607002', '780309607003', '780309608001', '780309608002', '780309609001', '780309609002', '780309610001', '780309610002', '780309610003', '780309610004', '780309610005', '780309611001', '780309611002', '780309612001', '780309612002', '780309900000']

FIPS only in ACS but NOT in SafeGraph:, 63 ['060374300033', '060374604012', '060759804011', '120659900000', '120839801001', '131919900000', '150019900000', '150019901000', '150019906000', '150019909000', '150019910000', '150019911000', '150019914000', '150039812001', '150070412002', '150079902000', '150079903000', '160439701002', '220870301053', '260099900000', '260539900000', '260619901000', '260959900000', '261579900000', '300290017002', '325109900000', '340297310020', '340297360010', '350010047421', '350439403001', '360050319000', '360599902000', '360639401001', '360850081000', '360850223003', '361190056001', '370159604000', '370559701020', '371379901000', '410459400001', '440050401031', '480719900000', '482619900000', '484899900000', '511039901000', '530619901000', '550519900000', '720039900000', '720059900000', '720119900000', '720179900000', '720339800081', '720519900210', '720539901030', '720599900010', '720719900000', '720919900250', '720959900000', '721039900130', '721099900000', '721119900000', '721139930000', '721159900000']

Removed devices only in 516 SafeGraph FIPS: 73689 devices.

Removed these 63 block groups, 3 people.

Before merge ACS data row count: 2644588

After merge ACS data row count:  2640121

ACS columns:
Index(['state_fips', 'county_fips', 'tract_fips', 'fips', 'state',
       'totalpopulation', 'male', 'female', 'under5years', '5to9years',
       '10to14years', '15to17years', '18to24years', '25to34years',
       '35to44years', '45to54years', '55to64years', '65to74years',
       '75to84years', '85yearsandover', 'whitealone',
       'blackorafricanamericanalone', 'americanindianandalaskanativealone',
       'asianalone', 'nativehawaiianandotherpacificislanderalone',
       'someotherracealone', 'twoormoreraces', 'Hispanic_or_Latino',
       'population25yearsandover',
       'population25yearsandoverlessthanhighschool',
       'population25yearsandoverhighschoolgraduateincludesequivalency',
       'population25yearsandoversomecollege',
       'population25yearsandoverbachelorsdegree',
       'population25yearsandovermastersdegree',
       'population25yearsandoverprofessionalschooldegree',
       'population25yearsandoverdoctoratedegree', 'households',
       'householdslessthan10000', 'households10000to14999',
       'households15000to19999', 'households20000to24999',
       'households25000to29999', 'households30000to34999',
       'households35000to39999', 'households40000to44999',
       'households45000to49999', 'households50000to59999',
       'households60000to74999', 'households75000to99999',
       'households100000to124999', 'households125000to149999',
       'households150000to199999', 'households200000ormore', 'Female', 'Male',
       '<15', '15–17', '18–24', '25–34', '35–44', '45–54', '55–64', '>65',
       'White', 'Black', 'Hispanic', 'Asian', 'NoSchool', 'HighSchool',
       'NoCollege', 'Bachelor', 'Graduate', 'household_size', '<20K',
       '20K–30K', '30K–50K', '50K–100K', '>100K', 'cbg_fips', 'nation_fips'],
      dtype='object')

C:\Users\N\AppData\Local\Temp\ipykernel_29588\821876159.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_variable_df['region_tag'] = 'Deep South'
C:\Users\N\AppData\Local\Temp\ipykernel_29588\4010543827.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df.loc[:, 'state_fips'] = residing_df['state_fips'].astype(str).str.zfill(2)
C:\Users\N\AppData\Local\Temp\ipykernel_29588\4010543827.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df['date_range_start'] = residing_df['date_range_start'].astype(str).str[:10]   # have an issue of different starting hours
100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.71it/s]

2021
US population: 327939105, male, female: 166551005 161465237

FIPS count in SafeGraph：220534, in ACS: 220333

FIPS only in SafeGraph but NOT in ACS:, 345 ['0CA:24450148', '600109506002', '600109507002', '600109507003', '600109509002', '600109509003', '600109509004', '600509510002', '600509511001', '600509511002', '600509512011', '600509512012', '600509512021', '600509512032', '600509512033', '600509513002', '600509515001', '600509516004', '660109501001', '660109501002', '660109501003', '660109501004', '660109501005', '660109502003', '660109502004', '660109502005', '660109503002', '660109503003', '660109503004', '660109503009', '660109504011', '660109504012', '660109504013', '660109504014', '660109504015', '660109504016', '660109504021', '660109504022', '660109504023', '660109505011', '660109505012', '660109505021', '660109505022', '660109505023', '660109505024', '660109505025', '660109507011', '660109507012', '660109507013', '660109507014', '660109507015', '660109507016', '660109507017', '660109507021', '660109507022', '660109507023', '660109507024', '660109507025', '660109508011', '660109508012', '660109508013', '660109508014', '660109508021', '660109508022', '660109508023', '660109508024', '660109509001', '660109509002', '660109509003', '660109509004', '660109509005', '660109509006', '660109509007', '660109510001', '660109510002', '660109510003', '660109510004', '660109510005', '660109510006', '660109510007', '660109510008', '660109511001', '660109511002', '660109511003', '660109511004', '660109511005', '660109511006', '660109516001', '660109516002', '660109517001', '660109517002', '660109518001', '660109519011', '660109519012', '660109519013', '660109519014', '660109519021', '660109519022', '660109519023', '660109519024', '660109522001', '660109522002', '660109522003', '660109522004', '660109523001', '660109523002', '660109523003', '660109524001', '660109524002', '660109527001', '660109527002', '660109527003', '660109527004', '660109527005', '660109529001', '660109529002', '660109529003', '660109529004', '660109529005', '660109529006', '660109530001', '660109530002', '660109530003', '660109530004', '660109530005', '660109531011', '660109531012', '660109531013', '660109531021', '660109531022', '660109531023', '660109532001', '660109532002', '660109532003', '660109533001', '660109533002', '660109533003', '660109533004', '660109534001', '660109534002', '660109535001', '660109536001', '660109536002', '660109536003', '660109536004', '660109536005', '660109539001', '660109539002', '660109539003', '660109539004', '660109540001', '660109540002', '660109543001', '660109543002', '660109544001', '660109544002', '660109544003', '660109544004', '660109544007', '660109545001', '660109545002', '660109545003', '660109545004', '660109547001', '660109547002', '660109547003', '660109548001', '660109548002', '660109548003', '660109548004', '660109551001', '660109551002', '660109551003', '660109551004', '660109552001', '660109552002', '660109552003', '660109553001', '660109553002', '660109554001', '660109556001', '660109556002', '660109557001', '660109557002', '660109557003', '660109557004', '660109557005', '660109557006', '660109558001', '660109558002', '660109558003', '660109558004', '660109558005', '660109558006', '660109558007', '660109558008', '660109558009', '660109559001', '660109559002', '660109559003', '660109560001', '660109560002', '660109561001', '660109561002', '660109561004', '660109562001', '660109562002', '660109562003', '660109562004', '660109562005', '660109563001', '660109563004', '660109563005', '660109801001', '660109804001', '660109900000', '690859501001', '691009501001', '691009501002', '691009501003', '691100001001', '691100002001', '691100002002', '691100003001', '691100004001', '691100004002', '691100005001', '691100005002', '691100006001', '691100006003', '691100007001', '691100007002', '691100008002', '691100009001', '691100009002', '691100009003', '691100010001', '691100010002', '691100011001', '691100012001', '691100012002', '691100013001', '691100013003', '691100014002', '691100015002', '691100015003', '691100016001', '691100016002', '691100017001', '691100017002', '691100017003', '691100017004', '691209501012', '691209501013', '691209502001', '691209502002', '780109701001', '780109701002', '780109702001', '780109702002', '780109703001', '780109703002', '780109703003', '780109704001', '780109704002', '780109704003', '780109704004', '780109705001', '780109705002', '780109705003', '780109706001', '780109706002', '780109706003', '780109706004', '780109706005', '780109707001', '780109707002', '780109707003', '780109708001', '780109708002', '780109709001', '780109710001', '780109710002', '780109711001', '780109711002', '780109711003', '780109711004', '780109712001', '780109712002', '780109712003', '780109712004', '780109713001', '780109713002', '780109713003', '780109714001', '780109715001', '780109715002', '780109715003', '780109900000', '780209501001', '780209501002', '780209501003', '780209502001', '780209502002', '780209502003', '780209502004', '780209900000', '780309601001', '780309601002', '780309601003', '780309602001', '780309602002', '780309602003', '780309603001', '780309603002', '780309603003', '780309604001', '780309604002', '780309604003', '780309604004', '780309605001', '780309605002', '780309605003', '780309605004', '780309605005', '780309606001', '780309606002', '780309606003', '780309607001', '780309607002', '780309607003', '780309608001', '780309608002', '780309609001', '780309609002', '780309610001', '780309610002', '780309610003', '780309610004', '780309610005', '780309611001', '780309611002', '780309612001', '780309612002', '780309900000']

FIPS only in ACS but NOT in SafeGraph:, 144 ['060159900000', '060374300033', '060374303012', '060374604012', '061110036121', '080149801001', '080149803001', '120179900000', '120299900000', '120519900000', '120659900000', '120839801001', '120859901000', '121059800001', '121239900000', '130399900000', '131799900000', '131919900000', '150019900000', '150019901000', '150019906000', '150019909000', '150019910000', '150019911000', '150019913000', '150019914000', '150019917000', '150039812001', '150059900000', '150070412002', '150079902000', '150079903000', '150099800001', '150099900000', '150099912000', '160439701002', '210670039161', '220870301053', '220879900000', '221019900000', '221139900000', '230099900000', '230159756003', '230299900000', '260099900000', '260119900000', '260139901000', '260199900000', '260339801001', '260619901000', '260959800001', '260959900000', '261399900000', '261479900000', '270759901000', '280459900000', '300290017002', '325109900000', '360050115020', '360050319000', '360050516005', '360191019006', '360470164000', '360470168000', '360470174000', '360470280000', '360470282000', '360470616000', '360470702031', '360599901000', '360599902000', '360599903020', '360610007002', '360610136000', '360610175000', '360610195000', '360610223020', '360610225000', '360639401001', '360810992000', '360811008010', '360811010010', '360850081000', '360850128050', '360850223003', '360850323000', '361190056001', '370159604000', '370299501020', '370419301010', '370559701020', '370559704000', '370559706020', '371379901000', '371399607020', '371439201000', '390959900000', '410119901010', '410199900000', '410399900000', '410459400001', '480079900000', '480579900000', '480719900000', '482459900000', '482619900000', '484899900000', '510019902000', '511039901000', '511199901000', '530319900000', '530619901000', '550039900000', '550079900000', '550319900000', '550519900000', '720054009002', '720119900000', '720159915000', '720179900000', '720339800021', '720339800081', '720371601002', '720539901030', '720579926000', '720599900010', '720659900160', '720699918000', '720759900010', '720799911000', '720879900000', '720899900010', '720919900250', '721039900130', '721099900000', '721119900000', '721139930000', '721159900000', '721179904000', '721239928000', '721279803001', '721339900000', '721379900000', '721519900000']

Removed devices only in 345 SafeGraph FIPS: 14346 devices.

Removed these 144 block groups, 128 people.

Before merge ACS data row count: 2640227

After merge ACS data row count:  2637932

ACS columns:
Index(['state_fips', 'county_fips', 'tract_fips', 'fips', 'state',
       'totalpopulation', 'male', 'female', 'under5years', '5to9years',
       '10to14years', '15to17years', '18to24years', '25to34years',
       '35to44years', '45to54years', '55to64years', '65to74years',
       '75to84years', '85yearsandover', 'whitealone',
       'blackorafricanamericanalone', 'americanindianandalaskanativealone',
       'asianalone', 'nativehawaiianandotherpacificislanderalone',
       'someotherracealone', 'twoormoreraces', 'Hispanic_or_Latino',
       'population25yearsandover',
       'population25yearsandoverlessthanhighschool',
       'population25yearsandoverhighschoolgraduateincludesequivalency',
       'population25yearsandoversomecollege',
       'population25yearsandoverbachelorsdegree',
       'population25yearsandovermastersdegree',
       'population25yearsandoverprofessionalschooldegree',
       'population25yearsandoverdoctoratedegree', 'households',
       'householdslessthan10000', 'households10000to14999',
       'households15000to19999', 'households20000to24999',
       'households25000to29999', 'households30000to34999',
       'households35000to39999', 'households40000to44999',
       'households45000to49999', 'households50000to59999',
       'households60000to74999', 'households75000to99999',
       'households100000to124999', 'households125000to149999',
       'households150000to199999', 'households200000ormore', 'Female', 'Male',
       '<15', '15–17', '18–24', '25–34', '35–44', '45–54', '55–64', '>65',
       'White', 'Black', 'Hispanic', 'Asian', 'NoSchool', 'HighSchool',
       'NoCollege', 'Bachelor', 'Graduate', 'household_size', '<20K',
       '20K–30K', '30K–50K', '50K–100K', '>100K', 'cbg_fips', 'nation_fips'],
      dtype='object')

C:\Users\N\AppData\Local\Temp\ipykernel_29588\821876159.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_variable_df['region_tag'] = 'Deep South'
C:\Users\N\AppData\Local\Temp\ipykernel_29588\4010543827.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df.loc[:, 'state_fips'] = residing_df['state_fips'].astype(str).str.zfill(2)
C:\Users\N\AppData\Local\Temp\ipykernel_29588\4010543827.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df['date_range_start'] = residing_df['date_range_start'].astype(str).str[:10]   # have an issue of different starting hours
100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [00:01<00:00,  6.01it/s]

2020
US population: 327939105, male, female: 166551005 161465237

FIPS count in SafeGraph：220549, in ACS: 220333

FIPS only in SafeGraph but NOT in ACS:, 380 ['600109501001', '600109503001', '600109503002', '600109503003', '600109505001', '600109505002', '600109505003', '600109506001', '600109506002', '600109506003', '600109507001', '600109507002', '600109507003', '600109509001', '600109509002', '600109509003', '600109509004', '600509510001', '600509510002', '600509511001', '600509511002', '600509511003', '600509512011', '600509512012', '600509512021', '600509512022', '600509512031', '600509512032', '600509512033', '600509513001', '600509513002', '600509515001', '600509516002', '600509516003', '600509516004', '660109501001', '660109501002', '660109501003', '660109501004', '660109501005', '660109502003', '660109502004', '660109502005', '660109503002', '660109503003', '660109503004', '660109503006', '660109503007', '660109503008', '660109503009', '660109504011', '660109504012', '660109504013', '660109504014', '660109504015', '660109504016', '660109504021', '660109504022', '660109504023', '660109505011', '660109505012', '660109505021', '660109505022', '660109505023', '660109505024', '660109505025', '660109507011', '660109507012', '660109507013', '660109507014', '660109507015', '660109507016', '660109507017', '660109507021', '660109507022', '660109507023', '660109507024', '660109507025', '660109508011', '660109508012', '660109508013', '660109508014', '660109508021', '660109508022', '660109508023', '660109508024', '660109509001', '660109509002', '660109509003', '660109509004', '660109509005', '660109509006', '660109509007', '660109510001', '660109510002', '660109510003', '660109510004', '660109510005', '660109510006', '660109510007', '660109510008', '660109511001', '660109511002', '660109511003', '660109511004', '660109511005', '660109511006', '660109516001', '660109516002', '660109517001', '660109517002', '660109518001', '660109519011', '660109519012', '660109519013', '660109519014', '660109519021', '660109519022', '660109519023', '660109519024', '660109522001', '660109522002', '660109522003', '660109522004', '660109523001', '660109523002', '660109523003', '660109524001', '660109524002', '660109527001', '660109527002', '660109527003', '660109527004', '660109527005', '660109529001', '660109529002', '660109529003', '660109529004', '660109529005', '660109529006', '660109530001', '660109530002', '660109530003', '660109530004', '660109530005', '660109531011', '660109531012', '660109531013', '660109531021', '660109531022', '660109531023', '660109532001', '660109532002', '660109532003', '660109533001', '660109533002', '660109533003', '660109533004', '660109534001', '660109534002', '660109535001', '660109536001', '660109536002', '660109536003', '660109536004', '660109536005', '660109539001', '660109539002', '660109539003', '660109539004', '660109540001', '660109540002', '660109543001', '660109543002', '660109544001', '660109544002', '660109544003', '660109544004', '660109544005', '660109544006', '660109544007', '660109545001', '660109545002', '660109545003', '660109545004', '660109547001', '660109547002', '660109547003', '660109548001', '660109548002', '660109548003', '660109548004', '660109551001', '660109551002', '660109551003', '660109551004', '660109552001', '660109552002', '660109552003', '660109553001', '660109553002', '660109554001', '660109556001', '660109556002', '660109557001', '660109557002', '660109557003', '660109557004', '660109557005', '660109557006', '660109558001', '660109558002', '660109558003', '660109558004', '660109558005', '660109558006', '660109558007', '660109558008', '660109558009', '660109559001', '660109559002', '660109559003', '660109560001', '660109560002', '660109561001', '660109561002', '660109561004', '660109562001', '660109562002', '660109562003', '660109562004', '660109562005', '660109563001', '660109563003', '660109563004', '660109563005', '660109801001', '660109804001', '660109900000', '691009501001', '691009501002', '691009501003', '691100001001', '691100001002', '691100002001', '691100002002', '691100003001', '691100003002', '691100004001', '691100004002', '691100005001', '691100005002', '691100006001', '691100006002', '691100006003', '691100007001', '691100007002', '691100007003', '691100008001', '691100008002', '691100009001', '691100009002', '691100009003', '691100010001', '691100010002', '691100011001', '691100012001', '691100012002', '691100013001', '691100013002', '691100013003', '691100014001', '691100014002', '691100014003', '691100015001', '691100015002', '691100015003', '691100015004', '691100015005', '691100016001', '691100016002', '691100017001', '691100017002', '691100017003', '691100017004', '691109900000', '691209501011', '691209501012', '691209501013', '691209502001', '691209502002', '780109701001', '780109701002', '780109702001', '780109702002', '780109703001', '780109703002', '780109703003', '780109704001', '780109704002', '780109704003', '780109704004', '780109705001', '780109705002', '780109705003', '780109706001', '780109706002', '780109706003', '780109706004', '780109706005', '780109707001', '780109707002', '780109707003', '780109708001', '780109708002', '780109709001', '780109710001', '780109710002', '780109711001', '780109711002', '780109711003', '780109711004', '780109712001', '780109712002', '780109712003', '780109712004', '780109713001', '780109713002', '780109713003', '780109714001', '780109715001', '780109715002', '780109715003', '780109900000', '780209501001', '780209501002', '780209501003', '780209502001', '780209502002', '780209502003', '780209502004', '780209900000', '780309601001', '780309601002', '780309601003', '780309602001', '780309602002', '780309602003', '780309603001', '780309603002', '780309603003', '780309604001', '780309604002', '780309604003', '780309604004', '780309605001', '780309605002', '780309605003', '780309605004', '780309605005', '780309606001', '780309606002', '780309606003', '780309607001', '780309607002', '780309607003', '780309608001', '780309608002', '780309609001', '780309609002', '780309610001', '780309610002', '780309610003', '780309610004', '780309610005', '780309611001', '780309611002', '780309612001', '780309612002', '780309900000']

FIPS only in ACS but NOT in SafeGraph:, 164 ['060159900000', '060374300033', '060374303012', '060374604012', '060411242001', '060530141042', '080149801001', '120179900000', '120519900000', '120579901000', '120659900000', '120839801001', '120859901000', '121239900000', '121299900000', '130399900000', '131799900000', '131919900000', '150019900000', '150019901000', '150019904000', '150019905000', '150019906000', '150019910000', '150019911000', '150019912000', '150019913000', '150019914000', '150019917000', '150039812001', '150059900000', '150070412002', '150079902000', '150079903000', '150099800001', '150099912000', '160439701002', '220459900000', '220870301053', '230299900000', '260099900000', '260139901000', '260199900000', '260319900000', '260339801001', '260339900000', '260339901000', '260419901000', '260539900000', '260619900000', '260619901000', '260650044021', '260959800001', '260959900000', '261039900000', '261219900000', '261279900000', '261479900000', '261579900000', '261599900000', '261639902000', '270759901000', '280459900000', '320319901000', '325109900000', '340297225000', '340297310020', '340297360010', '340297380010', '350010047421', '350439403001', '360050028000', '360050115020', '360050516005', '360119902000', '360191019006', '360470052020', '360470164000', '360470280000', '360470282000', '360470292000', '360470330000', '360470616000', '360471028000', '360599903020', '360610175000', '360610223010', '360610223020', '360610225000', '360639401001', '360810992000', '360811008010', '360811008020', '360811010020', '360850081000', '360850223000', '360850223003', '360850228000', '360850244010', '360850323000', '361190056001', '370159604000', '370299501020', '370319902000', '370419301010', '370531104020', '370559701020', '370559705010', '370559706020', '370899801001', '370959902000', '371379901000', '371399607020', '371439201000', '371439202020', '390959900000', '410199900000', '410459400001', '420792156002', '480579900000', '480719900000', '482459900000', '484899900000', '510019902000', '511039901000', '511199901000', '530319900000', '530559901000', '530619901000', '550039900000', '550079900000', '550319900000', '550519900000', '720059900000', '720119900000', '720159915000', '720179900000', '720239800001', '720279900000', '720339800081', '720379900000', '720499905010', '720539901030', '720559900000', '720599900010', '720659900160', '720699918000', '720759900010', '720799911000', '720879900000', '720899900010', '720919900250', '720979900000', '721039900130', '721099900000', '721139930000', '721159900000', '721179904000', '721199927000', '721339900000', '721379900000', '721439900000', '721459900000', '721479900000']

Removed devices only in 380 SafeGraph FIPS: 57720 devices.

Removed these 164 block groups, 2001 people.

Before merge ACS data row count: 2643048

After merge ACS data row count:  2639245

ACS columns:
Index(['state_fips', 'county_fips', 'tract_fips', 'fips', 'state',
       'totalpopulation', 'male', 'female', 'under5years', '5to9years',
       '10to14years', '15to17years', '18to24years', '25to34years',
       '35to44years', '45to54years', '55to64years', '65to74years',
       '75to84years', '85yearsandover', 'whitealone',
       'blackorafricanamericanalone', 'americanindianandalaskanativealone',
       'asianalone', 'nativehawaiianandotherpacificislanderalone',
       'someotherracealone', 'twoormoreraces', 'Hispanic_or_Latino',
       'population25yearsandover',
       'population25yearsandoverlessthanhighschool',
       'population25yearsandoverhighschoolgraduateincludesequivalency',
       'population25yearsandoversomecollege',
       'population25yearsandoverbachelorsdegree',
       'population25yearsandovermastersdegree',
       'population25yearsandoverprofessionalschooldegree',
       'population25yearsandoverdoctoratedegree', 'households',
       'householdslessthan10000', 'households10000to14999',
       'households15000to19999', 'households20000to24999',
       'households25000to29999', 'households30000to34999',
       'households35000to39999', 'households40000to44999',
       'households45000to49999', 'households50000to59999',
       'households60000to74999', 'households75000to99999',
       'households100000to124999', 'households125000to149999',
       'households150000to199999', 'households200000ormore', 'Female', 'Male',
       '<15', '15–17', '18–24', '25–34', '35–44', '45–54', '55–64', '>65',
       'White', 'Black', 'Hispanic', 'Asian', 'NoSchool', 'HighSchool',
       'NoCollege', 'Bachelor', 'Graduate', 'household_size', '<20K',
       '20K–30K', '30K–50K', '50K–100K', '>100K', 'cbg_fips', 'nation_fips'],
      dtype='object')

C:\Users\N\AppData\Local\Temp\ipykernel_29588\821876159.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_variable_df['region_tag'] = 'Deep South'
C:\Users\N\AppData\Local\Temp\ipykernel_29588\4010543827.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df.loc[:, 'state_fips'] = residing_df['state_fips'].astype(str).str.zfill(2)
C:\Users\N\AppData\Local\Temp\ipykernel_29588\4010543827.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df['date_range_start'] = residing_df['date_range_start'].astype(str).str[:10]   # have an issue of different starting hours
100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.79it/s]

2019
US population: 327939105, male, female: 166551005 161465237

FIPS count in SafeGraph：220539, in ACS: 220333

FIPS only in SafeGraph but NOT in ACS:, 379 ['0CA:24680061', '0CA:59490105', '600109501001', '600109501002', '600109502001', '600109502002', '600109503001', '600109503002', '600109503003', '600109505001', '600109505002', '600109505003', '600109506001', '600109506002', '600109506003', '600109507001', '600109507002', '600109507003', '600109509001', '600109509002', '600109509003', '600109509004', '600209518001', '600209518002', '600509510001', '600509510002', '600509511001', '600509511002', '600509511003', '600509512011', '600509512012', '600509512021', '600509512022', '600509512031', '600509512032', '600509512033', '600509513001', '600509513002', '600509515001', '600509516001', '600509516003', '600509516004', '660109501001', '660109501002', '660109501003', '660109501004', '660109501005', '660109502003', '660109502004', '660109502005', '660109503002', '660109503003', '660109503004', '660109503009', '660109504011', '660109504012', '660109504013', '660109504014', '660109504015', '660109504016', '660109504021', '660109504022', '660109504023', '660109505011', '660109505012', '660109505021', '660109505022', '660109505023', '660109505024', '660109505025', '660109507011', '660109507012', '660109507013', '660109507014', '660109507015', '660109507016', '660109507017', '660109507021', '660109507022', '660109507023', '660109507024', '660109507025', '660109508011', '660109508012', '660109508013', '660109508014', '660109508021', '660109508022', '660109508023', '660109508024', '660109509001', '660109509002', '660109509003', '660109509004', '660109509005', '660109509006', '660109509007', '660109510001', '660109510002', '660109510003', '660109510004', '660109510005', '660109510006', '660109510007', '660109510008', '660109511001', '660109511002', '660109511003', '660109511004', '660109511005', '660109511006', '660109516001', '660109516002', '660109517001', '660109517002', '660109518001', '660109519011', '660109519012', '660109519013', '660109519014', '660109519021', '660109519022', '660109519023', '660109519024', '660109522001', '660109522002', '660109522003', '660109522004', '660109523001', '660109523002', '660109523003', '660109524001', '660109524002', '660109527001', '660109527002', '660109527003', '660109527004', '660109527005', '660109529001', '660109529002', '660109529003', '660109529004', '660109529005', '660109529006', '660109530001', '660109530002', '660109530003', '660109530004', '660109530005', '660109531011', '660109531012', '660109531013', '660109531021', '660109531022', '660109531023', '660109532001', '660109532002', '660109532003', '660109533001', '660109533002', '660109533003', '660109533004', '660109534001', '660109534002', '660109535001', '660109536001', '660109536002', '660109536003', '660109536004', '660109536005', '660109539001', '660109539002', '660109539003', '660109539004', '660109540001', '660109540002', '660109543001', '660109543002', '660109544001', '660109544003', '660109544004', '660109544006', '660109544007', '660109545001', '660109545002', '660109545003', '660109545004', '660109547001', '660109547002', '660109547003', '660109548001', '660109548002', '660109548003', '660109548004', '660109551001', '660109551002', '660109551003', '660109551004', '660109552001', '660109552002', '660109552003', '660109553001', '660109553002', '660109554001', '660109556001', '660109556002', '660109557001', '660109557003', '660109557004', '660109557005', '660109557006', '660109558001', '660109558002', '660109558003', '660109558004', '660109558005', '660109558006', '660109558007', '660109558008', '660109558009', '660109559001', '660109559002', '660109559003', '660109560001', '660109560002', '660109561001', '660109561002', '660109561004', '660109562001', '660109562002', '660109562003', '660109562004', '660109562005', '660109563004', '660109563005', '660109801001', '660109804001', '660109900000', '691009501001', '691009501002', '691009501003', '691009900000', '691100001001', '691100001002', '691100002001', '691100002002', '691100003001', '691100003002', '691100004001', '691100004002', '691100005001', '691100005002', '691100006001', '691100006002', '691100006003', '691100007001', '691100007002', '691100007003', '691100008001', '691100008002', '691100009001', '691100009002', '691100009003', '691100010001', '691100010002', '691100011001', '691100012001', '691100012002', '691100013001', '691100013002', '691100013003', '691100014001', '691100014002', '691100014003', '691100015001', '691100015002', '691100015003', '691100015004', '691100015005', '691100016001', '691100016002', '691100017002', '691100017003', '691100017004', '691109900000', '691209501011', '691209501012', '691209501013', '691209502001', '691209502002', '780109701001', '780109701002', '780109702001', '780109702002', '780109703001', '780109703002', '780109703003', '780109704001', '780109704002', '780109704003', '780109704004', '780109705001', '780109705002', '780109705003', '780109706001', '780109706002', '780109706003', '780109706004', '780109706005', '780109707001', '780109707002', '780109707003', '780109708001', '780109708002', '780109709001', '780109710001', '780109710002', '780109711001', '780109711002', '780109711003', '780109711004', '780109712001', '780109712002', '780109712003', '780109712004', '780109713001', '780109713002', '780109713003', '780109714001', '780109715001', '780109715002', '780109715003', '780109900000', '780209501001', '780209501002', '780209501003', '780209502001', '780209502002', '780209502003', '780209502004', '780209900000', '780309601001', '780309601002', '780309601003', '780309602001', '780309602002', '780309602003', '780309603001', '780309603002', '780309603003', '780309604001', '780309604002', '780309604003', '780309604004', '780309605001', '780309605002', '780309605003', '780309605004', '780309605005', '780309606001', '780309606002', '780309606003', '780309607001', '780309607002', '780309607003', '780309608001', '780309608002', '780309609001', '780309609002', '780309610001', '780309610002', '780309610003', '780309610004', '780309610005', '780309611001', '780309611002', '780309612001', '780309612002', '780309900000']

FIPS only in ACS but NOT in SafeGraph:, 173 ['060159900000', '060379800201', '060759804011', '061110036121', '080149801001', '080149802001', '080149803001', '090079901000', '120179900000', '120299900000', '120379900000', '120519900000', '120579901000', '120659900000', '120759900000', '120839800001', '120839801001', '120859901000', '120879801001', '121239900000', '121299900000', '130399900000', '131799900000', '131919900000', '150019900000', '150019901000', '150019903000', '150019904000', '150019905000', '150019906000', '150019907000', '150019909000', '150019910000', '150019911000', '150019912000', '150019914000', '150019916000', '150019917000', '150039812001', '150059900000', '150070412002', '150079902000', '150079903000', '150099912000', '160439701002', '180890110001', '210670039161', '230059900000', '230299900000', '260039900000', '260119900000', '260139901000', '260199900000', '260299900000', '260339900000', '260339901000', '260419901000', '260539900000', '260619900000', '260619901000', '260899900000', '260959900000', '261039900000', '261279900000', '261479900000', '261579900000', '280459900000', '325109900000', '340297225000', '340297310020', '340297340020', '340297360010', '350010047421', '350439403001', '360039402001', '360050002000', '360050019000', '360050024000', '360050110000', '360050115020', '360050319000', '360050516005', '360119902000', '360470050000', '360470054000', '360470174000', '360470286000', '360470616000', '360599902000', '360599903020', '360610009002', '360610159000', '360610191000', '360610199000', '360610223020', '360639401001', '360810916020', '360810922000', '360810928000', '360810934010', '360810942010', '360810964000', '360810981000', '360810987000', '360810992000', '360811008010', '360850070000', '360850074000', '360850081000', '360850112020', '360850128050', '360850128060', '360850223003', '360850228000', '361190056001', '370159604000', '370299501020', '370319902000', '370419301010', '370531104020', '370559703000', '370559705010', '370559706020', '370879801001', '370959901000', '371379901000', '371399607020', '371439202020', '410199900000', '410459400001', '450539901000', '450899708021', '480579900000', '480719900000', '482459900000', '482619900000', '482739900000', '484899900000', '510019902000', '511039901000', '511199901000', '517359901000', '530050109011', '530319900000', '530619901000', '550039900000', '550079900000', '550299900000', '550319900000', '550519900000', '550839900000', '720119900000', '720159915000', '720179900000', '720279900000', '720519900210', '720539901030', '720559900000', '720599900010', '720759900010', '720799911000', '720899900010', '720919900250', '720959900000', '721039900130', '721099900000', '721139930000', '721159900000', '721199927000', '721279900000', '721459900000', '721479900000', '721519900000']

Removed devices only in 379 SafeGraph FIPS: 30328 devices.

Removed these 173 block groups, 1275 people.

Before merge ACS data row count: 2643116

After merge ACS data row count:  2639192

ACS columns:
Index(['state_fips', 'county_fips', 'tract_fips', 'fips', 'state',
       'totalpopulation', 'male', 'female', 'under5years', '5to9years',
       '10to14years', '15to17years', '18to24years', '25to34years',
       '35to44years', '45to54years', '55to64years', '65to74years',
       '75to84years', '85yearsandover', 'whitealone',
       'blackorafricanamericanalone', 'americanindianandalaskanativealone',
       'asianalone', 'nativehawaiianandotherpacificislanderalone',
       'someotherracealone', 'twoormoreraces', 'Hispanic_or_Latino',
       'population25yearsandover',
       'population25yearsandoverlessthanhighschool',
       'population25yearsandoverhighschoolgraduateincludesequivalency',
       'population25yearsandoversomecollege',
       'population25yearsandoverbachelorsdegree',
       'population25yearsandovermastersdegree',
       'population25yearsandoverprofessionalschooldegree',
       'population25yearsandoverdoctoratedegree', 'households',
       'householdslessthan10000', 'households10000to14999',
       'households15000to19999', 'households20000to24999',
       'households25000to29999', 'households30000to34999',
       'households35000to39999', 'households40000to44999',
       'households45000to49999', 'households50000to59999',
       'households60000to74999', 'households75000to99999',
       'households100000to124999', 'households125000to149999',
       'households150000to199999', 'households200000ormore', 'Female', 'Male',
       '<15', '15–17', '18–24', '25–34', '35–44', '45–54', '55–64', '>65',
       'White', 'Black', 'Hispanic', 'Asian', 'NoSchool', 'HighSchool',
       'NoCollege', 'Bachelor', 'Graduate', 'household_size', '<20K',
       '20K–30K', '30K–50K', '50K–100K', '>100K', 'cbg_fips', 'nation_fips'],
      dtype='object')

C:\Users\N\AppData\Local\Temp\ipykernel_29588\821876159.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_variable_df['region_tag'] = 'Deep South'
C:\Users\N\AppData\Local\Temp\ipykernel_29588\4010543827.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df.loc[:, 'state_fips'] = residing_df['state_fips'].astype(str).str.zfill(2)
C:\Users\N\AppData\Local\Temp\ipykernel_29588\4010543827.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df['date_range_start'] = residing_df['date_range_start'].astype(str).str[:10]   # have an issue of different starting hours
100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.89it/s]

2018
US population: 326228729, male, female: 165692916 160597055

FIPS count in SafeGraph：220601, in ACS: 220333

FIPS only in SafeGraph but NOT in ACS:, 390 ['0CA:24450148', '0CA:24680061', '600109501001', '600109501002', '600109502001', '600109502002', '600109503001', '600109503002', '600109503003', '600109505001', '600109505002', '600109505003', '600109506001', '600109506002', '600109506003', '600109507001', '600109507002', '600109507003', '600109509001', '600109509002', '600109509003', '600109509004', '600209518001', '600509510001', '600509510002', '600509511001', '600509511002', '600509511003', '600509512011', '600509512012', '600509512021', '600509512022', '600509512031', '600509512032', '600509512033', '600509513001', '600509513002', '600509515001', '600509516001', '600509516002', '600509516003', '600509516004', '660109501001', '660109501002', '660109501003', '660109501004', '660109501005', '660109502003', '660109502004', '660109502005', '660109503001', '660109503002', '660109503003', '660109503004', '660109503006', '660109503007', '660109503009', '660109504011', '660109504012', '660109504013', '660109504014', '660109504015', '660109504016', '660109504021', '660109504022', '660109504023', '660109505011', '660109505012', '660109505021', '660109505022', '660109505023', '660109505024', '660109505025', '660109507011', '660109507012', '660109507013', '660109507014', '660109507015', '660109507016', '660109507017', '660109507021', '660109507022', '660109507023', '660109507024', '660109507025', '660109508011', '660109508012', '660109508013', '660109508014', '660109508021', '660109508022', '660109508023', '660109508024', '660109509001', '660109509002', '660109509003', '660109509004', '660109509005', '660109509006', '660109509007', '660109510001', '660109510002', '660109510003', '660109510004', '660109510005', '660109510006', '660109510007', '660109510008', '660109511001', '660109511002', '660109511003', '660109511004', '660109511005', '660109511006', '660109516001', '660109516002', '660109517001', '660109517002', '660109518001', '660109519011', '660109519012', '660109519013', '660109519014', '660109519021', '660109519022', '660109519023', '660109519024', '660109522001', '660109522002', '660109522003', '660109522004', '660109523001', '660109523002', '660109523003', '660109524001', '660109524002', '660109527001', '660109527002', '660109527003', '660109527004', '660109527005', '660109528001', '660109528002', '660109529001', '660109529002', '660109529003', '660109529004', '660109529005', '660109529006', '660109530001', '660109530002', '660109530003', '660109530004', '660109530005', '660109531011', '660109531012', '660109531013', '660109531021', '660109531022', '660109531023', '660109532001', '660109532002', '660109532003', '660109533001', '660109533002', '660109533003', '660109533004', '660109534001', '660109534002', '660109535001', '660109536001', '660109536002', '660109536003', '660109536004', '660109536005', '660109539001', '660109539002', '660109539003', '660109539004', '660109540001', '660109540002', '660109543001', '660109543002', '660109544001', '660109544002', '660109544003', '660109544006', '660109544007', '660109545001', '660109545002', '660109545003', '660109545004', '660109545005', '660109547001', '660109547002', '660109547003', '660109548001', '660109548002', '660109548003', '660109548004', '660109551001', '660109551002', '660109551003', '660109551004', '660109552001', '660109552002', '660109552003', '660109553001', '660109553002', '660109554001', '660109556001', '660109556002', '660109557001', '660109557002', '660109557003', '660109557004', '660109557005', '660109557006', '660109557007', '660109558001', '660109558002', '660109558003', '660109558004', '660109558005', '660109558006', '660109558007', '660109558008', '660109558009', '660109559001', '660109559002', '660109559003', '660109560001', '660109560002', '660109561001', '660109561002', '660109561004', '660109562001', '660109562002', '660109562003', '660109562004', '660109562005', '660109562006', '660109563001', '660109563003', '660109563004', '660109563005', '660109801001', '660109804001', '660109900000', '691009501001', '691009501002', '691009501003', '691100001001', '691100001002', '691100002001', '691100002002', '691100003001', '691100003002', '691100004001', '691100004002', '691100005001', '691100005002', '691100006001', '691100006002', '691100006003', '691100007001', '691100007002', '691100007003', '691100008001', '691100008002', '691100009001', '691100009002', '691100009003', '691100010001', '691100010002', '691100011001', '691100012001', '691100012002', '691100013001', '691100013002', '691100013003', '691100014001', '691100014002', '691100014003', '691100015001', '691100015002', '691100015003', '691100015004', '691100015005', '691100016001', '691100016002', '691100017001', '691100017002', '691100017003', '691100017004', '691109900000', '691209501011', '691209501012', '691209501013', '691209502001', '691209502002', '780109701001', '780109701002', '780109702001', '780109702002', '780109703001', '780109703002', '780109703003', '780109704001', '780109704002', '780109704003', '780109704004', '780109705001', '780109705002', '780109705003', '780109706001', '780109706002', '780109706003', '780109706004', '780109706005', '780109707001', '780109707002', '780109707003', '780109708001', '780109708002', '780109709001', '780109710001', '780109710002', '780109711001', '780109711002', '780109711003', '780109711004', '780109712001', '780109712002', '780109712003', '780109712004', '780109713001', '780109713002', '780109713003', '780109714001', '780109715001', '780109715002', '780109715003', '780109900000', '780209501001', '780209501002', '780209501003', '780209502001', '780209502002', '780209502003', '780209502004', '780209900000', '780309601001', '780309601002', '780309601003', '780309602001', '780309602002', '780309602003', '780309603001', '780309603002', '780309603003', '780309604001', '780309604002', '780309604003', '780309604004', '780309605001', '780309605002', '780309605003', '780309605004', '780309605005', '780309606001', '780309606002', '780309606003', '780309607001', '780309607002', '780309607003', '780309608001', '780309608002', '780309609001', '780309609002', '780309610001', '780309610002', '780309610003', '780309610004', '780309610005', '780309611001', '780309611002', '780309612001', '780309612002', '780309900000']

FIPS only in ACS but NOT in SafeGraph:, 122 ['060159900000', '060374300033', '080149803001', '120519900000', '120659900000', '120839800001', '120839801001', '120879801001', '121239900000', '131799900000', '131919900000', '150019901000', '150019904000', '150019905000', '150019906000', '150019910000', '150019911000', '150019912000', '150019915000', '150019916000', '150039812001', '150059900000', '150070412002', '150079902000', '150079903000', '150099900000', '150099912000', '160439701002', '230099900000', '230299900000', '250056171015', '250179800001', '260099900000', '260119901000', '260139901000', '260199900000', '260419900000', '260539900000', '260619900000', '260619901000', '260839901000', '260959900000', '261479900000', '261539900000', '320319901000', '340297225000', '340297310020', '340297380010', '350010047421', '350439403001', '360039402001', '360050024000', '360050028000', '360050115020', '360050319000', '360050516005', '360119902000', '360470054000', '360470174000', '360470176000', '360470280000', '360470286000', '360470292000', '360470294000', '360470702031', '360599903020', '360639401001', '360739900000', '360810916020', '360810922000', '360810928000', '360810942030', '360810964000', '360810972020', '360811113000', '360850112020', '360850128040', '360850128060', '360850223003', '360850244010', '361190056001', '370319902000', '370559706020', '370899801001', '371379901000', '371399607020', '371439202020', '371779601000', '390959900000', '410199900000', '410459400001', '480579900000', '480719900000', '482459900000', '482619900000', '482739900000', '484899900000', '510019902000', '511039901000', '511199901000', '511959312003', '517359901000', '530319900000', '550039900000', '550079900000', '550299900000', '550319900000', '550519900000', '720039900000', '720119900000', '720159915000', '720179900000', '720279900000', '720499905010', '720539901030', '720599900010', '720799911000', '720899900010', '721099900000', '721159900000', '721339900000', '721519900000']

Removed devices only in 390 SafeGraph FIPS: 44911 devices.

Removed these 122 block groups, 272 people.

Before merge ACS data row count: 2643603

After merge ACS data row count:  2639497

ACS columns:
Index(['state_fips', 'county_fips', 'tract_fips', 'fips', 'state',
       'totalpopulation', 'male', 'female', 'under5years', '5to9years',
       '10to14years', '15to17years', '18to24years', '25to34years',
       '35to44years', '45to54years', '55to64years', '65to74years',
       '75to84years', '85yearsandover', 'whitealone',
       'blackorafricanamericanalone', 'americanindianandalaskanativealone',
       'asianalone', 'nativehawaiianandotherpacificislanderalone',
       'someotherracealone', 'twoormoreraces', 'Hispanic_or_Latino',
       'population25yearsandover',
       'population25yearsandoverlessthanhighschool',
       'population25yearsandoverhighschoolgraduateincludesequivalency',
       'population25yearsandoversomecollege',
       'population25yearsandoverbachelorsdegree',
       'population25yearsandovermastersdegree',
       'population25yearsandoverprofessionalschooldegree',
       'population25yearsandoverdoctoratedegree', 'households',
       'householdslessthan10000', 'households10000to14999',
       'households15000to19999', 'households20000to24999',
       'households25000to29999', 'households30000to34999',
       'households35000to39999', 'households40000to44999',
       'households45000to49999', 'households50000to59999',
       'households60000to74999', 'households75000to99999',
       'households100000to124999', 'households125000to149999',
       'households150000to199999', 'households200000ormore', 'Female', 'Male',
       '<15', '15–17', '18–24', '25–34', '35–44', '45–54', '55–64', '>65',
       'White', 'Black', 'Hispanic', 'Asian', 'NoSchool', 'HighSchool',
       'NoCollege', 'Bachelor', 'Graduate', 'household_size', '<20K',
       '20K–30K', '30K–50K', '50K–100K', '>100K', 'cbg_fips', 'nation_fips'],
      dtype='object')

C:\Users\N\AppData\Local\Temp\ipykernel_29588\821876159.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_variable_df['region_tag'] = 'Deep South'
C:\Users\N\AppData\Local\Temp\ipykernel_29588\4010543827.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df.loc[:, 'state_fips'] = residing_df['state_fips'].astype(str).str.zfill(2)
C:\Users\N\AppData\Local\Temp\ipykernel_29588\4010543827.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df['date_range_start'] = residing_df['date_range_start'].astype(str).str[:10]   # have an issue of different starting hours
100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.51it/s]

## Report

In [71]:
df

,region_tag,variable,start_date,end_date,period_count,CBG_count,safegraph_ratio_mean,safegraph_ratio_median,safegraph_ratio_min,safegraph_ratio_max,census_ratio,device_count,population,safegraph_ratio_mean_to_census,safegraph_ratio_median_to_census,safegraph_ratio_min_to_census,safegraph_ratio_max_to_census,bias,bias_median,bias_min,bias_max
0,Deep South,Female,201901,201912,12,54793,0.512,0.512,0.512,0.512,0.511,4478470.041,47902892.333,1.002,1.002,1.001,1.003,0.002,0.002,0.001,0.003
1,Deep South,Male,201901,201912,12,54793,0.489,0.489,0.489,0.490,0.490,4278400.336,45908552.250,0.999,0.999,0.998,1.000,-0.001,-0.001,-0.002,-0.000
2,Deep South,<15,201901,201912,12,54793,0.131,0.131,0.130,0.132,0.133,1146608.441,12497364.250,0.983,0.984,0.976,0.991,-0.017,-0.016,-0.024,-0.009
3,Deep South,15–17,201901,201912,12,54793,0.033,0.033,0.032,0.033,0.033,284509.476,3073657.500,0.992,0.992,0.983,0.999,-0.008,-0.008,-0.017,-0.001
4,Deep South,18–24,201901,201912,12,54793,0.053,0.053,0.053,0.054,0.052,462676.107,4912184.000,1.010,1.008,1.004,1.022,0.010,0.008,0.004,0.022
5,Deep South,25–34,201901,201912,12,54793,0.063,0.063,0.063,0.064,0.062,555003.064,5857822.167,1.015,1.016,1.007,1.022,0.015,0.016,0.007,0.022
6,Deep South,35–44,201901,201912,12,54793,0.063,0.063,0.062,0.063,0.062,551531.095,5836170.000,1.013,1.014,1.003,1.017,0.013,0.014,0.003,0.017
7,Deep South,45–54,201901,201912,12,54793,0.065,0.065,0.064,0.065,0.064,566437.285,5999947.500,1.012,1.014,1.002,1.015,0.012,0.014,0.002,0.015
8,Deep South,55–64,201901,201912,12,54793,0.067,0.067,0.066,0.067,0.065,583571.675,6134965.000,1.019,1.020,1.009,1.024,0.019,0.020,0.009,0.024
9,Deep South,>65,201901,201912,12,54793,0.112,0.113,0.111,0.114,0.112,984173.828,10465077.167,1.007,1.008,0.992,1.019,0.007,0.008,-0.008,0.019
10,Deep South,White,201901,201912,12,54793,0.716,0.716,0.707,0.722,0.705,6261200.715,66120211.500,1.015,1.015,1.002,1.024,0.015,0.015,0.002,0.024
11,Deep South,Black,201901,201912,12,54793,0.049,0.049,0.048,0.050,0.048,428033.833,4496069.083,1.020,1.021,1.007,1.032,0.020,0.021,0.007,0.032
12,Deep South,Hispanic,201901,201912,12,54793,0.200,0.198,0.194,0.212,0.209,1750939.305,19555422.500,0.959,0.947,0.930,1.017,-0.041,-0.053,-0.070,0.017
13,Deep South,Asian,201901,201912,12,54793,0.017,0.017,0.017,0.018,0.017,152678.977,1551699.000,1.055,1.053,1.039,1.082,0.055,0.053,0.039,0.082
14,Deep South,NoSchool,201901,201912,12,54793,0.052,0.053,0.052,0.053,0.053,459077.128,4953068.833,0.993,0.994,0.982,1.003,-0.007,-0.006,-0.018,0.003
15,Deep South,HighSchool,201901,201912,12,54793,0.185,0.185,0.182,0.186,0.188,1616107.220,17614568.417,0.983,0.984,0.971,0.989,-0.017,-0.016,-0.029,-0.011
16,Deep South,NoCollege,201901,201912,12,54793,0.237,0.237,0.234,0.239,0.241,2075184.348,22567637.250,0.985,0.986,0.973,0.992,-0.015,-0.014,-0.027,-0.008
17,Deep South,Bachelor,201901,201912,12,54793,0.057,0.057,0.057,0.058,0.055,500924.407,5173964.000,1.037,1.040,1.025,1.049,0.037,0.040,0.025,0.049
18,Deep South,Graduate,201901,201912,12,54793,0.057,0.057,0.055,0.058,0.055,496394.986,5110155.000,1.041,1.043,1.018,1.061,0.041,0.043,0.018,0.061
19,Deep South,<20K,201901,201912,12,54793,0.150,0.150,0.148,0.152,0.155,1311454.097,14502154.727,0.969,0.968,0.954,0.984,-0.031,-0.032,-0.046,-0.016
20,Deep South,20K–30K,201901,201912,12,54793,0.094,0.093,0.092,0.095,0.096,818594.153,9019321.681,0.973,0.967,0.961,0.987,-0.027,-0.033,-0.039,-0.013
21,Deep South,30K–50K,201901,201912,12,54793,0.176,0.175,0.174,0.178,0.179,1535762.379,16787194.682,0.981,0.977,0.973,0.992,-0.019,-0.023,-0.027,-0.008
22,Deep South,50K–100K,201901,201912,12,54793,0.262,0.262,0.261,0.262,0.263,2288769.179,24663076.870,0.995,0.995,0.992,0.996,-0.005,-0.005,-0.008,-0.004
23,Deep South,>100K,201901,201912,12,54793,0.221,0.222,0.217,0.225,0.214,1936608.818,20058969.425,1.035,1.037,1.014,1.052,0.035,0.037,0.014,0.052

In [75]:

df_new = pd.DataFrame()

for year in years[:]:
    print(year)
    region_name = r'deep_south'
    csv_file = os.path.join(save_dir, f'monthly_bias_{region_name}_{year}.csv')
    df = pd.read_csv(csv_file)
    
    df_new['variable'] =  df.iloc[:, 1]
    df_new[f'{year}'] = df[f'bias_median'].apply('{:.3f}'.format) + ' [' + df[f'bias_min'].apply('{:.3f}'.format).astype(str) + ', ' +  df[f'bias_max'].apply('{:.3f}'.format).astype(str)+ ']'
    # break
    # bias_df
df_new.set_index('variable', inplace=True)
    
df_new = df_new.loc[columns]
df_new.to_csv(os.path.join(save_dir, f'bias_{region_name}_2018-2022_table.csv'))    
df_new

2019
2020
2021
2022

,2019,2020,2021,2022
variable,,,,
Female,"0.002 [0.001, 0.003]","0.002 [0.002, 0.003]","0.002 [0.000, 0.003]","0.000 [-0.001, 0.001]"
Male,"-0.001 [-0.002, -0.000]","-0.001 [-0.002, -0.000]","-0.001 [-0.002, 0.000]","0.001 [-0.000, 0.002]"
<15,"-0.016 [-0.024, -0.009]","-0.013 [-0.020, -0.009]","-0.011 [-0.018, -0.004]","-0.008 [-0.013, -0.002]"
15–17,"-0.008 [-0.017, -0.001]","-0.001 [-0.012, 0.003]","0.002 [-0.003, 0.009]","0.005 [-0.005, 0.015]"
18–24,"0.008 [0.004, 0.022]","-0.001 [-0.006, 0.004]","0.010 [-0.005, 0.023]","0.020 [0.004, 0.039]"
25–34,"0.016 [0.007, 0.022]","0.005 [0.002, 0.011]","0.016 [0.001, 0.028]","0.022 [0.004, 0.054]"
35–44,"0.014 [0.003, 0.017]","0.006 [0.003, 0.013]","0.014 [0.001, 0.022]","0.019 [0.005, 0.042]"
45–54,"0.014 [0.002, 0.015]","0.014 [0.009, 0.019]","0.023 [0.015, 0.033]","0.029 [0.013, 0.054]"
55–64,"0.020 [0.009, 0.024]","0.024 [0.014, 0.029]","0.033 [0.026, 0.044]","0.041 [0.020, 0.068]"
>65,"0.008 [-0.008, 0.019]","0.028 [0.010, 0.034]","0.034 [0.019, 0.038]","0.032 [0.022, 0.053]"
White,"0.015 [0.002, 0.024]","0.042 [0.026, 0.045]","0.038 [0.027, 0.046]","0.035 [0.017, 0.057]"
Black,"0.021 [0.007, 0.032]","-0.011 [-0.027, -0.001]","0.012 [-0.013, 0.043]","0.025 [-0.032, 0.069]"
Hispanic,"-0.053 [-0.070, 0.017]","-0.102 [-0.126, -0.078]","-0.118 [-0.146, -0.105]","-0.076 [-0.115, -0.031]"
Asian,"0.053 [0.039, 0.082]","0.007 [0.000, 0.020]","-0.012 [-0.031, 0.006]","-0.035 [-0.081, -0.017]"
NoSchool,"-0.006 [-0.018, 0.003]","-0.007 [-0.010, 0.002]","0.011 [-0.008, 0.028]","0.030 [0.021, 0.060]"
HighSchool,"-0.016 [-0.029, -0.011]","0.004 [-0.005, 0.008]","0.007 [-0.001, 0.016]","0.026 [0.016, 0.035]"
NoCollege,"-0.014 [-0.027, -0.008]","0.002 [-0.006, 0.006]","0.008 [-0.002, 0.019]","0.031 [0.017, 0.034]"
Bachelor,"0.040 [0.025, 0.049]","0.034 [0.024, 0.037]","0.033 [0.023, 0.035]","0.029 [0.002, 0.053]"
Graduate,"0.043 [0.018, 0.061]","0.028 [0.018, 0.035]","0.016 [-0.014, 0.040]","-0.009 [-0.056, 0.004]"
<20K,"-0.032 [-0.046, -0.016]","-0.049 [-0.068, -0.038]","-0.032 [-0.057, 0.002]","-0.002 [-0.038, 0.033]"
20K–30K,"-0.033 [-0.039, -0.013]","-0.043 [-0.051, -0.031]","-0.037 [-0.052, -0.014]","-0.012 [-0.028, 0.008]"
30K–50K,"-0.023 [-0.027, -0.008]","-0.028 [-0.031, -0.021]","-0.024 [-0.035, -0.008]","-0.008 [-0.015, 0.008]"
50K–100K,"-0.005 [-0.008, -0.004]","0.002 [-0.003, 0.005]","0.000 [-0.003, 0.002]","0.004 [0.000, 0.011]"
>100K,"0.037 [0.014, 0.052]","0.052 [0.037, 0.062]","0.046 [0.013, 0.064]","0.005 [-0.010, 0.030]"

In [ ]:
df_new = pd.DataFrame()
for year in years:
    # print(year)
    
    # 
    # df_new[f'{year}_mean'] = df[f'{year}_mean'].apply('{:.3f}'.format)
    # df_new[f'{year}_median'] = df[f'{year}_median']
    # if level == 'county':
    #     df_new['Urban'] = df.iloc[:, 0]
    df_new['variable'] =  df.iloc[:, 1]
    df_new[f'{year}'] = df[f'{year}_median'].apply('{:.3f}'.format) + ' [' + df[f'{year}_min'].apply('{:.3f}'.format).astype(str) + ', ' +  df[f'{year}_max'].apply('{:.3f}'.format).astype(str)+ ']'
    # df_new[f'{year}_max'] = df[f'{year}_max']

    
df_new.set_index('variable', inplace=True)
    
df_new = df_new.loc[columns]
df_new.to_csv(os.path.join(save_dir, f'violin_bias_{level}_2018-2022_table.csv'))    
df_new

In [36]:
for year in [2018, 2019, 2020, 2021, 2022][::-1]:
    print(year)
    if year > 2019:
        acs_year = 2019
    else:
        acs_year = year
 

    residing_variable_df, ACS_df = load_data(year = year)
    df_all = compute_sampling_rates(residing_variable_df, ACS_df=ACS_df, aggre_columns = ['nation_fips', 'state_fips', 'county_fips', 'tract_fips', 'cbg_fips'])

    df_all['fips_len'] = df_all['fips'].astype(str).str.len()
    df_all['fips_level'] = df_all['fips_len'].astype(str)
    df_all['fips_level'] = df_all['fips_level'].replace({'1': 'nation', '2':"state", '5':"county", '11': 'tract', '12':'CBG'})

    sampling_rates_csv_name = os.path.join(save_dir, fr'sampling_rates_{year}_monthly.csv')
    df_all.to_csv(sampling_rates_csv_name, index=False)
    
    rate_gb_df = time_aggregate(df_all.iloc[:]).reset_index()# .query(" sampling_rate < 0.5 ")).reset_index()  # remove the outliers
    # rate_gb_df.to_csv(r'P:\Shared drives\NJIT_T5\safegraph_bias\sampling_rates_yearly.csv', index=False)
    rate_gb_df['fips_len'] = rate_gb_df['fips'].astype(str).str.len()
    rate_gb_df['fips_level'] = rate_gb_df['fips_len'].astype(str)
    rate_gb_df['fips_level'] = rate_gb_df['fips_level'].replace({'1':'nation', '2':"state", '5':"county", '11': 'tract', '12':'cbg'})

    rate_gb_df.to_csv(os.path.join(save_dir, fr'sampling_rates_{year}_monthly_yearly.csv'), index=False)
    # 
    # bias
    
    # bias_gb_df, bias_df = compute_nation_bias()
    # bias_gb_df, bias_df = compute_state_bias()
    # bias_gb_df, bias_df = compute_county_bias()
    bias_gb_df, bias_df = compute_region_bias()

2022
US population: 327939105, male, female: 166551005 161465237

FIPS count in SafeGraph：220786, in ACS: 220333

FIPS only in SafeGraph but NOT in ACS:, 516 ['0CA:13020068', '0CA:13020069', '0CA:13020071', '0CA:13020079', '0CA:13020085', '0CA:13020090', '0CA:13020091', '0CA:13020092', '0CA:13020096', '0CA:13100277', '0CA:13130093', '0CA:13130094', '0CA:13130095', '0CA:13130096', '0CA:13130100', '0CA:13130101', '0CA:13130102', '0CA:13130103', '0CA:13130105', '0CA:13130106', '0CA:13130115', '0CA:13130119', '0CA:13130132', '0CA:24170059', '0CA:24170060', '0CA:24170065', '0CA:24290142', '0CA:24440063', '0CA:24450147', '0CA:24450148', '0CA:24450149', '0CA:24450150', '0CA:24690094', '0CA:24690108', '0CA:35010304', '0CA:35010306', '0CA:35010307', '0CA:35010308', '0CA:35010309', '0CA:35010310', '0CA:35010323', '0CA:35010407', '0CA:35010408', '0CA:35070201', '0CA:35070202', '0CA:35070203', '0CA:35070204', '0CA:35070205', '0CA:35070207', '0CA:35070215', '0CA:35070216', '0CA:35070222', '0CA:35070236', '0CA:35070237', '0CA:35070238', '0CA:35070241', '0CA:35070242', '0CA:35070243', '0CA:35070244', '0CA:35070248', '0CA:35070249', '0CA:35070250', '0CA:35070317', '0CA:35070324', '0CA:35100292', '0CA:35260093', '0CA:35260094', '0CA:35260095', '0CA:35260096', '0CA:35260133', '0CA:35260716', '0CA:35260718', '0CA:35260719', '0CA:35260754', '0CA:35380142', '0CA:35380326', '0CA:35380327', '0CA:35380353', '0CA:35570068', '0CA:35570070', '0CA:35570073', '0CA:35570074', '0CA:35570075', '0CA:35570076', '0CA:35570077', '0CA:35570078', '0CA:35570079', '0CA:35570080', '0CA:35570081', '0CA:35570082', '0CA:35570083', '0CA:35570084', '0CA:35570086', '0CA:35570087', '0CA:35570103', '0CA:35570105', '0CA:35570106', '0CA:35570107', '0CA:35570109', '0CA:35570111', '0CA:35570112', '0CA:35570113', '0CA:35570114', '0CA:35570121', '0CA:35570123', '0CA:35570124', '0CA:35570125', '0CA:35570127', '0CA:35570128', '0CA:35570129', '0CA:35570136', '0CA:35570137', '0CA:35570138', '0CA:35570279', '0CA:35570314', '0CA:35570375', '0CA:35570387', '0CA:35570388', '0CA:35570389', '0CA:35570414', '0CA:35570415', '0CA:35570416', '0CA:35570417', '0CA:35590066', '0CA:35590067', '0CA:35590068', '0CA:35590073', '0CA:35590076', '0CA:35590081', '0CA:35590087', '0CA:35590089', '0CA:35590090', '0CA:35590091', '0CA:35590092', '0CA:35590093', '0CA:35590094', '0CA:35590095', '0CA:35590124', '0CA:59090159', '600109501002', '600109503001', '600109503003', '600109505001', '600109505002', '600109506001', '600109506002', '600109506003', '600109507001', '600109507002', '600109507003', '600109509002', '600109509003', '600209518002', '600509510001', '600509510002', '600509511001', '600509511002', '600509511003', '600509512011', '600509512012', '600509512021', '600509512022', '600509512031', '600509512032', '600509513001', '600509513002', '600509515001', '600509516001', '600509516003', '600509516004', '660109501001', '660109501002', '660109501003', '660109501004', '660109501005', '660109502003', '660109502004', '660109502005', '660109503001', '660109503002', '660109503003', '660109503004', '660109503005', '660109503006', '660109503007', '660109503008', '660109503009', '660109504011', '660109504012', '660109504013', '660109504014', '660109504015', '660109504016', '660109504021', '660109504022', '660109504023', '660109505011', '660109505012', '660109505021', '660109505022', '660109505023', '660109505024', '660109505025', '660109507011', '660109507012', '660109507013', '660109507014', '660109507015', '660109507016', '660109507017', '660109507021', '660109507022', '660109507023', '660109507024', '660109507025', '660109508011', '660109508012', '660109508013', '660109508014', '660109508021', '660109508022', '660109508023', '660109508024', '660109509001', '660109509002', '660109509003', '660109509004', '660109509005', '660109509006', '660109509007', '660109510001', '660109510002', '660109510003', '660109510004', '660109510005', '660109510006', '660109510007', '660109510008', '660109511001', '660109511002', '660109511003', '660109511004', '660109511005', '660109511006', '660109516001', '660109516002', '660109517001', '660109517002', '660109518001', '660109519011', '660109519012', '660109519013', '660109519014', '660109519021', '660109519022', '660109519023', '660109519024', '660109522001', '660109522002', '660109522003', '660109522004', '660109523001', '660109523002', '660109523003', '660109524001', '660109524002', '660109527001', '660109527002', '660109527003', '660109527004', '660109527005', '660109528002', '660109529001', '660109529002', '660109529003', '660109529004', '660109529005', '660109529006', '660109530001', '660109530002', '660109530003', '660109530004', '660109530005', '660109531011', '660109531012', '660109531013', '660109531021', '660109531022', '660109531023', '660109532001', '660109532002', '660109532003', '660109533001', '660109533002', '660109533003', '660109533004', '660109534001', '660109534002', '660109535001', '660109536001', '660109536002', '660109536003', '660109536004', '660109536005', '660109539001', '660109539002', '660109539003', '660109539004', '660109540001', '660109540002', '660109543001', '660109543002', '660109544001', '660109544003', '660109544004', '660109544005', '660109544006', '660109545001', '660109545002', '660109545003', '660109545004', '660109547001', '660109547002', '660109547003', '660109548001', '660109548002', '660109548003', '660109548004', '660109551001', '660109551002', '660109551003', '660109551004', '660109552001', '660109552002', '660109552003', '660109553001', '660109553002', '660109554001', '660109556001', '660109556002', '660109557001', '660109557002', '660109557003', '660109557004', '660109557005', '660109557006', '660109558001', '660109558002', '660109558003', '660109558004', '660109558005', '660109558006', '660109558007', '660109558008', '660109558009', '660109559001', '660109559002', '660109559003', '660109560001', '660109560002', '660109561001', '660109561002', '660109561004', '660109562001', '660109562002', '660109562003', '660109562004', '660109562005', '660109563001', '660109563004', '660109563005', '660109801001', '660109804001', '660109900000', '691009501001', '691009501002', '691009501003', '691009900000', '691100001001', '691100001002', '691100002001', '691100002002', '691100003001', '691100003002', '691100004001', '691100004002', '691100005001', '691100005002', '691100006001', '691100006002', '691100006003', '691100007001', '691100007002', '691100007003', '691100008001', '691100008002', '691100009001', '691100009002', '691100009003', '691100010001', '691100010002', '691100011001', '691100012001', '691100012002', '691100013001', '691100013002', '691100013003', '691100014001', '691100014002', '691100014003', '691100015001', '691100015002', '691100015003', '691100015004', '691100015005', '691100016001', '691100016002', '691100017001', '691100017002', '691100017003', '691100017004', '691109900000', '691209501011', '691209501012', '691209501013', '691209502001', '691209502002', '780109701001', '780109701002', '780109702001', '780109702002', '780109703001', '780109703002', '780109703003', '780109704001', '780109704002', '780109704003', '780109704004', '780109705001', '780109705002', '780109705003', '780109706001', '780109706002', '780109706003', '780109706004', '780109706005', '780109707001', '780109707002', '780109707003', '780109708001', '780109708002', '780109709001', '780109710001', '780109710002', '780109711001', '780109711002', '780109711003', '780109711004', '780109712001', '780109712002', '780109712003', '780109712004', '780109713001', '780109713002', '780109713003', '780109714001', '780109715001', '780109715002', '780109715003', '780109900000', '780209501001', '780209501002', '780209501003', '780209502001', '780209502002', '780209502003', '780209502004', '780209900000', '780309601001', '780309601002', '780309601003', '780309602001', '780309602002', '780309602003', '780309603001', '780309603002', '780309603003', '780309604001', '780309604002', '780309604003', '780309604004', '780309605001', '780309605002', '780309605003', '780309605004', '780309605005', '780309606001', '780309606002', '780309606003', '780309607001', '780309607002', '780309607003', '780309608001', '780309608002', '780309609001', '780309609002', '780309610001', '780309610002', '780309610003', '780309610004', '780309610005', '780309611001', '780309611002', '780309612001', '780309612002', '780309900000']

FIPS only in ACS but NOT in SafeGraph:, 63 ['060374300033', '060374604012', '060759804011', '120659900000', '120839801001', '131919900000', '150019900000', '150019901000', '150019906000', '150019909000', '150019910000', '150019911000', '150019914000', '150039812001', '150070412002', '150079902000', '150079903000', '160439701002', '220870301053', '260099900000', '260539900000', '260619901000', '260959900000', '261579900000', '300290017002', '325109900000', '340297310020', '340297360010', '350010047421', '350439403001', '360050319000', '360599902000', '360639401001', '360850081000', '360850223003', '361190056001', '370159604000', '370559701020', '371379901000', '410459400001', '440050401031', '480719900000', '482619900000', '484899900000', '511039901000', '530619901000', '550519900000', '720039900000', '720059900000', '720119900000', '720179900000', '720339800081', '720519900210', '720539901030', '720599900010', '720719900000', '720919900250', '720959900000', '721039900130', '721099900000', '721119900000', '721139930000', '721159900000']

Removed devices only in 516 SafeGraph FIPS: 73689 devices.

Removed these 63 block groups, 3 people.

Before merge ACS data row count: 2644588

After merge ACS data row count:  2640121

ACS columns:
Index(['state_fips', 'county_fips', 'tract_fips', 'fips', 'state',
       'totalpopulation', 'male', 'female', 'under5years', '5to9years',
       '10to14years', '15to17years', '18to24years', '25to34years',
       '35to44years', '45to54years', '55to64years', '65to74years',
       '75to84years', '85yearsandover', 'whitealone',
       'blackorafricanamericanalone', 'americanindianandalaskanativealone',
       'asianalone', 'nativehawaiianandotherpacificislanderalone',
       'someotherracealone', 'twoormoreraces', 'Hispanic_or_Latino',
       'population25yearsandover',
       'population25yearsandoverlessthanhighschool',
       'population25yearsandoverhighschoolgraduateincludesequivalency',
       'population25yearsandoversomecollege',
       'population25yearsandoverbachelorsdegree',
       'population25yearsandovermastersdegree',
       'population25yearsandoverprofessionalschooldegree',
       'population25yearsandoverdoctoratedegree', 'households',
       'householdslessthan10000', 'households10000to14999',
       'households15000to19999', 'households20000to24999',
       'households25000to29999', 'households30000to34999',
       'households35000to39999', 'households40000to44999',
       'households45000to49999', 'households50000to59999',
       'households60000to74999', 'households75000to99999',
       'households100000to124999', 'households125000to149999',
       'households150000to199999', 'households200000ormore', 'Female', 'Male',
       '<15', '15–17', '18–24', '25–34', '35–44', '45–54', '55–64', '>65',
       'White', 'Black', 'Hispanic', 'Asian', 'NoSchool', 'HighSchool',
       'NoCollege', 'Bachelor', 'Graduate', 'household_size', '<20K',
       '20K–30K', '30K–50K', '50K–100K', '>100K', 'cbg_fips', 'nation_fips'],
      dtype='object')
Use the US population 327939105 for the naion level bias:

C:\Users\N\AppData\Local\Temp\ipykernel_10560\2597773154.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df.loc[:, 'state_fips'] = residing_df['state_fips'].astype(str).str.zfill(2)
C:\Users\N\AppData\Local\Temp\ipykernel_10560\2597773154.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df['date_range_start'] = residing_df['date_range_start'].astype(str).str[:10]   # have an issue of different starting hours
100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [00:07<00:00,  1.52it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 624/624 [00:21<00:00, 28.50it/s]
100%|████████████████████████████████████████████████████████████████████████████| 38640/38640 [19:02<00:00, 33.83it/s]

2021
US population: 327939105, male, female: 166551005 161465237

FIPS count in SafeGraph：220534, in ACS: 220333

FIPS only in SafeGraph but NOT in ACS:, 345 ['0CA:24450148', '600109506002', '600109507002', '600109507003', '600109509002', '600109509003', '600109509004', '600509510002', '600509511001', '600509511002', '600509512011', '600509512012', '600509512021', '600509512032', '600509512033', '600509513002', '600509515001', '600509516004', '660109501001', '660109501002', '660109501003', '660109501004', '660109501005', '660109502003', '660109502004', '660109502005', '660109503002', '660109503003', '660109503004', '660109503009', '660109504011', '660109504012', '660109504013', '660109504014', '660109504015', '660109504016', '660109504021', '660109504022', '660109504023', '660109505011', '660109505012', '660109505021', '660109505022', '660109505023', '660109505024', '660109505025', '660109507011', '660109507012', '660109507013', '660109507014', '660109507015', '660109507016', '660109507017', '660109507021', '660109507022', '660109507023', '660109507024', '660109507025', '660109508011', '660109508012', '660109508013', '660109508014', '660109508021', '660109508022', '660109508023', '660109508024', '660109509001', '660109509002', '660109509003', '660109509004', '660109509005', '660109509006', '660109509007', '660109510001', '660109510002', '660109510003', '660109510004', '660109510005', '660109510006', '660109510007', '660109510008', '660109511001', '660109511002', '660109511003', '660109511004', '660109511005', '660109511006', '660109516001', '660109516002', '660109517001', '660109517002', '660109518001', '660109519011', '660109519012', '660109519013', '660109519014', '660109519021', '660109519022', '660109519023', '660109519024', '660109522001', '660109522002', '660109522003', '660109522004', '660109523001', '660109523002', '660109523003', '660109524001', '660109524002', '660109527001', '660109527002', '660109527003', '660109527004', '660109527005', '660109529001', '660109529002', '660109529003', '660109529004', '660109529005', '660109529006', '660109530001', '660109530002', '660109530003', '660109530004', '660109530005', '660109531011', '660109531012', '660109531013', '660109531021', '660109531022', '660109531023', '660109532001', '660109532002', '660109532003', '660109533001', '660109533002', '660109533003', '660109533004', '660109534001', '660109534002', '660109535001', '660109536001', '660109536002', '660109536003', '660109536004', '660109536005', '660109539001', '660109539002', '660109539003', '660109539004', '660109540001', '660109540002', '660109543001', '660109543002', '660109544001', '660109544002', '660109544003', '660109544004', '660109544007', '660109545001', '660109545002', '660109545003', '660109545004', '660109547001', '660109547002', '660109547003', '660109548001', '660109548002', '660109548003', '660109548004', '660109551001', '660109551002', '660109551003', '660109551004', '660109552001', '660109552002', '660109552003', '660109553001', '660109553002', '660109554001', '660109556001', '660109556002', '660109557001', '660109557002', '660109557003', '660109557004', '660109557005', '660109557006', '660109558001', '660109558002', '660109558003', '660109558004', '660109558005', '660109558006', '660109558007', '660109558008', '660109558009', '660109559001', '660109559002', '660109559003', '660109560001', '660109560002', '660109561001', '660109561002', '660109561004', '660109562001', '660109562002', '660109562003', '660109562004', '660109562005', '660109563001', '660109563004', '660109563005', '660109801001', '660109804001', '660109900000', '690859501001', '691009501001', '691009501002', '691009501003', '691100001001', '691100002001', '691100002002', '691100003001', '691100004001', '691100004002', '691100005001', '691100005002', '691100006001', '691100006003', '691100007001', '691100007002', '691100008002', '691100009001', '691100009002', '691100009003', '691100010001', '691100010002', '691100011001', '691100012001', '691100012002', '691100013001', '691100013003', '691100014002', '691100015002', '691100015003', '691100016001', '691100016002', '691100017001', '691100017002', '691100017003', '691100017004', '691209501012', '691209501013', '691209502001', '691209502002', '780109701001', '780109701002', '780109702001', '780109702002', '780109703001', '780109703002', '780109703003', '780109704001', '780109704002', '780109704003', '780109704004', '780109705001', '780109705002', '780109705003', '780109706001', '780109706002', '780109706003', '780109706004', '780109706005', '780109707001', '780109707002', '780109707003', '780109708001', '780109708002', '780109709001', '780109710001', '780109710002', '780109711001', '780109711002', '780109711003', '780109711004', '780109712001', '780109712002', '780109712003', '780109712004', '780109713001', '780109713002', '780109713003', '780109714001', '780109715001', '780109715002', '780109715003', '780109900000', '780209501001', '780209501002', '780209501003', '780209502001', '780209502002', '780209502003', '780209502004', '780209900000', '780309601001', '780309601002', '780309601003', '780309602001', '780309602002', '780309602003', '780309603001', '780309603002', '780309603003', '780309604001', '780309604002', '780309604003', '780309604004', '780309605001', '780309605002', '780309605003', '780309605004', '780309605005', '780309606001', '780309606002', '780309606003', '780309607001', '780309607002', '780309607003', '780309608001', '780309608002', '780309609001', '780309609002', '780309610001', '780309610002', '780309610003', '780309610004', '780309610005', '780309611001', '780309611002', '780309612001', '780309612002', '780309900000']

FIPS only in ACS but NOT in SafeGraph:, 144 ['060159900000', '060374300033', '060374303012', '060374604012', '061110036121', '080149801001', '080149803001', '120179900000', '120299900000', '120519900000', '120659900000', '120839801001', '120859901000', '121059800001', '121239900000', '130399900000', '131799900000', '131919900000', '150019900000', '150019901000', '150019906000', '150019909000', '150019910000', '150019911000', '150019913000', '150019914000', '150019917000', '150039812001', '150059900000', '150070412002', '150079902000', '150079903000', '150099800001', '150099900000', '150099912000', '160439701002', '210670039161', '220870301053', '220879900000', '221019900000', '221139900000', '230099900000', '230159756003', '230299900000', '260099900000', '260119900000', '260139901000', '260199900000', '260339801001', '260619901000', '260959800001', '260959900000', '261399900000', '261479900000', '270759901000', '280459900000', '300290017002', '325109900000', '360050115020', '360050319000', '360050516005', '360191019006', '360470164000', '360470168000', '360470174000', '360470280000', '360470282000', '360470616000', '360470702031', '360599901000', '360599902000', '360599903020', '360610007002', '360610136000', '360610175000', '360610195000', '360610223020', '360610225000', '360639401001', '360810992000', '360811008010', '360811010010', '360850081000', '360850128050', '360850223003', '360850323000', '361190056001', '370159604000', '370299501020', '370419301010', '370559701020', '370559704000', '370559706020', '371379901000', '371399607020', '371439201000', '390959900000', '410119901010', '410199900000', '410399900000', '410459400001', '480079900000', '480579900000', '480719900000', '482459900000', '482619900000', '484899900000', '510019902000', '511039901000', '511199901000', '530319900000', '530619901000', '550039900000', '550079900000', '550319900000', '550519900000', '720054009002', '720119900000', '720159915000', '720179900000', '720339800021', '720339800081', '720371601002', '720539901030', '720579926000', '720599900010', '720659900160', '720699918000', '720759900010', '720799911000', '720879900000', '720899900010', '720919900250', '721039900130', '721099900000', '721119900000', '721139930000', '721159900000', '721179904000', '721239928000', '721279803001', '721339900000', '721379900000', '721519900000']

Removed devices only in 345 SafeGraph FIPS: 14346 devices.

Removed these 144 block groups, 128 people.

Before merge ACS data row count: 2640227

After merge ACS data row count:  2637932

ACS columns:
Index(['state_fips', 'county_fips', 'tract_fips', 'fips', 'state',
       'totalpopulation', 'male', 'female', 'under5years', '5to9years',
       '10to14years', '15to17years', '18to24years', '25to34years',
       '35to44years', '45to54years', '55to64years', '65to74years',
       '75to84years', '85yearsandover', 'whitealone',
       'blackorafricanamericanalone', 'americanindianandalaskanativealone',
       'asianalone', 'nativehawaiianandotherpacificislanderalone',
       'someotherracealone', 'twoormoreraces', 'Hispanic_or_Latino',
       'population25yearsandover',
       'population25yearsandoverlessthanhighschool',
       'population25yearsandoverhighschoolgraduateincludesequivalency',
       'population25yearsandoversomecollege',
       'population25yearsandoverbachelorsdegree',
       'population25yearsandovermastersdegree',
       'population25yearsandoverprofessionalschooldegree',
       'population25yearsandoverdoctoratedegree', 'households',
       'householdslessthan10000', 'households10000to14999',
       'households15000to19999', 'households20000to24999',
       'households25000to29999', 'households30000to34999',
       'households35000to39999', 'households40000to44999',
       'households45000to49999', 'households50000to59999',
       'households60000to74999', 'households75000to99999',
       'households100000to124999', 'households125000to149999',
       'households150000to199999', 'households200000ormore', 'Female', 'Male',
       '<15', '15–17', '18–24', '25–34', '35–44', '45–54', '55–64', '>65',
       'White', 'Black', 'Hispanic', 'Asian', 'NoSchool', 'HighSchool',
       'NoCollege', 'Bachelor', 'Graduate', 'household_size', '<20K',
       '20K–30K', '30K–50K', '50K–100K', '>100K', 'cbg_fips', 'nation_fips'],
      dtype='object')
Use the US population 327939105 for the naion level bias:

C:\Users\N\AppData\Local\Temp\ipykernel_10560\2597773154.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df.loc[:, 'state_fips'] = residing_df['state_fips'].astype(str).str.zfill(2)
C:\Users\N\AppData\Local\Temp\ipykernel_10560\2597773154.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df['date_range_start'] = residing_df['date_range_start'].astype(str).str[:10]   # have an issue of different starting hours
100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [00:07<00:00,  1.54it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 624/624 [00:21<00:00, 28.67it/s]
100%|████████████████████████████████████████████████████████████████████████████| 38639/38639 [18:44<00:00, 34.38it/s]

2020
US population: 327939105, male, female: 166551005 161465237

FIPS count in SafeGraph：220549, in ACS: 220333

FIPS only in SafeGraph but NOT in ACS:, 380 ['600109501001', '600109503001', '600109503002', '600109503003', '600109505001', '600109505002', '600109505003', '600109506001', '600109506002', '600109506003', '600109507001', '600109507002', '600109507003', '600109509001', '600109509002', '600109509003', '600109509004', '600509510001', '600509510002', '600509511001', '600509511002', '600509511003', '600509512011', '600509512012', '600509512021', '600509512022', '600509512031', '600509512032', '600509512033', '600509513001', '600509513002', '600509515001', '600509516002', '600509516003', '600509516004', '660109501001', '660109501002', '660109501003', '660109501004', '660109501005', '660109502003', '660109502004', '660109502005', '660109503002', '660109503003', '660109503004', '660109503006', '660109503007', '660109503008', '660109503009', '660109504011', '660109504012', '660109504013', '660109504014', '660109504015', '660109504016', '660109504021', '660109504022', '660109504023', '660109505011', '660109505012', '660109505021', '660109505022', '660109505023', '660109505024', '660109505025', '660109507011', '660109507012', '660109507013', '660109507014', '660109507015', '660109507016', '660109507017', '660109507021', '660109507022', '660109507023', '660109507024', '660109507025', '660109508011', '660109508012', '660109508013', '660109508014', '660109508021', '660109508022', '660109508023', '660109508024', '660109509001', '660109509002', '660109509003', '660109509004', '660109509005', '660109509006', '660109509007', '660109510001', '660109510002', '660109510003', '660109510004', '660109510005', '660109510006', '660109510007', '660109510008', '660109511001', '660109511002', '660109511003', '660109511004', '660109511005', '660109511006', '660109516001', '660109516002', '660109517001', '660109517002', '660109518001', '660109519011', '660109519012', '660109519013', '660109519014', '660109519021', '660109519022', '660109519023', '660109519024', '660109522001', '660109522002', '660109522003', '660109522004', '660109523001', '660109523002', '660109523003', '660109524001', '660109524002', '660109527001', '660109527002', '660109527003', '660109527004', '660109527005', '660109529001', '660109529002', '660109529003', '660109529004', '660109529005', '660109529006', '660109530001', '660109530002', '660109530003', '660109530004', '660109530005', '660109531011', '660109531012', '660109531013', '660109531021', '660109531022', '660109531023', '660109532001', '660109532002', '660109532003', '660109533001', '660109533002', '660109533003', '660109533004', '660109534001', '660109534002', '660109535001', '660109536001', '660109536002', '660109536003', '660109536004', '660109536005', '660109539001', '660109539002', '660109539003', '660109539004', '660109540001', '660109540002', '660109543001', '660109543002', '660109544001', '660109544002', '660109544003', '660109544004', '660109544005', '660109544006', '660109544007', '660109545001', '660109545002', '660109545003', '660109545004', '660109547001', '660109547002', '660109547003', '660109548001', '660109548002', '660109548003', '660109548004', '660109551001', '660109551002', '660109551003', '660109551004', '660109552001', '660109552002', '660109552003', '660109553001', '660109553002', '660109554001', '660109556001', '660109556002', '660109557001', '660109557002', '660109557003', '660109557004', '660109557005', '660109557006', '660109558001', '660109558002', '660109558003', '660109558004', '660109558005', '660109558006', '660109558007', '660109558008', '660109558009', '660109559001', '660109559002', '660109559003', '660109560001', '660109560002', '660109561001', '660109561002', '660109561004', '660109562001', '660109562002', '660109562003', '660109562004', '660109562005', '660109563001', '660109563003', '660109563004', '660109563005', '660109801001', '660109804001', '660109900000', '691009501001', '691009501002', '691009501003', '691100001001', '691100001002', '691100002001', '691100002002', '691100003001', '691100003002', '691100004001', '691100004002', '691100005001', '691100005002', '691100006001', '691100006002', '691100006003', '691100007001', '691100007002', '691100007003', '691100008001', '691100008002', '691100009001', '691100009002', '691100009003', '691100010001', '691100010002', '691100011001', '691100012001', '691100012002', '691100013001', '691100013002', '691100013003', '691100014001', '691100014002', '691100014003', '691100015001', '691100015002', '691100015003', '691100015004', '691100015005', '691100016001', '691100016002', '691100017001', '691100017002', '691100017003', '691100017004', '691109900000', '691209501011', '691209501012', '691209501013', '691209502001', '691209502002', '780109701001', '780109701002', '780109702001', '780109702002', '780109703001', '780109703002', '780109703003', '780109704001', '780109704002', '780109704003', '780109704004', '780109705001', '780109705002', '780109705003', '780109706001', '780109706002', '780109706003', '780109706004', '780109706005', '780109707001', '780109707002', '780109707003', '780109708001', '780109708002', '780109709001', '780109710001', '780109710002', '780109711001', '780109711002', '780109711003', '780109711004', '780109712001', '780109712002', '780109712003', '780109712004', '780109713001', '780109713002', '780109713003', '780109714001', '780109715001', '780109715002', '780109715003', '780109900000', '780209501001', '780209501002', '780209501003', '780209502001', '780209502002', '780209502003', '780209502004', '780209900000', '780309601001', '780309601002', '780309601003', '780309602001', '780309602002', '780309602003', '780309603001', '780309603002', '780309603003', '780309604001', '780309604002', '780309604003', '780309604004', '780309605001', '780309605002', '780309605003', '780309605004', '780309605005', '780309606001', '780309606002', '780309606003', '780309607001', '780309607002', '780309607003', '780309608001', '780309608002', '780309609001', '780309609002', '780309610001', '780309610002', '780309610003', '780309610004', '780309610005', '780309611001', '780309611002', '780309612001', '780309612002', '780309900000']

FIPS only in ACS but NOT in SafeGraph:, 164 ['060159900000', '060374300033', '060374303012', '060374604012', '060411242001', '060530141042', '080149801001', '120179900000', '120519900000', '120579901000', '120659900000', '120839801001', '120859901000', '121239900000', '121299900000', '130399900000', '131799900000', '131919900000', '150019900000', '150019901000', '150019904000', '150019905000', '150019906000', '150019910000', '150019911000', '150019912000', '150019913000', '150019914000', '150019917000', '150039812001', '150059900000', '150070412002', '150079902000', '150079903000', '150099800001', '150099912000', '160439701002', '220459900000', '220870301053', '230299900000', '260099900000', '260139901000', '260199900000', '260319900000', '260339801001', '260339900000', '260339901000', '260419901000', '260539900000', '260619900000', '260619901000', '260650044021', '260959800001', '260959900000', '261039900000', '261219900000', '261279900000', '261479900000', '261579900000', '261599900000', '261639902000', '270759901000', '280459900000', '320319901000', '325109900000', '340297225000', '340297310020', '340297360010', '340297380010', '350010047421', '350439403001', '360050028000', '360050115020', '360050516005', '360119902000', '360191019006', '360470052020', '360470164000', '360470280000', '360470282000', '360470292000', '360470330000', '360470616000', '360471028000', '360599903020', '360610175000', '360610223010', '360610223020', '360610225000', '360639401001', '360810992000', '360811008010', '360811008020', '360811010020', '360850081000', '360850223000', '360850223003', '360850228000', '360850244010', '360850323000', '361190056001', '370159604000', '370299501020', '370319902000', '370419301010', '370531104020', '370559701020', '370559705010', '370559706020', '370899801001', '370959902000', '371379901000', '371399607020', '371439201000', '371439202020', '390959900000', '410199900000', '410459400001', '420792156002', '480579900000', '480719900000', '482459900000', '484899900000', '510019902000', '511039901000', '511199901000', '530319900000', '530559901000', '530619901000', '550039900000', '550079900000', '550319900000', '550519900000', '720059900000', '720119900000', '720159915000', '720179900000', '720239800001', '720279900000', '720339800081', '720379900000', '720499905010', '720539901030', '720559900000', '720599900010', '720659900160', '720699918000', '720759900010', '720799911000', '720879900000', '720899900010', '720919900250', '720979900000', '721039900130', '721099900000', '721139930000', '721159900000', '721179904000', '721199927000', '721339900000', '721379900000', '721439900000', '721459900000', '721479900000']

Removed devices only in 380 SafeGraph FIPS: 57720 devices.

Removed these 164 block groups, 2001 people.

Before merge ACS data row count: 2643048

After merge ACS data row count:  2639245

ACS columns:
Index(['state_fips', 'county_fips', 'tract_fips', 'fips', 'state',
       'totalpopulation', 'male', 'female', 'under5years', '5to9years',
       '10to14years', '15to17years', '18to24years', '25to34years',
       '35to44years', '45to54years', '55to64years', '65to74years',
       '75to84years', '85yearsandover', 'whitealone',
       'blackorafricanamericanalone', 'americanindianandalaskanativealone',
       'asianalone', 'nativehawaiianandotherpacificislanderalone',
       'someotherracealone', 'twoormoreraces', 'Hispanic_or_Latino',
       'population25yearsandover',
       'population25yearsandoverlessthanhighschool',
       'population25yearsandoverhighschoolgraduateincludesequivalency',
       'population25yearsandoversomecollege',
       'population25yearsandoverbachelorsdegree',
       'population25yearsandovermastersdegree',
       'population25yearsandoverprofessionalschooldegree',
       'population25yearsandoverdoctoratedegree', 'households',
       'householdslessthan10000', 'households10000to14999',
       'households15000to19999', 'households20000to24999',
       'households25000to29999', 'households30000to34999',
       'households35000to39999', 'households40000to44999',
       'households45000to49999', 'households50000to59999',
       'households60000to74999', 'households75000to99999',
       'households100000to124999', 'households125000to149999',
       'households150000to199999', 'households200000ormore', 'Female', 'Male',
       '<15', '15–17', '18–24', '25–34', '35–44', '45–54', '55–64', '>65',
       'White', 'Black', 'Hispanic', 'Asian', 'NoSchool', 'HighSchool',
       'NoCollege', 'Bachelor', 'Graduate', 'household_size', '<20K',
       '20K–30K', '30K–50K', '50K–100K', '>100K', 'cbg_fips', 'nation_fips'],
      dtype='object')
Use the US population 327939105 for the naion level bias:

C:\Users\N\AppData\Local\Temp\ipykernel_10560\2597773154.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df.loc[:, 'state_fips'] = residing_df['state_fips'].astype(str).str.zfill(2)
C:\Users\N\AppData\Local\Temp\ipykernel_10560\2597773154.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df['date_range_start'] = residing_df['date_range_start'].astype(str).str[:10]   # have an issue of different starting hours
100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [00:07<00:00,  1.56it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 624/624 [00:21<00:00, 29.06it/s]
100%|████████████████████████████████████████████████████████████████████████████| 38640/38640 [18:50<00:00, 34.17it/s]

2019
US population: 327939105, male, female: 166551005 161465237

FIPS count in SafeGraph：220539, in ACS: 220333

FIPS only in SafeGraph but NOT in ACS:, 379 ['0CA:24680061', '0CA:59490105', '600109501001', '600109501002', '600109502001', '600109502002', '600109503001', '600109503002', '600109503003', '600109505001', '600109505002', '600109505003', '600109506001', '600109506002', '600109506003', '600109507001', '600109507002', '600109507003', '600109509001', '600109509002', '600109509003', '600109509004', '600209518001', '600209518002', '600509510001', '600509510002', '600509511001', '600509511002', '600509511003', '600509512011', '600509512012', '600509512021', '600509512022', '600509512031', '600509512032', '600509512033', '600509513001', '600509513002', '600509515001', '600509516001', '600509516003', '600509516004', '660109501001', '660109501002', '660109501003', '660109501004', '660109501005', '660109502003', '660109502004', '660109502005', '660109503002', '660109503003', '660109503004', '660109503009', '660109504011', '660109504012', '660109504013', '660109504014', '660109504015', '660109504016', '660109504021', '660109504022', '660109504023', '660109505011', '660109505012', '660109505021', '660109505022', '660109505023', '660109505024', '660109505025', '660109507011', '660109507012', '660109507013', '660109507014', '660109507015', '660109507016', '660109507017', '660109507021', '660109507022', '660109507023', '660109507024', '660109507025', '660109508011', '660109508012', '660109508013', '660109508014', '660109508021', '660109508022', '660109508023', '660109508024', '660109509001', '660109509002', '660109509003', '660109509004', '660109509005', '660109509006', '660109509007', '660109510001', '660109510002', '660109510003', '660109510004', '660109510005', '660109510006', '660109510007', '660109510008', '660109511001', '660109511002', '660109511003', '660109511004', '660109511005', '660109511006', '660109516001', '660109516002', '660109517001', '660109517002', '660109518001', '660109519011', '660109519012', '660109519013', '660109519014', '660109519021', '660109519022', '660109519023', '660109519024', '660109522001', '660109522002', '660109522003', '660109522004', '660109523001', '660109523002', '660109523003', '660109524001', '660109524002', '660109527001', '660109527002', '660109527003', '660109527004', '660109527005', '660109529001', '660109529002', '660109529003', '660109529004', '660109529005', '660109529006', '660109530001', '660109530002', '660109530003', '660109530004', '660109530005', '660109531011', '660109531012', '660109531013', '660109531021', '660109531022', '660109531023', '660109532001', '660109532002', '660109532003', '660109533001', '660109533002', '660109533003', '660109533004', '660109534001', '660109534002', '660109535001', '660109536001', '660109536002', '660109536003', '660109536004', '660109536005', '660109539001', '660109539002', '660109539003', '660109539004', '660109540001', '660109540002', '660109543001', '660109543002', '660109544001', '660109544003', '660109544004', '660109544006', '660109544007', '660109545001', '660109545002', '660109545003', '660109545004', '660109547001', '660109547002', '660109547003', '660109548001', '660109548002', '660109548003', '660109548004', '660109551001', '660109551002', '660109551003', '660109551004', '660109552001', '660109552002', '660109552003', '660109553001', '660109553002', '660109554001', '660109556001', '660109556002', '660109557001', '660109557003', '660109557004', '660109557005', '660109557006', '660109558001', '660109558002', '660109558003', '660109558004', '660109558005', '660109558006', '660109558007', '660109558008', '660109558009', '660109559001', '660109559002', '660109559003', '660109560001', '660109560002', '660109561001', '660109561002', '660109561004', '660109562001', '660109562002', '660109562003', '660109562004', '660109562005', '660109563004', '660109563005', '660109801001', '660109804001', '660109900000', '691009501001', '691009501002', '691009501003', '691009900000', '691100001001', '691100001002', '691100002001', '691100002002', '691100003001', '691100003002', '691100004001', '691100004002', '691100005001', '691100005002', '691100006001', '691100006002', '691100006003', '691100007001', '691100007002', '691100007003', '691100008001', '691100008002', '691100009001', '691100009002', '691100009003', '691100010001', '691100010002', '691100011001', '691100012001', '691100012002', '691100013001', '691100013002', '691100013003', '691100014001', '691100014002', '691100014003', '691100015001', '691100015002', '691100015003', '691100015004', '691100015005', '691100016001', '691100016002', '691100017002', '691100017003', '691100017004', '691109900000', '691209501011', '691209501012', '691209501013', '691209502001', '691209502002', '780109701001', '780109701002', '780109702001', '780109702002', '780109703001', '780109703002', '780109703003', '780109704001', '780109704002', '780109704003', '780109704004', '780109705001', '780109705002', '780109705003', '780109706001', '780109706002', '780109706003', '780109706004', '780109706005', '780109707001', '780109707002', '780109707003', '780109708001', '780109708002', '780109709001', '780109710001', '780109710002', '780109711001', '780109711002', '780109711003', '780109711004', '780109712001', '780109712002', '780109712003', '780109712004', '780109713001', '780109713002', '780109713003', '780109714001', '780109715001', '780109715002', '780109715003', '780109900000', '780209501001', '780209501002', '780209501003', '780209502001', '780209502002', '780209502003', '780209502004', '780209900000', '780309601001', '780309601002', '780309601003', '780309602001', '780309602002', '780309602003', '780309603001', '780309603002', '780309603003', '780309604001', '780309604002', '780309604003', '780309604004', '780309605001', '780309605002', '780309605003', '780309605004', '780309605005', '780309606001', '780309606002', '780309606003', '780309607001', '780309607002', '780309607003', '780309608001', '780309608002', '780309609001', '780309609002', '780309610001', '780309610002', '780309610003', '780309610004', '780309610005', '780309611001', '780309611002', '780309612001', '780309612002', '780309900000']

FIPS only in ACS but NOT in SafeGraph:, 173 ['060159900000', '060379800201', '060759804011', '061110036121', '080149801001', '080149802001', '080149803001', '090079901000', '120179900000', '120299900000', '120379900000', '120519900000', '120579901000', '120659900000', '120759900000', '120839800001', '120839801001', '120859901000', '120879801001', '121239900000', '121299900000', '130399900000', '131799900000', '131919900000', '150019900000', '150019901000', '150019903000', '150019904000', '150019905000', '150019906000', '150019907000', '150019909000', '150019910000', '150019911000', '150019912000', '150019914000', '150019916000', '150019917000', '150039812001', '150059900000', '150070412002', '150079902000', '150079903000', '150099912000', '160439701002', '180890110001', '210670039161', '230059900000', '230299900000', '260039900000', '260119900000', '260139901000', '260199900000', '260299900000', '260339900000', '260339901000', '260419901000', '260539900000', '260619900000', '260619901000', '260899900000', '260959900000', '261039900000', '261279900000', '261479900000', '261579900000', '280459900000', '325109900000', '340297225000', '340297310020', '340297340020', '340297360010', '350010047421', '350439403001', '360039402001', '360050002000', '360050019000', '360050024000', '360050110000', '360050115020', '360050319000', '360050516005', '360119902000', '360470050000', '360470054000', '360470174000', '360470286000', '360470616000', '360599902000', '360599903020', '360610009002', '360610159000', '360610191000', '360610199000', '360610223020', '360639401001', '360810916020', '360810922000', '360810928000', '360810934010', '360810942010', '360810964000', '360810981000', '360810987000', '360810992000', '360811008010', '360850070000', '360850074000', '360850081000', '360850112020', '360850128050', '360850128060', '360850223003', '360850228000', '361190056001', '370159604000', '370299501020', '370319902000', '370419301010', '370531104020', '370559703000', '370559705010', '370559706020', '370879801001', '370959901000', '371379901000', '371399607020', '371439202020', '410199900000', '410459400001', '450539901000', '450899708021', '480579900000', '480719900000', '482459900000', '482619900000', '482739900000', '484899900000', '510019902000', '511039901000', '511199901000', '517359901000', '530050109011', '530319900000', '530619901000', '550039900000', '550079900000', '550299900000', '550319900000', '550519900000', '550839900000', '720119900000', '720159915000', '720179900000', '720279900000', '720519900210', '720539901030', '720559900000', '720599900010', '720759900010', '720799911000', '720899900010', '720919900250', '720959900000', '721039900130', '721099900000', '721139930000', '721159900000', '721199927000', '721279900000', '721459900000', '721479900000', '721519900000']

Removed devices only in 379 SafeGraph FIPS: 30328 devices.

Removed these 173 block groups, 1275 people.

Before merge ACS data row count: 2643116

After merge ACS data row count:  2639192

ACS columns:
Index(['state_fips', 'county_fips', 'tract_fips', 'fips', 'state',
       'totalpopulation', 'male', 'female', 'under5years', '5to9years',
       '10to14years', '15to17years', '18to24years', '25to34years',
       '35to44years', '45to54years', '55to64years', '65to74years',
       '75to84years', '85yearsandover', 'whitealone',
       'blackorafricanamericanalone', 'americanindianandalaskanativealone',
       'asianalone', 'nativehawaiianandotherpacificislanderalone',
       'someotherracealone', 'twoormoreraces', 'Hispanic_or_Latino',
       'population25yearsandover',
       'population25yearsandoverlessthanhighschool',
       'population25yearsandoverhighschoolgraduateincludesequivalency',
       'population25yearsandoversomecollege',
       'population25yearsandoverbachelorsdegree',
       'population25yearsandovermastersdegree',
       'population25yearsandoverprofessionalschooldegree',
       'population25yearsandoverdoctoratedegree', 'households',
       'householdslessthan10000', 'households10000to14999',
       'households15000to19999', 'households20000to24999',
       'households25000to29999', 'households30000to34999',
       'households35000to39999', 'households40000to44999',
       'households45000to49999', 'households50000to59999',
       'households60000to74999', 'households75000to99999',
       'households100000to124999', 'households125000to149999',
       'households150000to199999', 'households200000ormore', 'Female', 'Male',
       '<15', '15–17', '18–24', '25–34', '35–44', '45–54', '55–64', '>65',
       'White', 'Black', 'Hispanic', 'Asian', 'NoSchool', 'HighSchool',
       'NoCollege', 'Bachelor', 'Graduate', 'household_size', '<20K',
       '20K–30K', '30K–50K', '50K–100K', '>100K', 'cbg_fips', 'nation_fips'],
      dtype='object')
Use the US population 327939105 for the naion level bias:

C:\Users\N\AppData\Local\Temp\ipykernel_10560\2597773154.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df.loc[:, 'state_fips'] = residing_df['state_fips'].astype(str).str.zfill(2)
C:\Users\N\AppData\Local\Temp\ipykernel_10560\2597773154.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df['date_range_start'] = residing_df['date_range_start'].astype(str).str[:10]   # have an issue of different starting hours
100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [00:08<00:00,  1.49it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 624/624 [00:21<00:00, 28.88it/s]
100%|████████████████████████████████████████████████████████████████████████████| 38640/38640 [18:55<00:00, 34.04it/s]

2018
US population: 326228729, male, female: 165692916 160597055

FIPS count in SafeGraph：220601, in ACS: 220333

FIPS only in SafeGraph but NOT in ACS:, 390 ['0CA:24450148', '0CA:24680061', '600109501001', '600109501002', '600109502001', '600109502002', '600109503001', '600109503002', '600109503003', '600109505001', '600109505002', '600109505003', '600109506001', '600109506002', '600109506003', '600109507001', '600109507002', '600109507003', '600109509001', '600109509002', '600109509003', '600109509004', '600209518001', '600509510001', '600509510002', '600509511001', '600509511002', '600509511003', '600509512011', '600509512012', '600509512021', '600509512022', '600509512031', '600509512032', '600509512033', '600509513001', '600509513002', '600509515001', '600509516001', '600509516002', '600509516003', '600509516004', '660109501001', '660109501002', '660109501003', '660109501004', '660109501005', '660109502003', '660109502004', '660109502005', '660109503001', '660109503002', '660109503003', '660109503004', '660109503006', '660109503007', '660109503009', '660109504011', '660109504012', '660109504013', '660109504014', '660109504015', '660109504016', '660109504021', '660109504022', '660109504023', '660109505011', '660109505012', '660109505021', '660109505022', '660109505023', '660109505024', '660109505025', '660109507011', '660109507012', '660109507013', '660109507014', '660109507015', '660109507016', '660109507017', '660109507021', '660109507022', '660109507023', '660109507024', '660109507025', '660109508011', '660109508012', '660109508013', '660109508014', '660109508021', '660109508022', '660109508023', '660109508024', '660109509001', '660109509002', '660109509003', '660109509004', '660109509005', '660109509006', '660109509007', '660109510001', '660109510002', '660109510003', '660109510004', '660109510005', '660109510006', '660109510007', '660109510008', '660109511001', '660109511002', '660109511003', '660109511004', '660109511005', '660109511006', '660109516001', '660109516002', '660109517001', '660109517002', '660109518001', '660109519011', '660109519012', '660109519013', '660109519014', '660109519021', '660109519022', '660109519023', '660109519024', '660109522001', '660109522002', '660109522003', '660109522004', '660109523001', '660109523002', '660109523003', '660109524001', '660109524002', '660109527001', '660109527002', '660109527003', '660109527004', '660109527005', '660109528001', '660109528002', '660109529001', '660109529002', '660109529003', '660109529004', '660109529005', '660109529006', '660109530001', '660109530002', '660109530003', '660109530004', '660109530005', '660109531011', '660109531012', '660109531013', '660109531021', '660109531022', '660109531023', '660109532001', '660109532002', '660109532003', '660109533001', '660109533002', '660109533003', '660109533004', '660109534001', '660109534002', '660109535001', '660109536001', '660109536002', '660109536003', '660109536004', '660109536005', '660109539001', '660109539002', '660109539003', '660109539004', '660109540001', '660109540002', '660109543001', '660109543002', '660109544001', '660109544002', '660109544003', '660109544006', '660109544007', '660109545001', '660109545002', '660109545003', '660109545004', '660109545005', '660109547001', '660109547002', '660109547003', '660109548001', '660109548002', '660109548003', '660109548004', '660109551001', '660109551002', '660109551003', '660109551004', '660109552001', '660109552002', '660109552003', '660109553001', '660109553002', '660109554001', '660109556001', '660109556002', '660109557001', '660109557002', '660109557003', '660109557004', '660109557005', '660109557006', '660109557007', '660109558001', '660109558002', '660109558003', '660109558004', '660109558005', '660109558006', '660109558007', '660109558008', '660109558009', '660109559001', '660109559002', '660109559003', '660109560001', '660109560002', '660109561001', '660109561002', '660109561004', '660109562001', '660109562002', '660109562003', '660109562004', '660109562005', '660109562006', '660109563001', '660109563003', '660109563004', '660109563005', '660109801001', '660109804001', '660109900000', '691009501001', '691009501002', '691009501003', '691100001001', '691100001002', '691100002001', '691100002002', '691100003001', '691100003002', '691100004001', '691100004002', '691100005001', '691100005002', '691100006001', '691100006002', '691100006003', '691100007001', '691100007002', '691100007003', '691100008001', '691100008002', '691100009001', '691100009002', '691100009003', '691100010001', '691100010002', '691100011001', '691100012001', '691100012002', '691100013001', '691100013002', '691100013003', '691100014001', '691100014002', '691100014003', '691100015001', '691100015002', '691100015003', '691100015004', '691100015005', '691100016001', '691100016002', '691100017001', '691100017002', '691100017003', '691100017004', '691109900000', '691209501011', '691209501012', '691209501013', '691209502001', '691209502002', '780109701001', '780109701002', '780109702001', '780109702002', '780109703001', '780109703002', '780109703003', '780109704001', '780109704002', '780109704003', '780109704004', '780109705001', '780109705002', '780109705003', '780109706001', '780109706002', '780109706003', '780109706004', '780109706005', '780109707001', '780109707002', '780109707003', '780109708001', '780109708002', '780109709001', '780109710001', '780109710002', '780109711001', '780109711002', '780109711003', '780109711004', '780109712001', '780109712002', '780109712003', '780109712004', '780109713001', '780109713002', '780109713003', '780109714001', '780109715001', '780109715002', '780109715003', '780109900000', '780209501001', '780209501002', '780209501003', '780209502001', '780209502002', '780209502003', '780209502004', '780209900000', '780309601001', '780309601002', '780309601003', '780309602001', '780309602002', '780309602003', '780309603001', '780309603002', '780309603003', '780309604001', '780309604002', '780309604003', '780309604004', '780309605001', '780309605002', '780309605003', '780309605004', '780309605005', '780309606001', '780309606002', '780309606003', '780309607001', '780309607002', '780309607003', '780309608001', '780309608002', '780309609001', '780309609002', '780309610001', '780309610002', '780309610003', '780309610004', '780309610005', '780309611001', '780309611002', '780309612001', '780309612002', '780309900000']

FIPS only in ACS but NOT in SafeGraph:, 122 ['060159900000', '060374300033', '080149803001', '120519900000', '120659900000', '120839800001', '120839801001', '120879801001', '121239900000', '131799900000', '131919900000', '150019901000', '150019904000', '150019905000', '150019906000', '150019910000', '150019911000', '150019912000', '150019915000', '150019916000', '150039812001', '150059900000', '150070412002', '150079902000', '150079903000', '150099900000', '150099912000', '160439701002', '230099900000', '230299900000', '250056171015', '250179800001', '260099900000', '260119901000', '260139901000', '260199900000', '260419900000', '260539900000', '260619900000', '260619901000', '260839901000', '260959900000', '261479900000', '261539900000', '320319901000', '340297225000', '340297310020', '340297380010', '350010047421', '350439403001', '360039402001', '360050024000', '360050028000', '360050115020', '360050319000', '360050516005', '360119902000', '360470054000', '360470174000', '360470176000', '360470280000', '360470286000', '360470292000', '360470294000', '360470702031', '360599903020', '360639401001', '360739900000', '360810916020', '360810922000', '360810928000', '360810942030', '360810964000', '360810972020', '360811113000', '360850112020', '360850128040', '360850128060', '360850223003', '360850244010', '361190056001', '370319902000', '370559706020', '370899801001', '371379901000', '371399607020', '371439202020', '371779601000', '390959900000', '410199900000', '410459400001', '480579900000', '480719900000', '482459900000', '482619900000', '482739900000', '484899900000', '510019902000', '511039901000', '511199901000', '511959312003', '517359901000', '530319900000', '550039900000', '550079900000', '550299900000', '550319900000', '550519900000', '720039900000', '720119900000', '720159915000', '720179900000', '720279900000', '720499905010', '720539901030', '720599900010', '720799911000', '720899900010', '721099900000', '721159900000', '721339900000', '721519900000']

Removed devices only in 390 SafeGraph FIPS: 44911 devices.

Removed these 122 block groups, 272 people.

Before merge ACS data row count: 2643603

After merge ACS data row count:  2639497

ACS columns:
Index(['state_fips', 'county_fips', 'tract_fips', 'fips', 'state',
       'totalpopulation', 'male', 'female', 'under5years', '5to9years',
       '10to14years', '15to17years', '18to24years', '25to34years',
       '35to44years', '45to54years', '55to64years', '65to74years',
       '75to84years', '85yearsandover', 'whitealone',
       'blackorafricanamericanalone', 'americanindianandalaskanativealone',
       'asianalone', 'nativehawaiianandotherpacificislanderalone',
       'someotherracealone', 'twoormoreraces', 'Hispanic_or_Latino',
       'population25yearsandover',
       'population25yearsandoverlessthanhighschool',
       'population25yearsandoverhighschoolgraduateincludesequivalency',
       'population25yearsandoversomecollege',
       'population25yearsandoverbachelorsdegree',
       'population25yearsandovermastersdegree',
       'population25yearsandoverprofessionalschooldegree',
       'population25yearsandoverdoctoratedegree', 'households',
       'householdslessthan10000', 'households10000to14999',
       'households15000to19999', 'households20000to24999',
       'households25000to29999', 'households30000to34999',
       'households35000to39999', 'households40000to44999',
       'households45000to49999', 'households50000to59999',
       'households60000to74999', 'households75000to99999',
       'households100000to124999', 'households125000to149999',
       'households150000to199999', 'households200000ormore', 'Female', 'Male',
       '<15', '15–17', '18–24', '25–34', '35–44', '45–54', '55–64', '>65',
       'White', 'Black', 'Hispanic', 'Asian', 'NoSchool', 'HighSchool',
       'NoCollege', 'Bachelor', 'Graduate', 'household_size', '<20K',
       '20K–30K', '30K–50K', '50K–100K', '>100K', 'cbg_fips', 'nation_fips'],
      dtype='object')
Use the US population 326228729 for the naion level bias:

C:\Users\N\AppData\Local\Temp\ipykernel_10560\2597773154.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df.loc[:, 'state_fips'] = residing_df['state_fips'].astype(str).str.zfill(2)
C:\Users\N\AppData\Local\Temp\ipykernel_10560\2597773154.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  residing_df['date_range_start'] = residing_df['date_range_start'].astype(str).str[:10]   # have an issue of different starting hours
100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [00:07<00:00,  1.58it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 624/624 [00:21<00:00, 29.09it/s]
100%|████████████████████████████████████████████████████████████████████████████| 38628/38628 [18:41<00:00, 34.44it/s]

# Compute device sampling rate

# Tools

## Merge monthly home panel CSV files

In [113]:
import os
import pandas as pd



def get_all_files(data_dir, exts=['.csv'], verbose=True):
    all_files = []
    for root_dir, folders, files in os.walk(data_dir):
        # print(root_dir)
        for f in files:
            for ext in exts:
                ext_len = len(ext)
                if ext == f[-ext_len:]:
                    full_name = os.path.join(root_dir, f)
                    all_files.append(full_name)
                    
    if verbose:
        print("Found files:", len(all_files))
    return sorted(all_files)


# csv_files.pop(9)  # Error when downlaoding: 'L:\\SafeGraph_monthly_patterns_2018-2022\\2022\\09\\06\\SAFEGRAPH\\MP\\home_panel_summary.csv',  
# csv_files.pop(11)   # identical to 11-01:  'L:\\SafeGraph_monthly_patterns_2018-2022\\2022\\11\\22\\SAFEGRAPH\\MP\\home_panel_summary.csv',


# YEAR = 2018

years = [2018, 2019, 2020, 2021, 2022]
# years = [2022]

for year in years:
    
    data_dir = fr'L:\SafeGraph_monthly_patterns_2018-2022\{year}'
    
    csv_files = get_all_files(data_dir, exts=['home_panel_summary.csv'])

    
    print("Year:", year)

    df_list = []
    for f in csv_files:
        sep = '\\'  # path separate for windows 
        first_day = f.split(sep)[-4]
        if first_day != '01':
            print("Not first day data, skipped:", f)
            continue
        df = pd.read_csv(f)
        df_list.append(df)

    all_df = pd.concat(df_list)
    print("row count:", len(all_df))
    all_df.to_csv(fr'L:\SafeGraph_monthly_patterns_2018-2022\\{year}\US_monthly_home_panel_summary_{year}.csv', index=False)
all_df

Found files: 12
Year: 2018

C:\Users\N\AppData\Local\Temp\ipykernel_26404\416220133.py:47: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
C:\Users\N\AppData\Local\Temp\ipykernel_26404\416220133.py:47: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
C:\Users\N\AppData\Local\Temp\ipykernel_26404\416220133.py:47: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
C:\Users\N\AppData\Local\Temp\ipykernel_26404\416220133.py:47: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
C:\Users\N\AppData\Local\Temp\ipykernel_26404\416220133.py:47: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
C:\Users\N\AppData\Local\Temp\ipykernel_26404\416220133.py:47: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
C:\Users\N\AppData\Local\Temp\ipykernel_26404\416220133.py:47: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)

row count: 2643603
Found files: 12
Year: 2019

C:\Users\N\AppData\Local\Temp\ipykernel_26404\416220133.py:47: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
C:\Users\N\AppData\Local\Temp\ipykernel_26404\416220133.py:47: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)

row count: 2643116
Found files: 12
Year: 2020
row count: 2643048
Found files: 12
Year: 2021

C:\Users\N\AppData\Local\Temp\ipykernel_26404\416220133.py:47: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)

row count: 2640227
Found files: 13
Year: 2022

C:\Users\N\AppData\Local\Temp\ipykernel_26404\416220133.py:47: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
C:\Users\N\AppData\Local\Temp\ipykernel_26404\416220133.py:47: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
C:\Users\N\AppData\Local\Temp\ipykernel_26404\416220133.py:47: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
C:\Users\N\AppData\Local\Temp\ipykernel_26404\416220133.py:47: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
C:\Users\N\AppData\Local\Temp\ipykernel_26404\416220133.py:47: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)

Not first day data, skipped: L:\SafeGraph_monthly_patterns_2018-2022\2022\11\22\SAFEGRAPH\MP\home_panel_summary.csv
row count: 2644588

,year,month,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime
0,2022,1,ak,US,20200002021,211,91
1,2022,1,ak,US,21300002001,142,95
2,2022,1,ak,US,20200015003,25,32
3,2022,1,ak,US,20900010002,74,70
4,2022,1,ak,US,20900019003,39,13
...,...,...,...,...,...,...,...
220203,2022,12,wy,US,560419753002,66,70
220204,2022,12,wy,US,560019636003,12,10
220205,2022,12,wy,US,560210015013,48,40
220206,2022,12,wy,US,560250011002,124,96
220207,2022,12,wy,US,560379709011,119,105

## Weekly

In [435]:
# weekly residing files
weekly_residing_all_df = pd.read_csv(r'J:\weekly_patterns_20211211\Panel_overview_data\WeeklyPattern\weekly_home_panel_summary.csv', dtype={'census_block_group':str})
# weekly_residing_df = weekly_residing_df.merge(sociala_variable_df, left_on='census_block_group', right_on='fips')
weekly_residing_all_df['census_block_group'] = weekly_residing_all_df['census_block_group'].str.zfill(12)
weekly_residing_all_df = weekly_residing_all_df.sort_values(['date_range_start', 'date_range_end'])
weekly_residing_all_df

,date_range_start,date_range_end,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime
54709667,2018-01-01T00:00:00+10:00,2018-01-08T00:00:00+10:00,gu,US,660109544001,5,5
54709668,2018-01-01T00:00:00+10:00,2018-01-08T00:00:00+10:00,gu,US,660109507022,5,4
54709669,2018-01-01T00:00:00+10:00,2018-01-08T00:00:00+10:00,gu,US,660109507023,14,12
54709670,2018-01-01T00:00:00+10:00,2018-01-08T00:00:00+10:00,gu,US,660109510002,4,4
54709671,2018-01-01T00:00:00+10:00,2018-01-08T00:00:00+10:00,gu,US,660109529003,3,3
...,...,...,...,...,...,...,...
16235,2021-12-27T00:00:00-10:00,2022-01-03T00:00:00-10:00,hi,US,150090311031,41,37
59971,2021-12-27T00:00:00-10:00,2022-01-03T00:00:00-10:00,ak,US,020160001001,34,22
65799,2021-12-27T00:00:00-11:00,2022-01-03T00:00:00-11:00,as,US,600109506002,5,6
65800,2021-12-27T00:00:00-11:00,2022-01-03T00:00:00-11:00,as,US,600109509002,1,0
65801,2021-12-27T00:00:00-11:00,2022-01-03T00:00:00-11:00,as,US,600509516004,1,0

In [1]:
YEAR = '2018'
if YEAR > "2019":
    acs_year = '2019'
else:
    acs_year = YEAR
acs_year

'2018'

In [475]:
social_variable_df = pd.read_csv(fr'F:\USC_OneDrive\OneDrive - University of South Carolina\Research\Safegraph_bias\cbg_acs_{acs_year}_county_tract.csv', dtype={'fips':str})
social_variable_df['fips'] = social_variable_df['fips'].astype(str).str.zfill(12)
social_variable_df.columns
print("US population, male, female:")
social_variable_df['totalpopulation'].sum(), social_variable_df['male'].sum(), social_variable_df['female'].sum(), len(social_variable_df)

US population, male, female:

(327939105, 161465237, 166551005, 220333)

In [476]:
weekly_residing_year_df = weekly_residing_all_df[weekly_residing_all_df["date_range_start"].str.startswith(YEAR)]
weekly_residing_merged_df = weekly_residing_year_df.merge(social_variable_df, left_on='census_block_group', right_on='fips')
weekly_residing_merged_df

,date_range_start,date_range_end,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime,state_fips,county_fips,tract_fips,fips,state,totalpopulation,male,female,under5years,5to9years,10to14years,15to17years,18to24years,25to34years,35to44years,45to54years,55to64years,65to74years,75to84years,85yearsandover,whitealone,blackorafricanamericanalone,americanindianandalaskanativealone,asianalone,nativehawaiianandotherpacificislanderalone,someotherracealone,twoormoreraces,Hispanic_or_Latino,population25yearsandover,population25yearsandoverlessthanhighschool,population25yearsandoverhighschoolgraduateincludesequivalency,population25yearsandoversomecollege,population25yearsandoverbachelorsdegree,population25yearsandovermastersdegree,population25yearsandoverprofessionalschooldegree,population25yearsandoverdoctoratedegree,households,householdslessthan10000,households10000to14999,households15000to19999,households20000to24999,households25000to29999,households30000to34999,households35000to39999,households40000to44999,households45000to49999,households50000to59999,households60000to74999,households75000to99999,households100000to124999,households125000to149999,households150000to199999,households200000ormore
0,2021-01-04T00:00:00-04:00,2021-01-11T00:00:00-04:00,pr,US,720678204002,2,4,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0
1,2021-01-11T00:00:00-04:00,2021-01-18T00:00:00-04:00,pr,US,720678204002,2,4,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0
2,2021-01-18T00:00:00-04:00,2021-01-25T00:00:00-04:00,pr,US,720678204002,0,2,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0
3,2021-01-25T00:00:00-04:00,2021-02-01T00:00:00-04:00,pr,US,720678204002,0,1,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0
4,2021-02-01T00:00:00-04:00,2021-02-08T00:00:00-04:00,pr,US,720678204002,1,0,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11630225,2021-12-27T00:00:00-05:00,2022-01-03T00:00:00-05:00,mi,US,260139901000,1,0,26,26013,26013990100,260139901000,mi,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11630226,2021-12-27T00:00:00-05:00,2022-01-03T00:00:00-05:00,ny,US,360470164000,1,0,36,36047,36047016400,360470164000,ny,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11630227,2021-12-27T00:00:00-05:00,2022-01-03T00:00:00-05:00,wi,US,550039900000,1,0,55,55003,55003990000,550039900000,wi,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11630228,2021-12-27T00:00:00-06:00,2022-01-03T00:00:00-06:00,la,US,220879900000,1,0,22,22087,22087990000,220879900000,la,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11630229,2021-12-27T00:00:00-10:00,2022-01-03T00:00:00-10:00,hi,US,150099900000,1,0,15,15009,15009990000,150099900000,hi,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [477]:
weekly_residing_merged_df['date_range_start'] = weekly_residing_merged_df['date_range_start'].astype(str).str[:10]
weekly_residing_merged_df['state_fips'] = weekly_residing_merged_df['state_fips'].astype(str).str.zfill(2)
weekly_residing_merged_df['county_fips'] = weekly_residing_merged_df['county_fips'].astype(str).str.zfill(5)
weekly_residing_merged_df['tract_fips'] = weekly_residing_merged_df['tract_fips'].astype(str).str.zfill(11)
weekly_residing_merged_df['year'] =  weekly_residing_merged_df['date_range_start'].astype(str).str[:4]
weekly_residing_merged_df.rename(columns={'fips':'cbg_fips'}, inplace=True)
weekly_residing_merged_df

,date_range_start,date_range_end,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime,state_fips,county_fips,tract_fips,cbg_fips,state,totalpopulation,male,female,under5years,5to9years,10to14years,15to17years,18to24years,25to34years,35to44years,45to54years,55to64years,65to74years,75to84years,85yearsandover,whitealone,blackorafricanamericanalone,americanindianandalaskanativealone,asianalone,nativehawaiianandotherpacificislanderalone,someotherracealone,twoormoreraces,Hispanic_or_Latino,population25yearsandover,population25yearsandoverlessthanhighschool,population25yearsandoverhighschoolgraduateincludesequivalency,population25yearsandoversomecollege,population25yearsandoverbachelorsdegree,population25yearsandovermastersdegree,population25yearsandoverprofessionalschooldegree,population25yearsandoverdoctoratedegree,households,householdslessthan10000,households10000to14999,households15000to19999,households20000to24999,households25000to29999,households30000to34999,households35000to39999,households40000to44999,households45000to49999,households50000to59999,households60000to74999,households75000to99999,households100000to124999,households125000to149999,households150000to199999,households200000ormore,year
0,2021-01-04,2021-01-11T00:00:00-04:00,pr,US,720678204002,2,4,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0,2021
1,2021-01-11,2021-01-18T00:00:00-04:00,pr,US,720678204002,2,4,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0,2021
2,2021-01-18,2021-01-25T00:00:00-04:00,pr,US,720678204002,0,2,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0,2021
3,2021-01-25,2021-02-01T00:00:00-04:00,pr,US,720678204002,0,1,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0,2021
4,2021-02-01,2021-02-08T00:00:00-04:00,pr,US,720678204002,1,0,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11630225,2021-12-27,2022-01-03T00:00:00-05:00,mi,US,260139901000,1,0,26,26013,26013990100,260139901000,mi,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021
11630226,2021-12-27,2022-01-03T00:00:00-05:00,ny,US,360470164000,1,0,36,36047,36047016400,360470164000,ny,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021
11630227,2021-12-27,2022-01-03T00:00:00-05:00,wi,US,550039900000,1,0,55,55003,55003990000,550039900000,wi,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021
11630228,2021-12-27,2022-01-03T00:00:00-06:00,la,US,220879900000,1,0,22,22087,22087990000,220879900000,la,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021
11630229,2021-12-27,2022-01-03T00:00:00-10:00,hi,US,150099900000,1,0,15,15009,15009990000,150099900000,hi,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021

In [478]:
df = weekly_residing_merged_df[weekly_residing_merged_df["date_range_start"].str.startswith(YEAR)].query("region == 'sc'")
df

,date_range_start,date_range_end,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime,state_fips,county_fips,tract_fips,cbg_fips,state,totalpopulation,male,female,under5years,5to9years,10to14years,15to17years,18to24years,25to34years,35to44years,45to54years,55to64years,65to74years,75to84years,85yearsandover,whitealone,blackorafricanamericanalone,americanindianandalaskanativealone,asianalone,nativehawaiianandotherpacificislanderalone,someotherracealone,twoormoreraces,Hispanic_or_Latino,population25yearsandover,population25yearsandoverlessthanhighschool,population25yearsandoverhighschoolgraduateincludesequivalency,population25yearsandoversomecollege,population25yearsandoverbachelorsdegree,population25yearsandovermastersdegree,population25yearsandoverprofessionalschooldegree,population25yearsandoverdoctoratedegree,households,householdslessthan10000,households10000to14999,households15000to19999,households20000to24999,households25000to29999,households30000to34999,households35000to39999,households40000to44999,households45000to49999,households50000to59999,households60000to74999,households75000to99999,households100000to124999,households125000to149999,households150000to199999,households200000ormore,year
150859,2021-01-04,2021-01-11T00:00:00-05:00,sc,US,450410003004,87,67,45,45041,45041000300,450410003004,sc,1866,829,1037,127,91,127,70,127,127,127,127,127,127,103,11,387,127,0,21,0,0,0,0,1156,127,301,127,127,46,4,3,580,67,11,51,34,21,16,47,29,10,70,108,60,39,11,4,2,2021
150860,2021-01-11,2021-01-18T00:00:00-05:00,sc,US,450410003004,83,67,45,45041,45041000300,450410003004,sc,1866,829,1037,127,91,127,70,127,127,127,127,127,127,103,11,387,127,0,21,0,0,0,0,1156,127,301,127,127,46,4,3,580,67,11,51,34,21,16,47,29,10,70,108,60,39,11,4,2,2021
150861,2021-01-18,2021-01-25T00:00:00-05:00,sc,US,450410003004,81,62,45,45041,45041000300,450410003004,sc,1866,829,1037,127,91,127,70,127,127,127,127,127,127,103,11,387,127,0,21,0,0,0,0,1156,127,301,127,127,46,4,3,580,67,11,51,34,21,16,47,29,10,70,108,60,39,11,4,2,2021
150862,2021-01-25,2021-02-01T00:00:00-05:00,sc,US,450410003004,83,65,45,45041,45041000300,450410003004,sc,1866,829,1037,127,91,127,70,127,127,127,127,127,127,103,11,387,127,0,21,0,0,0,0,1156,127,301,127,127,46,4,3,580,67,11,51,34,21,16,47,29,10,70,108,60,39,11,4,2,2021
150863,2021-02-01,2021-02-08T00:00:00-05:00,sc,US,450410003004,86,69,45,45041,45041000300,450410003004,sc,1866,829,1037,127,91,127,70,127,127,127,127,127,127,103,11,387,127,0,21,0,0,0,0,1156,127,301,127,127,46,4,3,580,67,11,51,34,21,16,47,29,10,70,108,60,39,11,4,2,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11630108,2021-10-18,2021-10-25T00:00:00-04:00,sc,US,450899708021,0,1,45,45089,45089970802,450899708021,sc,1266,1266,0,0,0,0,0,58,127,127,127,98,0,0,0,317,127,27,0,0,96,74,299,1208,127,473,127,37,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021
11630109,2021-10-25,2021-11-01T00:00:00-04:00,sc,US,450899708021,0,1,45,45089,45089970802,450899708021,sc,1266,1266,0,0,0,0,0,58,127,127,127,98,0,0,0,317,127,27,0,0,96,74,299,1208,127,473,127,37,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021
11630110,2021-11-01,2021-11-08T00:00:00-05:00,sc,US,450899708021,0,1,45,45089,45089970802,450899708021,sc,1266,1266,0,0,0,0,0,58,127,127,127,98,0,0,0,317,127,27,0,0,96,74,299,1208,127,473,127,37,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021
11630111,2021-11-08,2021-11-15T00:00:00-05:00,sc,US,450899708021,0,1,45,45089,45089970802,450899708021,sc,1266,1266,0,0,0,0,0,58,127,127,127,98,0,0,0,317,127,27,0,0,96,74,299,1208,127,473,127,37,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021
11630112,2021-12-27,2022-01-03T00:00:00-05:00,sc,US,450899708021,0,1,45,45089,45089970802,450899708021,sc,1266,1266,0,0,0,0,0,58,127,127,127,98,0,0,0,317,127,27,0,0,96,74,299,1208,127,473,127,37,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021

In [479]:
import numpy as np
def get_sampling_rate(residing_df, aggre_columns):
    # residing_df['date_range_start'] = residing_df['date_range_start'].astype(str).str[:10]
    aggre_columns = ['date_range_start'] + aggre_columns
    
    sampling_rate_df = residing_df.groupby(aggre_columns).agg(
                                      
                                      start_date=('date_range_start', 'first'), 
                                      end_date=('date_range_start', 'last'), 
                                      # period_count=('CBG_count', 'count'), 
                                      CBG_count=('totalpopulation', 'count'), 
                                      fips=(aggre_columns[-1], 'first'), 
                                      device_count=('number_devices_residing', 'sum'), 
                                      population=('totalpopulation', 'sum'), 
                                      year=('year', 'first'),
                                      aggre_column=(aggre_columns[-1], 'first'), 
                                      # safegraph_ratio_max=('safegraph_ratio', max),
                                      # census_ratio=('census_ratio', 'mean'),
                                      # census_ratio_max=('census_ratio', max),
                                      # census_ratio_min=('census_ratio', min),
                                     )
    
    sampling_rate_df['sampling_rate'] = sampling_rate_df['device_count'] / sampling_rate_df['population']
    sampling_rate_df.replace([np.inf], np.nan, inplace=True)

    return sampling_rate_df.reset_index().iloc[:, 2:]


def save_df(df, save_name):
    
    print("Saved.")
    

def compute_sampling_rates(df, aggre_columns = ['state_fips', 'county_fips', 'tract_fips', 'cbg_fips']):
    df_list = []
    for c in aggre_columns:
        sampling_rate_df = get_sampling_rate(df, aggre_columns=[c])
        df_list.append(sampling_rate_df)
        
    df_all = pd.concat(df_list)
    
    return df_all

df_all = compute_sampling_rates(weekly_residing_merged_df, aggre_columns = ['state_fips', 'county_fips', 'tract_fips', 'cbg_fips'])
# df_all = compute_sampling_rates(df,                        aggre_columns = ['state_fips', 'county_fips', 'tract_fips', 'cbg_fips'])

df_all['fips_len'] = df_all['fips'].astype(str).str.len()
df_all['fips_level'] = df_all['fips_len'].astype(str)
df_all['fips_level'] = df_all['fips_level'].replace({'2':"state", '5':"county", '11': 'tract', '12':'cbg'})

df_all.to_csv(fr'P:\Shared drives\NJIT_T5\safegraph_bias\sampling_rates_{YEAR}.csv', index=False)
df_all

,start_date,end_date,CBG_count,fips,device_count,population,year,aggre_column,sampling_rate,fips_len,fips_level
0,2021-01-04,2021-01-04,3438,01,394059,4876250,2021,01,0.080812,2,state
1,2021-01-04,2021-01-04,528,02,22125,733893,2021,02,0.030147,2,state
2,2021-01-04,2021-01-04,4177,04,313834,7050299,2021,04,0.044514,2,state
3,2021-01-04,2021-01-04,2147,05,217957,2999370,2021,05,0.072668,2,state
4,2021-01-04,2021-01-04,23192,06,1311949,39272874,2021,06,0.033406,2,state
...,...,...,...,...,...,...,...,...,...,...,...
11410434,2021-12-27,2021-12-27,1,721537505032,2,981,2021,721537505032,0.002039,12,cbg
11410435,2021-12-27,2021-12-27,1,721537506011,2,883,2021,721537506011,0.002265,12,cbg
11410436,2021-12-27,2021-12-27,1,721537506012,7,2523,2021,721537506012,0.002774,12,cbg
11410437,2021-12-27,2021-12-27,1,721537506013,8,991,2021,721537506013,0.008073,12,cbg
11410438,2021-12-27,2021-12-27,1,721537506021,3,1577,2021,721537506021,0.001902,12,cbg

In [480]:
df_all['sampling_rate'].mean(), df_all['sampling_rate'].max(), df_all['sampling_rate'].min()

(0.0539842884694264, 362.5, 0.0)

In [481]:
def time_aggregate(sampling_rate_df):
    
    rate_gb_df = sampling_rate_df.groupby(['year', 'fips']).agg(
                                      start_date=('start_date', 'first'), 
                                      end_date=('end_date', 'last'), 
                                      period_count=('start_date', 'count'), 
                                      CBG_count=('CBG_count', 'mean'), 
                                      device_count_mean=('device_count', 'mean'), 
                                      population=('population', 'mean'), 
                                      sampling_rate_mean=('sampling_rate', 'mean'),
                                      sampling_rate_max=('sampling_rate', max),
                                      sampling_rate_min=('sampling_rate', min),        
                                     )
    
    return rate_gb_df
    
rate_gb_df = time_aggregate(df_all.iloc[:]).reset_index()
# rate_gb_df.to_csv(r'P:\Shared drives\NJIT_T5\safegraph_bias\sampling_rates_yearly.csv', index=False)
rate_gb_df['fips_len'] = rate_gb_df['fips'].astype(str).str.len()
rate_gb_df['fips_level'] = rate_gb_df['fips_len'].astype(str)
rate_gb_df['fips_level'] = rate_gb_df['fips_level'].replace({'2':"state", '5':"county", '11': 'tract', '12':'cbg'})

rate_gb_df.to_csv(fr'P:\Shared drives\NJIT_T5\safegraph_bias\sampling_rates_{YEAR}_yearly.csv', index=False)

rate_gb_df

,year,fips,start_date,end_date,period_count,CBG_count,device_count_mean,population,sampling_rate_mean,sampling_rate_max,sampling_rate_min,fips_len,fips_level
0,2021,01,2021-01-04,2021-12-27,52,3503.615385,408712.230769,4.970024e+06,0.081901,0.103577,0.075744,2,state
1,2021,01001,2021-01-04,2021-12-27,52,32.615385,5263.519231,5.644500e+04,0.092875,0.115312,0.085645,5,county
2,2021,01001020100,2021-01-04,2021-12-27,52,2.038462,242.365385,2.031327e+03,0.118482,0.176618,0.100351,11,tract
3,2021,010010201001,2021-01-04,2021-12-27,52,1.019231,111.423077,7.440385e+02,0.148209,0.275342,0.093151,12,cbg
4,2021,010010201002,2021-01-04,2021-12-27,52,1.019231,130.942308,1.287288e+03,0.101300,0.123515,0.091053,12,cbg
...,...,...,...,...,...,...,...,...,...,...,...,...,...
297408,2021,721537506012,2021-01-04,2021-12-27,49,1.020408,4.816327,2.574490e+03,0.001869,0.012287,0.000000,12,cbg
297409,2021,721537506013,2021-01-04,2021-12-27,50,1.020000,3.480000,1.010820e+03,0.003471,0.019173,0.000000,12,cbg
297410,2021,72153750602,2021-01-04,2021-12-27,45,1.488889,2.733333,1.831867e+03,0.001405,0.005393,0.000000,11,tract
297411,2021,721537506021,2021-01-04,2021-12-27,41,1.024390,1.951220,1.615463e+03,0.001206,0.005073,0.000000,12,cbg
297412,2021,721537506022,2021-01-04,2021-11-22,25,1.000000,1.720000,6.480000e+02,0.002654,0.009259,0.000000,12,cbg

In [482]:
rate_gb_df['sampling_rate_mean'].mean(), rate_gb_df['sampling_rate_mean'].max(), rate_gb_df['sampling_rate_mean'].min()

(0.05389302167150877, 151.57692307692307, 0.0)

In [483]:
stop

NameError: name 'stop' is not defined

## Monthly

In [3]:
# weekly residing files
residing_all_df = pd.read_csv(r'J:\monthly_patterns_20211211\Panel_overview_data\MonthlyPattern\monthly_home_panel_summary.csv', dtype={'census_block_group':str})
# weekly_residing_df = weekly_residing_df.merge(sociala_variable_df, left_on='census_block_group', right_on='fips')
residing_all_df['census_block_group'] = residing_all_df['census_block_group'].str.zfill(12)
residing_all_df['date_range_start'] = residing_all_df['year'].astype(str).str.zfill(4) + residing_all_df['month'].astype(str).str.zfill(2)
residing_all_df['date_range_end'] = residing_all_df['date_range_start'] 
residing_all_df = residing_all_df.sort_values(['date_range_start', 'date_range_end'])
residing_all_df['date_range_start'] = residing_all_df['year'].astype(str).str.zfill(4) + residing_all_df['month'].astype(str).str.zfill(2)
residing_all_df

,year,month,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime,date_range_start,date_range_end
10569887,2018,1,ak,US,021880001002,9,5,201801,201801
10569888,2018,1,ak,US,021700006011,118,103,201801,201801
10569889,2018,1,ak,US,021220010001,120,93,201801,201801
10569890,2018,1,ak,US,021220006002,45,34,201801,201801
10569891,2018,1,ak,US,020200015003,42,38,201801,201801
...,...,...,...,...,...,...,...,...,...
220201,2022,1,wy,US,560119502001,86,60,202201,202201
220202,2022,1,wy,US,560199552003,62,52,202201,202201
220203,2022,1,wy,US,560159580003,83,54,202201,202201
220204,2022,1,wy,US,560250006002,90,67,202201,202201
220205,2022,1,wy,US,560210005015,43,28,202201,202201

In [4]:
YEAR = '2021'

if YEAR > "2019":
    acs_year = '2019'
else:
    acs_year = YEAR

In [5]:
residing_df = residing_all_df[residing_all_df["date_range_start"].astype(str).str.startswith(str(YEAR))] 
residing_df['date_range_start']

2640135    202101
2640136    202101
2640137    202101
2640138    202101
2640139    202101
            ...
439951     202112
439952     202112
439953     202112
439954     202112
439955     202112
Name: date_range_start, Length: 2640227, dtype: object

In [530]:
social_variable_df = pd.read_csv(fr'F:\USC_OneDrive\OneDrive - University of South Carolina\Research\Safegraph_bias\cbg_acs_{acs_year}_county_tract.csv', dtype={'fips':str})
social_variable_df['fips'] = social_variable_df['fips'].astype(str).str.zfill(12)
social_variable_df.columns

print("acs_year, US population, male, female:")
acs_year, social_variable_df['totalpopulation'].sum(), social_variable_df['male'].sum(), social_variable_df['female'].sum(), len(social_variable_df)

acs_year, US population, male, female:

('2019', 327939105, 161465237, 166551005, 220333)

In [531]:
residing_merged_df = residing_df.merge(social_variable_df, left_on='census_block_group', right_on='fips')
residing_merged_df

,year,month,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime,date_range_start,date_range_end,state_fips,county_fips,tract_fips,fips,state,totalpopulation,male,female,under5years,5to9years,10to14years,15to17years,18to24years,25to34years,35to44years,45to54years,55to64years,65to74years,75to84years,85yearsandover,whitealone,blackorafricanamericanalone,americanindianandalaskanativealone,asianalone,nativehawaiianandotherpacificislanderalone,someotherracealone,twoormoreraces,Hispanic_or_Latino,population25yearsandover,population25yearsandoverlessthanhighschool,population25yearsandoverhighschoolgraduateincludesequivalency,population25yearsandoversomecollege,population25yearsandoverbachelorsdegree,population25yearsandovermastersdegree,population25yearsandoverprofessionalschooldegree,population25yearsandoverdoctoratedegree,households,householdslessthan10000,households10000to14999,households15000to19999,households20000to24999,households25000to29999,households30000to34999,households35000to39999,households40000to44999,households45000to49999,households50000to59999,households60000to74999,households75000to99999,households100000to124999,households125000to149999,households150000to199999,households200000ormore
0,2021,1,ak,US,022400001002,28,22,202101,202101,2,2240,2240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
1,2021,2,ak,US,022400001002,15,14,202102,202102,2,2240,2240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
2,2021,3,ak,US,022400001002,21,21,202103,202103,2,2240,2240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
3,2021,4,ak,US,022400001002,26,18,202104,202104,2,2240,2240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
4,2021,5,ak,US,022400001002,31,22,202105,202105,2,2240,2240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2637927,2021,12,nc,US,370899801001,1,1,202112,202112,37,37089,37089980100,370899801001,nc,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2637928,2021,12,nj,US,340297360010,1,0,202112,202112,34,34029,34029736001,340297360010,nj,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2637929,2021,12,ny,US,360850228000,1,0,202112,202112,36,36085,36085022800,360850228000,ny,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2637930,2021,12,ny,US,360850244010,1,0,202112,202112,36,36085,36085024401,360850244010,ny,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2637931,2021,12,pr,US,721439900000,0,1,202112,202112,72,72143,72143990000,721439900000,pr,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [532]:
residing_merged_df['date_range_start'] = residing_merged_df['date_range_start'].astype(str).str[:10]
residing_merged_df['state_fips'] = residing_merged_df['state_fips'].astype(str).str.zfill(2)
residing_merged_df['county_fips'] = residing_merged_df['county_fips'].astype(str).str.zfill(5)
residing_merged_df['tract_fips'] = residing_merged_df['tract_fips'].astype(str).str.zfill(11)
residing_merged_df['year'] =  residing_merged_df['date_range_start'].astype(str).str[:4]
residing_merged_df.rename(columns={'fips':'cbg_fips'}, inplace=True)
residing_merged_df

,year,month,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime,date_range_start,date_range_end,state_fips,county_fips,tract_fips,cbg_fips,state,totalpopulation,male,female,under5years,5to9years,10to14years,15to17years,18to24years,25to34years,35to44years,45to54years,55to64years,65to74years,75to84years,85yearsandover,whitealone,blackorafricanamericanalone,americanindianandalaskanativealone,asianalone,nativehawaiianandotherpacificislanderalone,someotherracealone,twoormoreraces,Hispanic_or_Latino,population25yearsandover,population25yearsandoverlessthanhighschool,population25yearsandoverhighschoolgraduateincludesequivalency,population25yearsandoversomecollege,population25yearsandoverbachelorsdegree,population25yearsandovermastersdegree,population25yearsandoverprofessionalschooldegree,population25yearsandoverdoctoratedegree,households,householdslessthan10000,households10000to14999,households15000to19999,households20000to24999,households25000to29999,households30000to34999,households35000to39999,households40000to44999,households45000to49999,households50000to59999,households60000to74999,households75000to99999,households100000to124999,households125000to149999,households150000to199999,households200000ormore
0,2021,1,ak,US,022400001002,28,22,202101,202101,02,02240,02240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
1,2021,2,ak,US,022400001002,15,14,202102,202102,02,02240,02240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
2,2021,3,ak,US,022400001002,21,21,202103,202103,02,02240,02240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
3,2021,4,ak,US,022400001002,26,18,202104,202104,02,02240,02240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
4,2021,5,ak,US,022400001002,31,22,202105,202105,02,02240,02240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2637927,2021,12,nc,US,370899801001,1,1,202112,202112,37,37089,37089980100,370899801001,nc,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2637928,2021,12,nj,US,340297360010,1,0,202112,202112,34,34029,34029736001,340297360010,nj,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2637929,2021,12,ny,US,360850228000,1,0,202112,202112,36,36085,36085022800,360850228000,ny,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2637930,2021,12,ny,US,360850244010,1,0,202112,202112,36,36085,36085024401,360850244010,ny,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2637931,2021,12,pr,US,721439900000,0,1,202112,202112,72,72143,72143990000,721439900000,pr,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [533]:
import numpy as np
def get_sampling_rate(residing_df, aggre_columns):
    # residing_df['date_range_start'] = residing_df['date_range_start'].astype(str).str[:10]
    aggre_columns = ['date_range_start'] + aggre_columns
    
    sampling_rate_df = residing_df.groupby(aggre_columns).agg(
                                      
                                      start_date=('date_range_start', 'first'), 
                                      end_date=('date_range_start', 'last'), 
                                      # period_count=('CBG_count', 'count'), 
                                      CBG_count=('totalpopulation', 'count'), 
                                      fips=(aggre_columns[-1], 'first'), 
                                      device_count=('number_devices_residing', 'sum'), 
                                      population=('totalpopulation', 'sum'), 
                                      year=('year', 'first'),
                                      aggre_column=(aggre_columns[-1], 'first'), 
                                      # safegraph_ratio_max=('safegraph_ratio', max),
                                      # census_ratio=('census_ratio', 'mean'),
                                      # census_ratio_max=('census_ratio', max),
                                      # census_ratio_min=('census_ratio', min),
                                     )
    
    sampling_rate_df['sampling_rate'] = sampling_rate_df['device_count'] / sampling_rate_df['population']
    sampling_rate_df.replace([np.inf], np.nan, inplace=True)

    return sampling_rate_df.reset_index().iloc[:, 2:]


def save_df(df, save_name):
    
    print("Saved.")
    

def compute_sampling_rates(df, aggre_columns = ['state_fips', 'county_fips', 'tract_fips', 'cbg_fips']):
    df_list = []
    for c in aggre_columns:
        sampling_rate_df = get_sampling_rate(df, aggre_columns=[c])
        df_list.append(sampling_rate_df)
        
    df_all = pd.concat(df_list)
    
    return df_all

df_all = compute_sampling_rates(residing_merged_df, aggre_columns = ['state_fips', 'county_fips', 'tract_fips', 'cbg_fips'])
# df_all = compute_sampling_rates(df,                        aggre_columns = ['state_fips', 'county_fips', 'tract_fips', 'cbg_fips'])

df_all['fips_len'] = df_all['fips'].astype(str).str.len()
df_all['fips_level'] = df_all['fips_len'].astype(str)
df_all['fips_level'] = df_all['fips_level'].replace({'2':"state", '5':"county", '11': 'tract', '12':'cbg'})

df_all.to_csv(fr'P:\Shared drives\NJIT_T5\safegraph_bias\sampling_rates_{YEAR}_monthly.csv', index=False)
df_all

,start_date,end_date,CBG_count,fips,device_count,population,year,aggre_column,sampling_rate,fips_len,fips_level
0,202101,202101,3438,01,475154,4876250,2021,01,0.097443,2,state
1,202101,202101,533,02,31213,737054,2021,02,0.042348,2,state
2,202101,202101,4177,04,427128,7050299,2021,04,0.060583,2,state
3,202101,202101,2147,05,266447,2999370,2021,05,0.088834,2,state
4,202101,202101,23199,06,1821738,39277401,2021,06,0.046381,2,state
...,...,...,...,...,...,...,...,...,...,...,...
2637927,202112,202112,1,721537505032,1,981,2021,721537505032,0.001019,12,cbg
2637928,202112,202112,1,721537506011,1,883,2021,721537506011,0.001133,12,cbg
2637929,202112,202112,1,721537506012,1,2523,2021,721537506012,0.000396,12,cbg
2637930,202112,202112,1,721537506013,2,991,2021,721537506013,0.002018,12,cbg
2637931,202112,202112,1,721537506021,0,1577,2021,721537506021,0.000000,12,cbg

In [534]:
df_all['sampling_rate'].mean(), df_all['sampling_rate'].max(), df_all['sampling_rate'].min()

(0.07502739634419049, 639.5, 0.0)

In [ ]:
def weighted_average(dataframe, value, weight):
    val = dataframe[value]
    wt = dataframe[weight]
    # print("wt.sum:", wt.sum())
    return (val * wt).sum() / wt.sum()

In [535]:
def time_aggregate(sampling_rate_df):
    
    rate_gb_df = sampling_rate_df.groupby(['year', 'fips']).agg(
                                      start_date=('start_date', 'first'), 
                                      end_date=('end_date', 'last'), 
                                      period_count=('start_date', 'count'), 
                                      CBG_count=('CBG_count', 'mean'), 
                                      device_count_mean=('device_count', 'mean'), 
                                      population=('population', 'mean'), 
                                      sampling_rate_mean=('sampling_rate', 'mean'),
                                      sampling_rate_max=('sampling_rate', max),
                                      sampling_rate_min=('sampling_rate', min),        
                                     )
    
    return rate_gb_df
    
rate_gb_df = time_aggregate(df_all.iloc[:]).reset_index()
# rate_gb_df.to_csv(r'P:\Shared drives\NJIT_T5\safegraph_bias\sampling_rates_yearly.csv', index=False)
rate_gb_df['fips_len'] = rate_gb_df['fips'].astype(str).str.len()
rate_gb_df['fips_level'] = rate_gb_df['fips_len'].astype(str)
rate_gb_df['fips_level'] = rate_gb_df['fips_level'].replace({'2':"state", '5':"county", '11': 'tract', '12':'cbg'})

rate_gb_df.to_csv(fr'P:\Shared drives\NJIT_T5\safegraph_bias\sampling_rates_{YEAR}_monthly_yearly.csv', index=False)

rate_gb_df

,year,fips,start_date,end_date,period_count,CBG_count,device_count_mean,population,sampling_rate_mean,sampling_rate_max,sampling_rate_min,fips_len,fips_level
0,2021,01,202101,202112,12,3437.750000,485747.166667,4876250.0,0.099615,0.116666,0.093924,2,state
1,2021,01001,202101,202112,12,32.000000,6097.916667,55380.0,0.110110,0.126761,0.104153,5,county
2,2021,01001020100,202101,202112,12,2.000000,349.916667,1993.0,0.175573,0.214250,0.147015,11,tract
3,2021,010010201001,202101,202112,12,1.000000,199.083333,730.0,0.272717,0.345205,0.197260,12,cbg
4,2021,010010201002,202101,202112,12,1.000000,150.833333,1263.0,0.119425,0.138559,0.111639,12,cbg
...,...,...,...,...,...,...,...,...,...,...,...,...,...
297357,2021,721537506012,202101,202112,12,1.000000,8.916667,2523.0,0.003534,0.013872,0.000396,12,cbg
297358,2021,721537506013,202101,202112,12,1.000000,6.416667,991.0,0.006475,0.023209,0.001009,12,cbg
297359,2021,72153750602,202101,202112,12,1.833333,4.583333,2117.0,0.002091,0.006292,0.000000,11,tract
297360,2021,721537506021,202101,202112,12,1.000000,2.666667,1577.0,0.001691,0.005073,0.000000,12,cbg
297361,2021,721537506022,202101,202111,10,1.000000,2.300000,648.0,0.003549,0.009259,0.001543,12,cbg

In [536]:
rate_gb_df['sampling_rate_mean'].mean(), rate_gb_df['sampling_rate_mean'].max(), rate_gb_df['sampling_rate_mean'].min()

(0.07498375601505249, 270.125, 0.0)

In [537]:
stop

NameError: name 'stop' is not defined

In [ ]:
df = pd.DataFrame(columns=['C1', 'C2', "C3"])
df["C1"] = [2, 2, 2, 1, 1, 1]
df["C2"] = ["a"] * 2 + ["b"] * 2 + ["c"] * 2
df["C3"] = range(6)

df = df.groupby(['C1', 'C2']).agg(C4=('C3', 'mean'),)

df.loc[:, :]

In [ ]:
df.loc[:, ['a', 'c'], :]

In [ ]:
bias_gb_df.index.get_level_values(1)
bias_gb_df.loc[:, ['male', 'female'], :]

In [ ]:
# SC_residing_df.sort_values('date_range_start')

In [ ]:
# weekly residing files
weekly_residing_df = pd.read_csv(r'J:\weekly_patterns_20211211\Panel_overview_data\WeeklyPattern\weekly_home_panel_summary.csv')
weekly_residing_df

In [ ]:
ACS_csv = r'H:\covid_mobility_results\new_census_data\ACS_2019_5YR_BG\ACS_race_cbsa_income_2019_county_decile.csv'

ACS_df = pd.read_csv(ACS_csv)


sociala_variable_df = pd.read_csv(r'F:\USC_OneDrive\OneDrive - University of South Carolina\Research\Mobility_covid\social_variables.csv')


sociala_variable_df
sociala_variable_df['GEOID'] = sociala_variable_df['GEOID'].str[-12:]

In [ ]:
# sociala_variable_df

In [ ]:
def text2GEOID(text):
    # for state, county, tract, blockgroup level only
    county_fips = ''
    tract_fips = ''
    blockgroup_fips = ''    
    state_fips = ''
    try:
        state_fips = text.split('state:')[1][:2]
        county_fips = text.split('county:')[1][:3]
        tract_fips = text.split('tract:')[1][:6]
        blockgroup_fips = text.split('block group:')[1][:1]
        
    except Exception as e:
        print("Error in text2GEOID()", e)
        pass
    
    return state_fips + county_fips + tract_fips + blockgroup_fips
                            
# make a test
text = r'Block Group 1, Census Tract 113, Coffee County, Alabama: Summary level: 150, state:01> county:031> tract:011300> block group:1'

len(text2GEOID(text))

In [ ]:
# B01001_026E: SEX BY AGE: Female: Total population -- (Estimate)

# B01001_001E: SEX BY AGE: Total: Total population -- (Estimate)

def get_census(state_fips=['45'], county_fips=[], blockgroup_fips=[], fields=['B01001_001E', 'B01001_026E']):  
    # unfinished
    
    df_list = []
    
    for state in state_fips:
        try:
            cookbg = censusdata.download('acs5', 2019,
                                         censusdata.censusgeo([('state', state), ('county', '*'), ('block group', '*')]),
                                         ['B01001_001E', 'B01001_026E'])

            index = [text2GEOID(str(t)) for t in cookbg.index]
            cookbg.index = index
            cookbg.index = cookbg.index.set_names(['FIPS'])
            cookbg = cookbg.reset_index()
            df_list.append(cookbg)
        except Exception as e:
            print("Error in get Census data in :", state, e)
            continue
        
    return pd.concat(df_list)

# make a test

cookbg = get_census(state_fips=['45'], county_fips=[], blockgroup_fips=[])
len(cookbg)

In [ ]:
cookbg['Female_ratio']#mean()

In [ ]:
# state_fips = list(states.mapping('fips', 'abbr').keys())[:-1] # the last one is none, drop it using [:-1].

# get data of SC
state_fips = ['45'] # the last one is none, drop it using [:-1]
cookbg = get_census(state_fips=state_fips, county_fips=[], blockgroup_fips=[])

cookbg['ratio_female'] = cookbg['B01001_026E'] / cookbg['B01001_001E']


len(cookbg), cookbg['ratio_female'].mean()

cookbg['ratio_female']

In [ ]:
cookbg = cookbg.merge(sociala_variable_df, left_on=['FIPS'], right_on=['GEOID'])

In [ ]:
SC_residing_df = weekly_residing_df[weekly_residing_df["date_range_start"].str.startswith('2019')].query("region == 'sc'")
SC_residing_df

In [ ]:
SC_residing_df = SC_residing_df.merge(cookbg, left_on='census_block_group', right_on='FIPS')
SC_residing_df = SC_residing_df.query('B01001_001E > 1').dropna()
SC_residing_df

In [ ]:
columns = [ 'ratio_white', 'ratio_black', 'ratio_hispanic', 'ratio_high_school', 'ratio_senior']
columns = ['ratio_female', 'ratio_white', 'ratio_black', 'ratio_hispanic', 'ratio_high_school', 'ratio_senior']


def get_bias(df):
    
    # columns = ['ratio_female', 'ratio_white', 'ratio_black', 'ratio_hispanic', 'ratio_high_school', 'ratio_senior']
    state_total_device = df['number_devices_residing'].sum()
    state_total_pop = df['popu_cbg'].sum()
    
    result_df = pd.DataFrame(columns = [ 'variable', 'start_date', 'census_ratio', 'safegraph_ratio'],
                   index = columns)
    
    for column in columns:
        start_date = df.iloc[0]['date_range_start'][:10] 
        cbg_column_devices = df['number_devices_residing'] * df[column]
        cbg_device_ratio = cbg_column_devices.sum() / state_total_device 

        cbg_column_pop = df[column] * df['popu_cbg']
        
        census_ratio = cbg_column_pop.sum() / state_total_pop
        safegraph_ratio = cbg_column_devices.sum() / state_total_device
        
        result_df.loc[column]['variable'] = column
        result_df.loc[column]['start_date'] = start_date
        result_df.loc[column]['census_ratio'] = census_ratio
        result_df.loc[column]['safegraph_ratio'] = safegraph_ratio
        
        
        # print(f"{safegraph_ratio:0.3f}, {census_ratio:.3f}")
    # print(result_df)
    return result_df
bias_df = SC_residing_df.groupby('date_range_start').apply(get_bias)
bias_df.reset_index(drop=True, inplace=True)

# bias_df = bias_df[columns]


bias_gb_df = bias_df.groupby(['variable']).agg(census_ratio_mean=('safegraph_ratio', 'mean'), 
                                  census_ratio_min=('safegraph_ratio', min), 
                                  census_ratio_max=('safegraph_ratio', max),
                                  census_ratio=('census_ratio', max),
                                 )

bias_gb_df = bias_gb_df.loc[columns]

bias_gb_df['census_ratio_mean_to_census'] = bias_gb_df['census_ratio_mean'] / bias_gb_df['census_ratio']
bias_gb_df['census_ratio_min_to_census'] = bias_gb_df['census_ratio_min'] / bias_gb_df['census_ratio']
bias_gb_df['census_ratio_max_to_census'] = bias_gb_df['census_ratio_max'] / bias_gb_df['census_ratio']

bias_gb_df.round(2)

In [ ]:
#

In [ ]:
bias_df.reset_index(drop=True, inplace=True)

In [ ]:
SC_residing_df.columns

In [ ]:
cookbg

In [ ]:


# cookbg

In [ ]:
CENSUS_KEY = 'b12026d61228a4b0d441ae7aa93f1ea222877503'

# two packages can be use: Census (need a Census key), Censusdata (no key needed)


from census import Census
from us import states

c = Census(CENSUS_KEY)
c.acs5.get(('NAME', 'B25034_010E'),
          {'for': 'state:{}'.format(states.MD.fips)})

In [ ]:
Census.ALL

In [ ]:
# c.sf1.state_county_blockgroup('NAME', states.AK.fips, '170', Census.ALL)