In [198]:
# ! pip install censusdata
# ! pip install census
# ! pip install us

In [1]:
import pandas as pd
import censusdata
import glob
import os
from tqdm import tqdm
# import matplotlib.pyplot as plt
import random
import geopandas as gpd
from datetime import datetime


# from matplotlib.font_manager import FontManager
# fm = FontManager()
# mat_fonts = set(f.name for f in fm.ttflist)
# print(mat_fonts)

import matplotlib.pyplot as plt

# plt.rcParams['font.sans-serif'] = ['DengXian']
plt.rcParams.update({'font.size': 16})
pd.set_option('display.max_columns', None)  # show all columns
pd.set_option("display.max_colwidth", 100)

# Using Zhenlong's data

In [370]:
# weekly residing files
weekly_residing_all_df = pd.read_csv(r'J:\weekly_patterns_20211211\Panel_overview_data\WeeklyPattern\weekly_home_panel_summary.csv', dtype={'census_block_group':str})
# weekly_residing_df = weekly_residing_df.merge(sociala_variable_df, left_on='census_block_group', right_on='fips')
weekly_residing_all_df['census_block_group'] = weekly_residing_all_df['census_block_group'].str.zfill(12)
weekly_residing_all_df = weekly_residing_all_df.sort_values(['date_range_start', 'date_range_end'])
weekly_residing_all_df

,date_range_start,date_range_end,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime
54709667,2018-01-01T00:00:00+10:00,2018-01-08T00:00:00+10:00,gu,US,660109544001,5,5
54709668,2018-01-01T00:00:00+10:00,2018-01-08T00:00:00+10:00,gu,US,660109507022,5,4
54709669,2018-01-01T00:00:00+10:00,2018-01-08T00:00:00+10:00,gu,US,660109507023,14,12
54709670,2018-01-01T00:00:00+10:00,2018-01-08T00:00:00+10:00,gu,US,660109510002,4,4
54709671,2018-01-01T00:00:00+10:00,2018-01-08T00:00:00+10:00,gu,US,660109529003,3,3
...,...,...,...,...,...,...,...
16235,2021-12-27T00:00:00-10:00,2022-01-03T00:00:00-10:00,hi,US,150090311031,41,37
59971,2021-12-27T00:00:00-10:00,2022-01-03T00:00:00-10:00,ak,US,020160001001,34,22
65799,2021-12-27T00:00:00-11:00,2022-01-03T00:00:00-11:00,as,US,600109506002,5,6
65800,2021-12-27T00:00:00-11:00,2022-01-03T00:00:00-11:00,as,US,600109509002,1,0
65801,2021-12-27T00:00:00-11:00,2022-01-03T00:00:00-11:00,as,US,600509516004,1,0

In [410]:
YEAR = '2021'

In [411]:
# ACS_csv = r'H:\covid_mobility_results\new_census_data\ACS_2019_5YR_BG\ACS_race_cbsa_income_2019_county_decile.csv'
# ACS_df = pd.read_csv(ACS_csv)
if YEAR > "2019":
    acs_year = 2019
else:
    acs_year = YEAR
social_variable_df = pd.read_csv(fr'F:\USC_OneDrive\OneDrive - University of South Carolina\Research\Safegraph_bias\cbg_acs_{acs_year}_county_tract.csv', dtype={'fips':str})
social_variable_df['fips'] = social_variable_df['fips'].astype(str).str.zfill(12)
social_variable_df.columns
print("US population, male, female:")
social_variable_df['totalpopulation'].sum(), social_variable_df['male'].sum(), social_variable_df['female'].sum(), len(social_variable_df)

US population, male, female:

(327939105, 161465237, 166551005, 220333)

In [412]:
weekly_residing_df = weekly_residing_all_df[weekly_residing_all_df["date_range_start"].str.startswith(YEAR)].drop_duplicates()
weekly_residing_df

,date_range_start,date_range_end,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime
14181433,2021-01-04T00:00:00+10:00,2021-01-11T00:00:00+10:00,mp,US,691100009002,1,1
14287938,2021-01-04T00:00:00+10:00,2021-01-11T00:00:00+10:00,gu,US,660109544001,4,12
14287939,2021-01-04T00:00:00+10:00,2021-01-11T00:00:00+10:00,gu,US,660109507022,6,5
14287940,2021-01-04T00:00:00+10:00,2021-01-11T00:00:00+10:00,gu,US,660109507023,29,25
14287941,2021-01-04T00:00:00+10:00,2021-01-11T00:00:00+10:00,gu,US,660109510002,4,3
...,...,...,...,...,...,...,...
16235,2021-12-27T00:00:00-10:00,2022-01-03T00:00:00-10:00,hi,US,150090311031,41,37
59971,2021-12-27T00:00:00-10:00,2022-01-03T00:00:00-10:00,ak,US,020160001001,34,22
65799,2021-12-27T00:00:00-11:00,2022-01-03T00:00:00-11:00,as,US,600109506002,5,6
65800,2021-12-27T00:00:00-11:00,2022-01-03T00:00:00-11:00,as,US,600109509002,1,0
65801,2021-12-27T00:00:00-11:00,2022-01-03T00:00:00-11:00,as,US,600509516004,1,0

In [413]:
weekly_residing_merged_df = weekly_residing_df.merge(social_variable_df, left_on='census_block_group', right_on='fips')
weekly_residing_merged_df

,date_range_start,date_range_end,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime,state_fips,county_fips,tract_fips,fips,state,totalpopulation,male,female,under5years,5to9years,10to14years,15to17years,18to24years,25to34years,35to44years,45to54years,55to64years,65to74years,75to84years,85yearsandover,whitealone,blackorafricanamericanalone,americanindianandalaskanativealone,asianalone,nativehawaiianandotherpacificislanderalone,someotherracealone,twoormoreraces,Hispanic_or_Latino,population25yearsandover,population25yearsandoverlessthanhighschool,population25yearsandoverhighschoolgraduateincludesequivalency,population25yearsandoversomecollege,population25yearsandoverbachelorsdegree,population25yearsandovermastersdegree,population25yearsandoverprofessionalschooldegree,population25yearsandoverdoctoratedegree,households,householdslessthan10000,households10000to14999,households15000to19999,households20000to24999,households25000to29999,households30000to34999,households35000to39999,households40000to44999,households45000to49999,households50000to59999,households60000to74999,households75000to99999,households100000to124999,households125000to149999,households150000to199999,households200000ormore
0,2021-01-04T00:00:00-04:00,2021-01-11T00:00:00-04:00,pr,US,720678204002,2,4,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0
1,2021-01-11T00:00:00-04:00,2021-01-18T00:00:00-04:00,pr,US,720678204002,2,4,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0
2,2021-01-18T00:00:00-04:00,2021-01-25T00:00:00-04:00,pr,US,720678204002,0,2,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0
3,2021-01-25T00:00:00-04:00,2021-02-01T00:00:00-04:00,pr,US,720678204002,0,1,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0
4,2021-02-01T00:00:00-04:00,2021-02-08T00:00:00-04:00,pr,US,720678204002,1,0,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11410452,2021-12-27T00:00:00-05:00,2022-01-03T00:00:00-05:00,mi,US,260139901000,1,0,26,26013,26013990100,260139901000,mi,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11410453,2021-12-27T00:00:00-05:00,2022-01-03T00:00:00-05:00,ny,US,360470164000,1,0,36,36047,36047016400,360470164000,ny,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11410454,2021-12-27T00:00:00-05:00,2022-01-03T00:00:00-05:00,wi,US,550039900000,1,0,55,55003,55003990000,550039900000,wi,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11410455,2021-12-27T00:00:00-06:00,2022-01-03T00:00:00-06:00,la,US,220879900000,1,0,22,22087,22087990000,220879900000,la,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11410456,2021-12-27T00:00:00-10:00,2022-01-03T00:00:00-10:00,hi,US,150099900000,1,0,15,15009,15009990000,150099900000,hi,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [414]:
social_variable_df.columns

Index(['state_fips', 'county_fips', 'tract_fips', 'fips', 'state',
       'totalpopulation', 'male', 'female', 'under5years', '5to9years',
       '10to14years', '15to17years', '18to24years', '25to34years',
       '35to44years', '45to54years', '55to64years', '65to74years',
       '75to84years', '85yearsandover', 'whitealone',
       'blackorafricanamericanalone', 'americanindianandalaskanativealone',
       'asianalone', 'nativehawaiianandotherpacificislanderalone',
       'someotherracealone', 'twoormoreraces', 'Hispanic_or_Latino',
       'population25yearsandover',
       'population25yearsandoverlessthanhighschool',
       'population25yearsandoverhighschoolgraduateincludesequivalency',
       'population25yearsandoversomecollege',
       'population25yearsandoverbachelorsdegree',
       'population25yearsandovermastersdegree',
       'population25yearsandoverprofessionalschooldegree',
       'population25yearsandoverdoctoratedegree', 'households',
       'householdslessthan10000', 'households10000to14999',
       'households15000to19999', 'households20000to24999',
       'households25000to29999', 'households30000to34999',
       'households35000to39999', 'households40000to44999',
       'households45000to49999', 'households50000to59999',
       'households60000to74999', 'households75000to99999',
       'households100000to124999', 'households125000to149999',
       'households150000to199999', 'households200000ormore'],
      dtype='object')

In [415]:
weekly_residing_merged_df['Female'] = weekly_residing_merged_df['female'] / weekly_residing_merged_df['totalpopulation']
weekly_residing_merged_df['Male'] = weekly_residing_merged_df['male'] / weekly_residing_merged_df['totalpopulation']
weekly_residing_merged_df['<15'] = (weekly_residing_merged_df['under5years'] + weekly_residing_merged_df['5to9years'] + \
                                    weekly_residing_merged_df['10to14years']) / weekly_residing_merged_df['totalpopulation'] 

weekly_residing_merged_df['15â€“17'] = (weekly_residing_merged_df['15to17years']) / weekly_residing_merged_df['totalpopulation'] # weekly_residing_merged_df['under5years'] + weekly_residing_merged_df['5to9years'] + \                                     weekly_residing_merged_df['10to14years'] + 
                                    
weekly_residing_merged_df['18â€“24'] = weekly_residing_merged_df['18to24years'] / weekly_residing_merged_df['totalpopulation']
weekly_residing_merged_df['25â€“34'] = weekly_residing_merged_df['25to34years'] / weekly_residing_merged_df['totalpopulation'] 
weekly_residing_merged_df['35â€“44'] = weekly_residing_merged_df['35to44years'] / weekly_residing_merged_df['totalpopulation'] 
weekly_residing_merged_df['45â€“54'] = weekly_residing_merged_df['45to54years'] / weekly_residing_merged_df['totalpopulation'] 
weekly_residing_merged_df['55â€“64'] = weekly_residing_merged_df['55to64years'] / weekly_residing_merged_df['totalpopulation'] 
weekly_residing_merged_df['>65'] = (weekly_residing_merged_df['65to74years'] + weekly_residing_merged_df['65to74years'] + weekly_residing_merged_df['75to84years'] \
                                       + weekly_residing_merged_df['85yearsandover']) / weekly_residing_merged_df['totalpopulation']

weekly_residing_merged_df['White'] = weekly_residing_merged_df['whitealone'] / weekly_residing_merged_df['totalpopulation'] 
weekly_residing_merged_df['Black'] = weekly_residing_merged_df['blackorafricanamericanalone'] / weekly_residing_merged_df['totalpopulation'] 
weekly_residing_merged_df['Hispanic'] = weekly_residing_merged_df['Hispanic_or_Latino'] / weekly_residing_merged_df['totalpopulation'] 
weekly_residing_merged_df['Asian'] = weekly_residing_merged_df['asianalone'] / weekly_residing_merged_df['totalpopulation']
# Hispanic/Latino
weekly_residing_merged_df['NoSchool'] = weekly_residing_merged_df['population25yearsandoverlessthanhighschool'] / weekly_residing_merged_df['population25yearsandover'] 
weekly_residing_merged_df['HighSchool'] = weekly_residing_merged_df['population25yearsandoverhighschoolgraduateincludesequivalency'] / weekly_residing_merged_df['population25yearsandover'] 
weekly_residing_merged_df['NoCollege'] = (weekly_residing_merged_df['population25yearsandoverlessthanhighschool'] + \
                                            weekly_residing_merged_df['population25yearsandoverhighschoolgraduateincludesequivalency']) \
                                            / weekly_residing_merged_df['population25yearsandover'] 

weekly_residing_merged_df['Bachelor'] = weekly_residing_merged_df['population25yearsandoverbachelorsdegree'] / weekly_residing_merged_df['population25yearsandover'] 
weekly_residing_merged_df['Graduate'] = (weekly_residing_merged_df['population25yearsandovermastersdegree'] + weekly_residing_merged_df['population25yearsandovermastersdegree'] + \
                                               weekly_residing_merged_df['population25yearsandoverdoctoratedegree']) / weekly_residing_merged_df['population25yearsandover']

weekly_residing_merged_df['<20K'] = (weekly_residing_merged_df['householdslessthan10000'] + weekly_residing_merged_df['households10000to14999'] + \
                                               weekly_residing_merged_df['households15000to19999']) / weekly_residing_merged_df['households']   
weekly_residing_merged_df['20Kâ€“30K'] = (weekly_residing_merged_df['households20000to24999'] + weekly_residing_merged_df['households25000to29999']) / weekly_residing_merged_df['households']  
weekly_residing_merged_df['30Kâ€“50K'] = (weekly_residing_merged_df['households30000to34999'] + weekly_residing_merged_df['households35000to39999'] + \
                                       weekly_residing_merged_df['households40000to44999'] + weekly_residing_merged_df['households45000to49999']) / weekly_residing_merged_df['households']
weekly_residing_merged_df['50Kâ€“100K'] = (weekly_residing_merged_df['households50000to59999'] + weekly_residing_merged_df['households60000to74999'] + \
                                        weekly_residing_merged_df['households75000to99999']) / weekly_residing_merged_df['households']

weekly_residing_merged_df['>100K'] = (weekly_residing_merged_df['households100000to124999'] + weekly_residing_merged_df['households125000to149999'] + \
                                        weekly_residing_merged_df['households150000to199999'] + weekly_residing_merged_df['households200000ormore']) / weekly_residing_merged_df['households']

weekly_residing_merged_df['county_fips'] = weekly_residing_merged_df['county_fips'].astype(str).str.zfill(5)
weekly_residing_merged_df['fips'] = weekly_residing_merged_df['fips'].astype(str).str.zfill(12)
weekly_residing_merged_df['state_fips'] = weekly_residing_merged_df['state_fips'].astype(str).str.zfill(2)
weekly_residing_merged_df['tract_fips'] = weekly_residing_merged_df['state_fips'].astype(str).str.zfill(11)




weekly_residing_merged_df.iloc[:, -24:]

,Female,Male,<15,15â€“17,18â€“24,25â€“34,35â€“44,45â€“54,55â€“64,>65,White,Black,Hispanic,Asian,NoSchool,HighSchool,NoCollege,Bachelor,Graduate,<20K,20Kâ€“30K,30Kâ€“50K,50Kâ€“100K,>100K
0,0.524854,0.475146,0.078947,0.0,0.084795,0.105263,0.080409,0.097953,0.185673,0.51462,0.27193,0.111111,1.0,0.0,0.222028,0.291958,0.513986,0.085664,0.020979,0.673684,0.182456,0.038596,0.105263,0.0
1,0.524854,0.475146,0.078947,0.0,0.084795,0.105263,0.080409,0.097953,0.185673,0.51462,0.27193,0.111111,1.0,0.0,0.222028,0.291958,0.513986,0.085664,0.020979,0.673684,0.182456,0.038596,0.105263,0.0
2,0.524854,0.475146,0.078947,0.0,0.084795,0.105263,0.080409,0.097953,0.185673,0.51462,0.27193,0.111111,1.0,0.0,0.222028,0.291958,0.513986,0.085664,0.020979,0.673684,0.182456,0.038596,0.105263,0.0
3,0.524854,0.475146,0.078947,0.0,0.084795,0.105263,0.080409,0.097953,0.185673,0.51462,0.27193,0.111111,1.0,0.0,0.222028,0.291958,0.513986,0.085664,0.020979,0.673684,0.182456,0.038596,0.105263,0.0
4,0.524854,0.475146,0.078947,0.0,0.084795,0.105263,0.080409,0.097953,0.185673,0.51462,0.27193,0.111111,1.0,0.0,0.222028,0.291958,0.513986,0.085664,0.020979,0.673684,0.182456,0.038596,0.105263,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11410452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11410453,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11410454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11410455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11410456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [416]:
weekly_residing_merged_df['Female'].mean(), weekly_residing_merged_df['Asian'].mean(), weekly_residing_merged_df['White'].mean(), weekly_residing_merged_df['Black'].mean(), weekly_residing_merged_df['Hispanic'].mean(), weekly_residing_merged_df['50Kâ€“100K'].mean()

(0.5090249992497189,
 0.025577215843366245,
 0.7298296374715236,
 0.04837302120036851,
 0.1701182668920919,
 0.2830750618914996)

In [417]:
weekly_residing_merged_df.sample(10).iloc[:, -5:].sum(axis=1)

10631878    1.000000
1322509     1.000000
7523240     1.000000
2912625     0.844262
2927326     1.000000
2781626     0.982927
4356511     1.000000
3752621     0.831703
10518119    1.000000
198545      1.000000
dtype: float64

In [418]:
weekly_residing_merged_df.iloc[:, -24:].sample(10)

,Female,Male,<15,15â€“17,18â€“24,25â€“34,35â€“44,45â€“54,55â€“64,>65,White,Black,Hispanic,Asian,NoSchool,HighSchool,NoCollege,Bachelor,Graduate,<20K,20Kâ€“30K,30Kâ€“50K,50Kâ€“100K,>100K
9682167,0.487296,0.512704,0.180581,0.049002,0.064428,0.031760,0.089837,0.115245,0.115245,0.301270,0.867514,0.000000,0.015426,0.112523,0.017995,0.080977,0.098972,0.163239,0.353470,0.028571,0.033333,0.083333,0.111905,0.545238
11102385,0.550154,0.449846,0.204475,0.054784,0.047840,0.097994,0.097994,0.063272,0.097994,0.218364,0.855710,0.013117,0.439043,0.008488,0.040314,0.213886,0.254199,0.142217,0.088466,0.099115,0.051327,0.330973,0.414159,0.104425
2306749,0.487741,0.512259,0.163748,0.030648,0.051664,0.111208,0.111208,0.111208,0.107706,0.248687,0.932574,0.000000,0.063047,0.006130,0.116144,0.217189,0.333333,0.147503,0.160279,0.089130,0.110870,0.054348,0.432609,0.313043
2006255,0.547340,0.452660,0.223625,0.021641,0.071235,0.114518,0.101894,0.114518,0.109107,0.230839,0.884581,0.027953,0.032462,0.000000,0.068966,0.298408,0.367374,0.127321,0.071618,0.055710,0.044568,0.158774,0.470752,0.270195
7649200,0.534750,0.465250,0.154509,0.016657,0.072947,0.072947,0.072947,0.068352,0.072947,0.184951,0.617461,0.072947,0.000000,0.072947,0.096386,0.155766,0.252151,0.109294,0.245267,0.063920,0.085227,0.022727,0.440341,0.338068
2436020,0.513934,0.486066,0.155738,0.013115,0.049180,0.095902,0.104098,0.072131,0.104098,0.317213,0.925410,0.063115,0.011475,0.000000,0.061845,0.296646,0.358491,0.133124,0.100629,0.000000,0.038560,0.061697,0.347044,0.552699
10943601,0.481307,0.518693,0.127768,0.031579,0.046098,0.046098,0.046098,0.046098,0.046098,0.177132,0.388385,0.005808,0.144102,0.046098,0.032274,0.252323,0.284597,0.062103,0.138875,0.034924,0.038417,0.107101,0.210710,0.406286
44542,0.550986,0.449014,0.138901,0.053294,0.049937,0.053294,0.053294,0.053294,0.053294,0.144775,1.000000,0.000000,1.000000,0.000000,0.085407,0.264291,0.349697,0.085407,0.195024,0.303065,0.059024,0.165721,0.167991,0.046538
8178150,0.485075,0.514925,0.216418,0.055970,0.052239,0.035448,0.118470,0.118470,0.053172,0.354478,0.958955,0.000000,0.055037,0.006530,0.013812,0.165746,0.179558,0.175414,0.276243,0.106754,0.076253,0.102397,0.366013,0.348584
1148641,0.459984,0.540016,0.128982,0.005439,0.049340,0.049340,0.049340,0.049340,0.049340,0.197358,0.831002,0.009713,0.021756,0.049340,0.020202,0.115364,0.135566,0.067517,0.167464,0.066138,0.050265,0.175485,0.308642,0.297178

In [419]:
weekly_residing_merged_df.iloc[:, -20:].columns

Index(['18â€“24', '25â€“34', '35â€“44', '45â€“54', '55â€“64', '>65', 'White', 'Black',
       'Hispanic', 'Asian', 'NoSchool', 'HighSchool', 'NoCollege', 'Bachelor',
       'Graduate', '<20K', '20Kâ€“30K', '30Kâ€“50K', '50Kâ€“100K', '>100K'],
      dtype='object')

In [420]:
weekly_residing_merged_df

,date_range_start,date_range_end,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime,state_fips,county_fips,tract_fips,fips,state,totalpopulation,male,female,under5years,5to9years,10to14years,15to17years,18to24years,25to34years,35to44years,45to54years,55to64years,65to74years,75to84years,85yearsandover,whitealone,blackorafricanamericanalone,americanindianandalaskanativealone,asianalone,nativehawaiianandotherpacificislanderalone,someotherracealone,twoormoreraces,Hispanic_or_Latino,population25yearsandover,population25yearsandoverlessthanhighschool,population25yearsandoverhighschoolgraduateincludesequivalency,population25yearsandoversomecollege,population25yearsandoverbachelorsdegree,population25yearsandovermastersdegree,population25yearsandoverprofessionalschooldegree,population25yearsandoverdoctoratedegree,households,householdslessthan10000,households10000to14999,households15000to19999,households20000to24999,households25000to29999,households30000to34999,households35000to39999,households40000to44999,households45000to49999,households50000to59999,households60000to74999,households75000to99999,households100000to124999,households125000to149999,households150000to199999,households200000ormore,Female,Male,<15,15â€“17,18â€“24,25â€“34,35â€“44,45â€“54,55â€“64,>65,White,Black,Hispanic,Asian,NoSchool,HighSchool,NoCollege,Bachelor,Graduate,<20K,20Kâ€“30K,30Kâ€“50K,50Kâ€“100K,>100K
0,2021-01-04T00:00:00-04:00,2021-01-11T00:00:00-04:00,pr,US,720678204002,2,4,72,72067,00000000072,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0,0.524854,0.475146,0.078947,0.0,0.084795,0.105263,0.080409,0.097953,0.185673,0.51462,0.27193,0.111111,1.0,0.0,0.222028,0.291958,0.513986,0.085664,0.020979,0.673684,0.182456,0.038596,0.105263,0.0
1,2021-01-11T00:00:00-04:00,2021-01-18T00:00:00-04:00,pr,US,720678204002,2,4,72,72067,00000000072,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0,0.524854,0.475146,0.078947,0.0,0.084795,0.105263,0.080409,0.097953,0.185673,0.51462,0.27193,0.111111,1.0,0.0,0.222028,0.291958,0.513986,0.085664,0.020979,0.673684,0.182456,0.038596,0.105263,0.0
2,2021-01-18T00:00:00-04:00,2021-01-25T00:00:00-04:00,pr,US,720678204002,0,2,72,72067,00000000072,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0,0.524854,0.475146,0.078947,0.0,0.084795,0.105263,0.080409,0.097953,0.185673,0.51462,0.27193,0.111111,1.0,0.0,0.222028,0.291958,0.513986,0.085664,0.020979,0.673684,0.182456,0.038596,0.105263,0.0
3,2021-01-25T00:00:00-04:00,2021-02-01T00:00:00-04:00,pr,US,720678204002,0,1,72,72067,00000000072,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0,0.524854,0.475146,0.078947,0.0,0.084795,0.105263,0.080409,0.097953,0.185673,0.51462,0.27193,0.111111,1.0,0.0,0.222028,0.291958,0.513986,0.085664,0.020979,0.673684,0.182456,0.038596,0.105263,0.0
4,2021-02-01T00:00:00-04:00,2021-02-08T00:00:00-04:00,pr,US,720678204002,1,0,72,72067,00000000072,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0,0.524854,0.475146,0.078947,0.0,0.084795,0.105263,0.080409,0.097953,0.185673,0.51462,0.27193,0.111111,1.0,0.0,0.222028,0.291958,0.513986,0.085664,0.020979,0.673684,0.182456,0.038596,0.105263,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11410452,2021-12-27T00:00:00-05:00,2022-01-03T00:00:00-05:00,mi,US,260139901000,1,0,26,26013,00000000026,260139901000,mi,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11410453,2021-12-27T00:00:00-05:00,2022-01-03T00:00:00-05:00,ny,US,360470164000,1,0,36,36047,00000000036,360470164000,ny,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11410454,2021-12-27T00:00:00-05:00,2022-01-03T00:00:00-05:00,wi,US,550039900000,1,0,55,55003,00000000055,550039900000,wi,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11410455,2021-12-27T00:00:00-06:00,2022-01-03T00:00:00-06:00,la,US,220879900000,1,0,22,22087,00000000022,220879900000,la,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11410456,2021-12-27T00:00:00-10:00,2022-01-03T00:00:00-10:00,hi,US,150099900000,1,0,15,15009,00000000015,150099900000,hi,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [421]:
# Use SC data as a small development dataset for quick feedback
SC_residing_df = weekly_residing_merged_df[weekly_residing_merged_df["date_range_start"].str.startswith(YEAR)].query("region == 'sc'")
# SC_residing_df = weekly_residing_merged_df[weekly_residing_merged_df["date_range_start"].str.startswith('2019')].query("region == 'al'")

In [422]:
SC_residing_df

,date_range_start,date_range_end,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime,state_fips,county_fips,tract_fips,fips,state,totalpopulation,male,female,under5years,5to9years,10to14years,15to17years,18to24years,25to34years,35to44years,45to54years,55to64years,65to74years,75to84years,85yearsandover,whitealone,blackorafricanamericanalone,americanindianandalaskanativealone,asianalone,nativehawaiianandotherpacificislanderalone,someotherracealone,twoormoreraces,Hispanic_or_Latino,population25yearsandover,population25yearsandoverlessthanhighschool,population25yearsandoverhighschoolgraduateincludesequivalency,population25yearsandoversomecollege,population25yearsandoverbachelorsdegree,population25yearsandovermastersdegree,population25yearsandoverprofessionalschooldegree,population25yearsandoverdoctoratedegree,households,householdslessthan10000,households10000to14999,households15000to19999,households20000to24999,households25000to29999,households30000to34999,households35000to39999,households40000to44999,households45000to49999,households50000to59999,households60000to74999,households75000to99999,households100000to124999,households125000to149999,households150000to199999,households200000ormore,Female,Male,<15,15â€“17,18â€“24,25â€“34,35â€“44,45â€“54,55â€“64,>65,White,Black,Hispanic,Asian,NoSchool,HighSchool,NoCollege,Bachelor,Graduate,<20K,20Kâ€“30K,30Kâ€“50K,50Kâ€“100K,>100K
147721,2021-01-04T00:00:00-05:00,2021-01-11T00:00:00-05:00,sc,US,450410003004,87,67,45,45041,00000000045,450410003004,sc,1866,829,1037,127,91,127,70,127,127,127,127,127,127,103,11,387,127,0,21,0,0,0,0,1156,127,301,127,127,46,4,3,580,67,11,51,34,21,16,47,29,10,70,108,60,39,11,4,2,0.555734,0.444266,0.184887,0.037513,0.068060,0.068060,0.068060,0.068060,0.068060,0.197213,0.207395,0.068060,0.000000,0.011254,0.109862,0.260381,0.370242,0.109862,0.08218,0.222414,0.094828,0.175862,0.410345,0.096552
147722,2021-01-11T00:00:00-05:00,2021-01-18T00:00:00-05:00,sc,US,450410003004,83,67,45,45041,00000000045,450410003004,sc,1866,829,1037,127,91,127,70,127,127,127,127,127,127,103,11,387,127,0,21,0,0,0,0,1156,127,301,127,127,46,4,3,580,67,11,51,34,21,16,47,29,10,70,108,60,39,11,4,2,0.555734,0.444266,0.184887,0.037513,0.068060,0.068060,0.068060,0.068060,0.068060,0.197213,0.207395,0.068060,0.000000,0.011254,0.109862,0.260381,0.370242,0.109862,0.08218,0.222414,0.094828,0.175862,0.410345,0.096552
147723,2021-01-18T00:00:00-05:00,2021-01-25T00:00:00-05:00,sc,US,450410003004,81,62,45,45041,00000000045,450410003004,sc,1866,829,1037,127,91,127,70,127,127,127,127,127,127,103,11,387,127,0,21,0,0,0,0,1156,127,301,127,127,46,4,3,580,67,11,51,34,21,16,47,29,10,70,108,60,39,11,4,2,0.555734,0.444266,0.184887,0.037513,0.068060,0.068060,0.068060,0.068060,0.068060,0.197213,0.207395,0.068060,0.000000,0.011254,0.109862,0.260381,0.370242,0.109862,0.08218,0.222414,0.094828,0.175862,0.410345,0.096552
147724,2021-01-25T00:00:00-05:00,2021-02-01T00:00:00-05:00,sc,US,450410003004,83,65,45,45041,00000000045,450410003004,sc,1866,829,1037,127,91,127,70,127,127,127,127,127,127,103,11,387,127,0,21,0,0,0,0,1156,127,301,127,127,46,4,3,580,67,11,51,34,21,16,47,29,10,70,108,60,39,11,4,2,0.555734,0.444266,0.184887,0.037513,0.068060,0.068060,0.068060,0.068060,0.068060,0.197213,0.207395,0.068060,0.000000,0.011254,0.109862,0.260381,0.370242,0.109862,0.08218,0.222414,0.094828,0.175862,0.410345,0.096552
147725,2021-02-01T00:00:00-05:00,2021-02-08T00:00:00-05:00,sc,US,450410003004,86,69,45,45041,00000000045,450410003004,sc,1866,829,1037,127,91,127,70,127,127,127,127,127,127,103,11,387,127,0,21,0,0,0,0,1156,127,301,127,127,46,4,3,580,67,11,51,34,21,16,47,29,10,70,108,60,39,11,4,2,0.555734,0.444266,0.184887,0.037513,0.068060,0.068060,0.068060,0.068060,0.068060,0.197213,0.207395,0.068060,0.000000,0.011254,0.109862,0.260381,0.370242,0.109862,0.08218,0.222414,0.094828,0.175862,0.410345,0.096552
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11410342,2021-10-18T00:00:00-04:00,2021-10-25T00:00:00-04:00,sc,US,450899708021,0,1,45,45089,00000000045,450899708021,sc,1266,1266,0,0,0,0,0,58,127,127,127,98,0,0,0,317,127,27,0,0,96,74,299,1208,127,473,127,37,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000,1.000000,0.000000,0.000000,0.045814,0.100316,0.100316,0.100316,0.077409,0.000000,0.250395,0.100316,0.236177,0.000000,0.105132,0.391556,0.496689,0.030629,0.00000,NaN,NaN,NaN,NaN,NaN
11410343,2021-10-25T00:00:00-04:00,2021-11-01T00:00:00-04:00,sc,US,450899708021,0,1,45,45089,00000000045,450899708021,sc,1266,1266,0,0,0,0,0,58,127,127,127,98,0,0,0,317,127,27,0,0,96,74,299,1208,127,473,127,37,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000,1.000000,0.000000,0.000000,0.045814,0.100316,0.100316,0.100316,0.077409,0.000000,0.250395,0.100316,0.236177,0.000000,0.105132,0.391556,0.496689,0.030629,0.00000,NaN,NaN,NaN,NaN,NaN
11410344,2021-11-01T00:00:00-04:00,2021-11-08T00:00:00-05:00,sc,US,450899708021,0,1,45,45089,00000000045,450899708021,sc,1266,1266,0,0,0,0,0,58,127,127,127,98,0,0,0,317,127,27,0,0,96,74,299,1208,127,473,127,37,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000,1.000000,0.000000,0.000000,0.045814,0.100316,0.100316,0.100316,0.077409,0.000000,0.250395,0.100316,0.236177,0.000000,0.105132,0.391556,0.496689,0.030629,0.00000,NaN,NaN,NaN,NaN,NaN
11410345,2021-11-08T00:00:00-05:00,2021-11-15T00:00:00-05:00,sc,US,450899708021,0,1,45,45089,00000000045,450899708021,sc,1266,1266,0,0,0,0,0,58,127,127,127,98,0,0,0,317,127,27,0,0,96,74,299,1208,127,473,127,37,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000,1.000000,0.000000,0.000000,0.045814,0.100316,0.100316,0.100316,0.077409,0.000000,0.250395,0.100316,0.236177,0.000000,0.105132,0.391556,0.496689,0.030629,0.00000,NaN,NaN,NaN,NaN,NaN
11410346,2021-12-27T00:00:00-05:00,2022-01-03T00:00:00-05:00,sc,US,450899708021,0,1,45,45089,00000000045,450899708021,sc,1266,1266,0,0,0,0,0,58,127,127,127,98,0,0,0,317,127,27,0,0,96,74,299,1208,127,473,127,37,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000,1.000000,0.000000,0.000000,0.045814,0.100316,0.100316,0.100316,0.077409,0.000000,0.250395,0.100316,0.236177,0.000000,0.105132,0.391556,0.496689,0.030629,0.00000,NaN,NaN,NaN,NaN,NaN

In [423]:
len(SC_residing_df['census_block_group'].unique())

3059

In [424]:
SC_residing_df.columns

Index(['date_range_start', 'date_range_end', 'region', 'iso_country_code',
       'census_block_group', 'number_devices_residing',
       'number_devices_primary_daytime', 'state_fips', 'county_fips',
       'tract_fips', 'fips', 'state', 'totalpopulation', 'male', 'female',
       'under5years', '5to9years', '10to14years', '15to17years', '18to24years',
       '25to34years', '35to44years', '45to54years', '55to64years',
       '65to74years', '75to84years', '85yearsandover', 'whitealone',
       'blackorafricanamericanalone', 'americanindianandalaskanativealone',
       'asianalone', 'nativehawaiianandotherpacificislanderalone',
       'someotherracealone', 'twoormoreraces', 'Hispanic_or_Latino',
       'population25yearsandover',
       'population25yearsandoverlessthanhighschool',
       'population25yearsandoverhighschoolgraduateincludesequivalency',
       'population25yearsandoversomecollege',
       'population25yearsandoverbachelorsdegree',
       'population25yearsandovermastersdegree',
       'population25yearsandoverprofessionalschooldegree',
       'population25yearsandoverdoctoratedegree', 'households',
       'householdslessthan10000', 'households10000to14999',
       'households15000to19999', 'households20000to24999',
       'households25000to29999', 'households30000to34999',
       'households35000to39999', 'households40000to44999',
       'households45000to49999', 'households50000to59999',
       'households60000to74999', 'households75000to99999',
       'households100000to124999', 'households125000to149999',
       'households150000to199999', 'households200000ormore', 'Female', 'Male',
       '<15', '15â€“17', '18â€“24', '25â€“34', '35â€“44', '45â€“54', '55â€“64', '>65',
       'White', 'Black', 'Hispanic', 'Asian', 'NoSchool', 'HighSchool',
       'NoCollege', 'Bachelor', 'Graduate', '<20K', '20Kâ€“30K', '30Kâ€“50K',
       '50Kâ€“100K', '>100K'],
      dtype='object')

# Compute bias

In [430]:
from tqdm import tqdm
from datetime import datetime
tqdm.pandas()

columns = ['Female', 'Male',
       '<15', '15â€“17', '18â€“24', '25â€“34', '35â€“44', '45â€“54', '55â€“64', '>65',
       'White', 'Black', 'Hispanic', 'Asian', 'NoSchool', 'HighSchool',
       'NoCollege', 'Bachelor', 'Graduate', '<20K', '20Kâ€“30K', '30Kâ€“50K',
       '50Kâ€“100K', '>100K']

used_columns = ['date_range_start', 'state_fips', 'county_fips', 'tract_fips', 'number_devices_residing', 'totalpopulation'] + columns

def get_bias(df):
    
    # if df.isna().sum() > 0:
    #     print(df)
#     now = datetime.now()
#     current_time = now.strftime("%H:%M:%S")
#     if current_time[-2] == '5':
#         print("Current state:", df.iloc[0]['state_fips'])
        
#     if current_time[-2] == '2':
#         print("Current state:", df.iloc[0]['state_fips'])
    
    df = df.dropna()
    
    aggre_total_device = df['number_devices_residing'].sum()
    aggre_total_pop = df['totalpopulation'].sum()
    
    result_df = pd.DataFrame(columns = [ 'start_date', 'census_ratio', 'safegraph_ratio', 'CBG_count'],
                   index = columns)
    
    result_df.index.name = 'variable'
    
    
    # return result_df
    for column in columns[:]:
        # print(column)
        start_date = df.iloc[0]['date_range_start'][:10] 
        
        # df[column] = df[column] / df['totalpopulation']  # population group ratio of each CBG
        
        cbg_column_devices = df['number_devices_residing'] * df[column]   # population group device count  of each CBG
        # cbg_device_ratio = cbg_column_devices.sum() / state_total_device  # aggregated population group device count / total_device

        cbg_column_pop = df[column] * df['totalpopulation']  # group population  of each CBG        
        census_ratio = cbg_column_pop.sum() / aggre_total_pop   # group population ratio (to the aggregated population)    
        
        safegraph_ratio = cbg_column_devices.sum() / aggre_total_device   # group population device ratio (to the aggregated device count)    
        
        # result_df.loc[column]['variable'] = column
        result_df.loc[column]['start_date'] = start_date
        result_df.loc[column]['CBG_count'] = len(df)
        result_df.loc[column]['census_ratio'] = census_ratio
        result_df.loc[column]['safegraph_ratio'] = safegraph_ratio
        

    return result_df


def get_aggregated_bias(residing_df, aggre_columns):
    
    residing_df.loc[:, 'state_fips'] = residing_df['state_fips'].astype(str).str.zfill(2)
    
    residing_df['date_range_start'] = residing_df['date_range_start'].astype(str).str[:10]   # have an issue of different starting hours 
    groupby_cols = ['date_range_start'] + aggre_columns
    # return aggre_columns

    bias_df = residing_df.sort_values('date_range_start').groupby(groupby_cols).progress_apply(get_bias)
    
    # return bias_df

    bias_df.reset_index(drop=False, inplace=True)
    # bias_df['start_date'] = bias_df['date_range_start'].astype(str).str[:10] 
    # bias_df = bias_df.drop(columns=['date_range_start'])
    
    # return aggre_columns + ['variable']

    bias_gb_df = bias_df.groupby(aggre_columns + ['variable']).agg(
                                      start_date=('start_date', 'first'), 
                                      end_date=('start_date', 'last'), 
                                      period_count=('CBG_count', 'count'), 
                                      CBG_count=('CBG_count', 'mean'), 
                                      safegraph_ratio_mean=('safegraph_ratio', 'mean'), 
                                      safegraph_ratio_min=('safegraph_ratio', min), 
                                      safegraph_ratio_max=('safegraph_ratio', max),
                                      census_ratio=('census_ratio', 'mean'),
                                      # census_ratio_max=('census_ratio', max),
                                      # census_ratio_min=('census_ratio', min),
                                     )
    
    # return bias_gb_df

    # if len(aggre_columns) == 1:
    #     bias_gb_df = bias_gb_df.loc[:, columns, :]  
    # if len(aggre_columns) == 2:
    #     bias_gb_df = bias_gb_df.loc[:, :, columns, :]  
    # if len(aggre_columns) == 3:
    #     bias_gb_df = bias_gb_df.loc[:, :, :, columns, :]  

    bias_gb_df['safegraph_ratio_mean_to_census'] = bias_gb_df['safegraph_ratio_mean'] / bias_gb_df['census_ratio']
    bias_gb_df['safegraph_ratio_min_to_census' ] = bias_gb_df['safegraph_ratio_min' ] / bias_gb_df['census_ratio']
    bias_gb_df['safegraph_ratio_max_to_census' ] = bias_gb_df['safegraph_ratio_max' ] / bias_gb_df['census_ratio']
    
    bias_gb_df['CBG_count'] = bias_gb_df['CBG_count'].astype(int)
    
    bias_gb_df = bias_gb_df.reset_index()
    bias_gb_df['variable'] = pd.Categorical(bias_gb_df['variable'], categories=columns, ordered=True)

    bias_gb_df = bias_gb_df.sort_values(aggre_columns + ['variable']) #   sort

  
    return bias_gb_df, bias_df

def compute_state_bias():
    save_path = r'P:\Shared drives\NJIT_T5\safegraph_bias'
    new_name = os.path.join(save_path, f'weekly_bias_state_{YEAR}.csv')
    aggre_columns = ['state_fips']

    # bias_gb_df = get_aggregated_bias(residing_df=SC_residing_df[used_columns], aggre_columns=aggre_columns)
    bias_gb_df, bias_df = get_aggregated_bias(residing_df=weekly_residing_merged_df[used_columns].dropna(), aggre_columns=aggre_columns)
    
    bias_gb_df.to_csv(new_name, index=False)
    
    new_name = os.path.join(save_path, f'weekly_bias_state_{YEAR}_time.csv')
    bias_df.to_csv(new_name, index=False)
    
    return bias_gb_df, bias_df

def compute_county_bias():
    save_path = r'P:\Shared drives\NJIT_T5\safegraph_bias'
    new_name = os.path.join(save_path, f'weekly_bias_county_{YEAR}.csv')

    aggre_columns = ['state_fips', 'county_fips']
    bias_gb_df, bias_df = get_aggregated_bias(residing_df=weekly_residing_merged_df.iloc[:].dropna(), aggre_columns=aggre_columns[:])
    # bias_gb_df = get_aggregated_bias(residing_df=SC_residing_df[used_columns], aggre_columns=aggre_columns[:])
    bias_gb_df.to_csv(new_name, index=False)
    
    new_name = os.path.join(save_path, f'weekly_bias_county_{YEAR}_time.csv')
    bias_df.to_csv(new_name, index=False)
    
    return bias_gb_df, bias_df

def compute_tract_bias():
    save_path = r'P:\Shared drives\NJIT_T5\safegraph_bias'
    new_name = os.path.join(save_path, f'weekly_bias_tract_{YEAR}.csv')

    aggre_columns = ['state_fips', 'county_fips', 'tract_fips']
    bias_gb_df, bias_df = get_aggregated_bias(residing_df=weekly_residing_merged_df[used_columns].dropna(), aggre_columns=aggre_columns[:])
    # bias_gb_df = get_aggregated_bias(residing_df=SC_residing_df.iloc[:1000], aggre_columns=aggre_columns[:])
    
    bias_gb_df.to_csv(new_name, index=False)
    
    new_name = os.path.join(save_path, f'weekly_bias_tract_{YEAR}_time.csv')
    bias_df.to_csv(new_name, index=False)
    
    return bias_gb_df, bias_df

bias_gb_df, bias_df = compute_state_bias()
bias_gb_df, bias_df = compute_county_bias()
# bias_gb_df, bias_df = compute_tract_bias()

bias_gb_df.round(2)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2704/2704 [01:10<00:00, 38.20it/s]
 12%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‰                                                                  | 19864/167427 [06:46<49:18, 49.87it/s]C:\Users\GPU\.conda\envs\Google_street_view\lib\site-packages\ipykernel_launcher.py:49: RuntimeWarning: invalid value encountered in double_scalars
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 167427/167427 [56:33<00:00, 49.34it/s]

,state_fips,county_fips,variable,start_date,end_date,period_count,CBG_count,safegraph_ratio_mean,safegraph_ratio_min,safegraph_ratio_max,census_ratio,safegraph_ratio_mean_to_census,safegraph_ratio_min_to_census,safegraph_ratio_max_to_census
16,01,01001,Female,2021-01-04,2021-12-27,52,32,0.51,0.51,0.52,0.51,1.00,1.00,1.00
20,01,01001,Male,2021-01-04,2021-12-27,52,32,0.49,0.48,0.49,0.49,1.00,1.00,1.00
9,01,01001,<15,2021-01-04,2021-12-27,52,32,0.13,0.13,0.14,0.14,0.97,0.96,0.98
0,01,01001,15â€“17,2021-01-04,2021-12-27,52,32,0.04,0.04,0.04,0.04,0.99,0.98,0.99
1,01,01001,18â€“24,2021-01-04,2021-12-27,52,32,0.06,0.05,0.06,0.06,0.99,0.98,1.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77266,72,72153,<20K,2021-01-04,2021-12-27,52,19,0.49,0.45,0.53,0.48,1.02,0.93,1.10
77258,72,72153,20Kâ€“30K,2021-01-04,2021-12-27,52,19,0.15,0.12,0.17,0.15,0.98,0.82,1.12
77260,72,72153,30Kâ€“50K,2021-01-04,2021-12-27,52,19,0.15,0.13,0.18,0.16,0.97,0.82,1.12
77263,72,72153,50Kâ€“100K,2021-01-04,2021-12-27,52,19,0.10,0.06,0.13,0.09,1.01,0.65,1.39
77267,72,72153,>100K,2021-01-04,2021-12-27,52,19,0.02,0.01,0.04,0.02,1.11,0.55,2.42

In [429]:
bias_gb_df.to_csv(r'P:\Shared drives\NJIT_T5\safegraph_bias\weekly_bias_county_2021.csv', index=False)

In [ ]:
stop

# Compute device sampling rate

## Weekly

In [435]:
# weekly residing files
weekly_residing_all_df = pd.read_csv(r'J:\weekly_patterns_20211211\Panel_overview_data\WeeklyPattern\weekly_home_panel_summary.csv', dtype={'census_block_group':str})
# weekly_residing_df = weekly_residing_df.merge(sociala_variable_df, left_on='census_block_group', right_on='fips')
weekly_residing_all_df['census_block_group'] = weekly_residing_all_df['census_block_group'].str.zfill(12)
weekly_residing_all_df = weekly_residing_all_df.sort_values(['date_range_start', 'date_range_end'])
weekly_residing_all_df

,date_range_start,date_range_end,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime
54709667,2018-01-01T00:00:00+10:00,2018-01-08T00:00:00+10:00,gu,US,660109544001,5,5
54709668,2018-01-01T00:00:00+10:00,2018-01-08T00:00:00+10:00,gu,US,660109507022,5,4
54709669,2018-01-01T00:00:00+10:00,2018-01-08T00:00:00+10:00,gu,US,660109507023,14,12
54709670,2018-01-01T00:00:00+10:00,2018-01-08T00:00:00+10:00,gu,US,660109510002,4,4
54709671,2018-01-01T00:00:00+10:00,2018-01-08T00:00:00+10:00,gu,US,660109529003,3,3
...,...,...,...,...,...,...,...
16235,2021-12-27T00:00:00-10:00,2022-01-03T00:00:00-10:00,hi,US,150090311031,41,37
59971,2021-12-27T00:00:00-10:00,2022-01-03T00:00:00-10:00,ak,US,020160001001,34,22
65799,2021-12-27T00:00:00-11:00,2022-01-03T00:00:00-11:00,as,US,600109506002,5,6
65800,2021-12-27T00:00:00-11:00,2022-01-03T00:00:00-11:00,as,US,600109509002,1,0
65801,2021-12-27T00:00:00-11:00,2022-01-03T00:00:00-11:00,as,US,600509516004,1,0

In [1]:
YEAR = '2018'
if YEAR > "2019":
    acs_year = '2019'
else:
    acs_year = YEAR
acs_year

'2018'

In [475]:
social_variable_df = pd.read_csv(fr'F:\USC_OneDrive\OneDrive - University of South Carolina\Research\Safegraph_bias\cbg_acs_{acs_year}_county_tract.csv', dtype={'fips':str})
social_variable_df['fips'] = social_variable_df['fips'].astype(str).str.zfill(12)
social_variable_df.columns
print("US population, male, female:")
social_variable_df['totalpopulation'].sum(), social_variable_df['male'].sum(), social_variable_df['female'].sum(), len(social_variable_df)

US population, male, female:

(327939105, 161465237, 166551005, 220333)

In [476]:
weekly_residing_year_df = weekly_residing_all_df[weekly_residing_all_df["date_range_start"].str.startswith(YEAR)]
weekly_residing_merged_df = weekly_residing_year_df.merge(social_variable_df, left_on='census_block_group', right_on='fips')
weekly_residing_merged_df

,date_range_start,date_range_end,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime,state_fips,county_fips,tract_fips,fips,state,totalpopulation,male,female,under5years,5to9years,10to14years,15to17years,18to24years,25to34years,35to44years,45to54years,55to64years,65to74years,75to84years,85yearsandover,whitealone,blackorafricanamericanalone,americanindianandalaskanativealone,asianalone,nativehawaiianandotherpacificislanderalone,someotherracealone,twoormoreraces,Hispanic_or_Latino,population25yearsandover,population25yearsandoverlessthanhighschool,population25yearsandoverhighschoolgraduateincludesequivalency,population25yearsandoversomecollege,population25yearsandoverbachelorsdegree,population25yearsandovermastersdegree,population25yearsandoverprofessionalschooldegree,population25yearsandoverdoctoratedegree,households,householdslessthan10000,households10000to14999,households15000to19999,households20000to24999,households25000to29999,households30000to34999,households35000to39999,households40000to44999,households45000to49999,households50000to59999,households60000to74999,households75000to99999,households100000to124999,households125000to149999,households150000to199999,households200000ormore
0,2021-01-04T00:00:00-04:00,2021-01-11T00:00:00-04:00,pr,US,720678204002,2,4,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0
1,2021-01-11T00:00:00-04:00,2021-01-18T00:00:00-04:00,pr,US,720678204002,2,4,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0
2,2021-01-18T00:00:00-04:00,2021-01-25T00:00:00-04:00,pr,US,720678204002,0,2,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0
3,2021-01-25T00:00:00-04:00,2021-02-01T00:00:00-04:00,pr,US,720678204002,0,1,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0
4,2021-02-01T00:00:00-04:00,2021-02-08T00:00:00-04:00,pr,US,720678204002,1,0,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11630225,2021-12-27T00:00:00-05:00,2022-01-03T00:00:00-05:00,mi,US,260139901000,1,0,26,26013,26013990100,260139901000,mi,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11630226,2021-12-27T00:00:00-05:00,2022-01-03T00:00:00-05:00,ny,US,360470164000,1,0,36,36047,36047016400,360470164000,ny,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11630227,2021-12-27T00:00:00-05:00,2022-01-03T00:00:00-05:00,wi,US,550039900000,1,0,55,55003,55003990000,550039900000,wi,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11630228,2021-12-27T00:00:00-06:00,2022-01-03T00:00:00-06:00,la,US,220879900000,1,0,22,22087,22087990000,220879900000,la,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11630229,2021-12-27T00:00:00-10:00,2022-01-03T00:00:00-10:00,hi,US,150099900000,1,0,15,15009,15009990000,150099900000,hi,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [477]:
weekly_residing_merged_df['date_range_start'] = weekly_residing_merged_df['date_range_start'].astype(str).str[:10]
weekly_residing_merged_df['state_fips'] = weekly_residing_merged_df['state_fips'].astype(str).str.zfill(2)
weekly_residing_merged_df['county_fips'] = weekly_residing_merged_df['county_fips'].astype(str).str.zfill(5)
weekly_residing_merged_df['tract_fips'] = weekly_residing_merged_df['tract_fips'].astype(str).str.zfill(11)
weekly_residing_merged_df['year'] =  weekly_residing_merged_df['date_range_start'].astype(str).str[:4]
weekly_residing_merged_df.rename(columns={'fips':'cbg_fips'}, inplace=True)
weekly_residing_merged_df

,date_range_start,date_range_end,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime,state_fips,county_fips,tract_fips,cbg_fips,state,totalpopulation,male,female,under5years,5to9years,10to14years,15to17years,18to24years,25to34years,35to44years,45to54years,55to64years,65to74years,75to84years,85yearsandover,whitealone,blackorafricanamericanalone,americanindianandalaskanativealone,asianalone,nativehawaiianandotherpacificislanderalone,someotherracealone,twoormoreraces,Hispanic_or_Latino,population25yearsandover,population25yearsandoverlessthanhighschool,population25yearsandoverhighschoolgraduateincludesequivalency,population25yearsandoversomecollege,population25yearsandoverbachelorsdegree,population25yearsandovermastersdegree,population25yearsandoverprofessionalschooldegree,population25yearsandoverdoctoratedegree,households,householdslessthan10000,households10000to14999,households15000to19999,households20000to24999,households25000to29999,households30000to34999,households35000to39999,households40000to44999,households45000to49999,households50000to59999,households60000to74999,households75000to99999,households100000to124999,households125000to149999,households150000to199999,households200000ormore,year
0,2021-01-04,2021-01-11T00:00:00-04:00,pr,US,720678204002,2,4,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0,2021
1,2021-01-11,2021-01-18T00:00:00-04:00,pr,US,720678204002,2,4,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0,2021
2,2021-01-18,2021-01-25T00:00:00-04:00,pr,US,720678204002,0,2,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0,2021
3,2021-01-25,2021-02-01T00:00:00-04:00,pr,US,720678204002,0,1,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0,2021
4,2021-02-01,2021-02-08T00:00:00-04:00,pr,US,720678204002,1,0,72,72067,72067820400,720678204002,pr,684,325,359,23,11,20,0,58,72,55,67,127,103,124,22,186,76,0,0,0,371,51,684,572,127,167,92,49,6,0,0,285,69,87,36,21,31,6,5,0,0,4,26,0,0,0,0,0,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11630225,2021-12-27,2022-01-03T00:00:00-05:00,mi,US,260139901000,1,0,26,26013,26013990100,260139901000,mi,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021
11630226,2021-12-27,2022-01-03T00:00:00-05:00,ny,US,360470164000,1,0,36,36047,36047016400,360470164000,ny,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021
11630227,2021-12-27,2022-01-03T00:00:00-05:00,wi,US,550039900000,1,0,55,55003,55003990000,550039900000,wi,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021
11630228,2021-12-27,2022-01-03T00:00:00-06:00,la,US,220879900000,1,0,22,22087,22087990000,220879900000,la,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021
11630229,2021-12-27,2022-01-03T00:00:00-10:00,hi,US,150099900000,1,0,15,15009,15009990000,150099900000,hi,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021

In [478]:
df = weekly_residing_merged_df[weekly_residing_merged_df["date_range_start"].str.startswith(YEAR)].query("region == 'sc'")
df

,date_range_start,date_range_end,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime,state_fips,county_fips,tract_fips,cbg_fips,state,totalpopulation,male,female,under5years,5to9years,10to14years,15to17years,18to24years,25to34years,35to44years,45to54years,55to64years,65to74years,75to84years,85yearsandover,whitealone,blackorafricanamericanalone,americanindianandalaskanativealone,asianalone,nativehawaiianandotherpacificislanderalone,someotherracealone,twoormoreraces,Hispanic_or_Latino,population25yearsandover,population25yearsandoverlessthanhighschool,population25yearsandoverhighschoolgraduateincludesequivalency,population25yearsandoversomecollege,population25yearsandoverbachelorsdegree,population25yearsandovermastersdegree,population25yearsandoverprofessionalschooldegree,population25yearsandoverdoctoratedegree,households,householdslessthan10000,households10000to14999,households15000to19999,households20000to24999,households25000to29999,households30000to34999,households35000to39999,households40000to44999,households45000to49999,households50000to59999,households60000to74999,households75000to99999,households100000to124999,households125000to149999,households150000to199999,households200000ormore,year
150859,2021-01-04,2021-01-11T00:00:00-05:00,sc,US,450410003004,87,67,45,45041,45041000300,450410003004,sc,1866,829,1037,127,91,127,70,127,127,127,127,127,127,103,11,387,127,0,21,0,0,0,0,1156,127,301,127,127,46,4,3,580,67,11,51,34,21,16,47,29,10,70,108,60,39,11,4,2,2021
150860,2021-01-11,2021-01-18T00:00:00-05:00,sc,US,450410003004,83,67,45,45041,45041000300,450410003004,sc,1866,829,1037,127,91,127,70,127,127,127,127,127,127,103,11,387,127,0,21,0,0,0,0,1156,127,301,127,127,46,4,3,580,67,11,51,34,21,16,47,29,10,70,108,60,39,11,4,2,2021
150861,2021-01-18,2021-01-25T00:00:00-05:00,sc,US,450410003004,81,62,45,45041,45041000300,450410003004,sc,1866,829,1037,127,91,127,70,127,127,127,127,127,127,103,11,387,127,0,21,0,0,0,0,1156,127,301,127,127,46,4,3,580,67,11,51,34,21,16,47,29,10,70,108,60,39,11,4,2,2021
150862,2021-01-25,2021-02-01T00:00:00-05:00,sc,US,450410003004,83,65,45,45041,45041000300,450410003004,sc,1866,829,1037,127,91,127,70,127,127,127,127,127,127,103,11,387,127,0,21,0,0,0,0,1156,127,301,127,127,46,4,3,580,67,11,51,34,21,16,47,29,10,70,108,60,39,11,4,2,2021
150863,2021-02-01,2021-02-08T00:00:00-05:00,sc,US,450410003004,86,69,45,45041,45041000300,450410003004,sc,1866,829,1037,127,91,127,70,127,127,127,127,127,127,103,11,387,127,0,21,0,0,0,0,1156,127,301,127,127,46,4,3,580,67,11,51,34,21,16,47,29,10,70,108,60,39,11,4,2,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11630108,2021-10-18,2021-10-25T00:00:00-04:00,sc,US,450899708021,0,1,45,45089,45089970802,450899708021,sc,1266,1266,0,0,0,0,0,58,127,127,127,98,0,0,0,317,127,27,0,0,96,74,299,1208,127,473,127,37,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021
11630109,2021-10-25,2021-11-01T00:00:00-04:00,sc,US,450899708021,0,1,45,45089,45089970802,450899708021,sc,1266,1266,0,0,0,0,0,58,127,127,127,98,0,0,0,317,127,27,0,0,96,74,299,1208,127,473,127,37,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021
11630110,2021-11-01,2021-11-08T00:00:00-05:00,sc,US,450899708021,0,1,45,45089,45089970802,450899708021,sc,1266,1266,0,0,0,0,0,58,127,127,127,98,0,0,0,317,127,27,0,0,96,74,299,1208,127,473,127,37,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021
11630111,2021-11-08,2021-11-15T00:00:00-05:00,sc,US,450899708021,0,1,45,45089,45089970802,450899708021,sc,1266,1266,0,0,0,0,0,58,127,127,127,98,0,0,0,317,127,27,0,0,96,74,299,1208,127,473,127,37,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021
11630112,2021-12-27,2022-01-03T00:00:00-05:00,sc,US,450899708021,0,1,45,45089,45089970802,450899708021,sc,1266,1266,0,0,0,0,0,58,127,127,127,98,0,0,0,317,127,27,0,0,96,74,299,1208,127,473,127,37,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2021

In [479]:
import numpy as np
def get_sampling_rate(residing_df, aggre_columns):
    # residing_df['date_range_start'] = residing_df['date_range_start'].astype(str).str[:10]
    aggre_columns = ['date_range_start'] + aggre_columns
    
    sampling_rate_df = residing_df.groupby(aggre_columns).agg(
                                      
                                      start_date=('date_range_start', 'first'), 
                                      end_date=('date_range_start', 'last'), 
                                      # period_count=('CBG_count', 'count'), 
                                      CBG_count=('totalpopulation', 'count'), 
                                      fips=(aggre_columns[-1], 'first'), 
                                      device_count=('number_devices_residing', 'sum'), 
                                      population=('totalpopulation', 'sum'), 
                                      year=('year', 'first'),
                                      aggre_column=(aggre_columns[-1], 'first'), 
                                      # safegraph_ratio_max=('safegraph_ratio', max),
                                      # census_ratio=('census_ratio', 'mean'),
                                      # census_ratio_max=('census_ratio', max),
                                      # census_ratio_min=('census_ratio', min),
                                     )
    
    sampling_rate_df['sampling_rate'] = sampling_rate_df['device_count'] / sampling_rate_df['population']
    sampling_rate_df.replace([np.inf], np.nan, inplace=True)

    return sampling_rate_df.reset_index().iloc[:, 2:]


def save_df(df, save_name):
    
    print("Saved.")
    

def compute_sampling_rates(df, aggre_columns = ['state_fips', 'county_fips', 'tract_fips', 'cbg_fips']):
    df_list = []
    for c in aggre_columns:
        sampling_rate_df = get_sampling_rate(df, aggre_columns=[c])
        df_list.append(sampling_rate_df)
        
    df_all = pd.concat(df_list)
    
    return df_all

df_all = compute_sampling_rates(weekly_residing_merged_df, aggre_columns = ['state_fips', 'county_fips', 'tract_fips', 'cbg_fips'])
# df_all = compute_sampling_rates(df,                        aggre_columns = ['state_fips', 'county_fips', 'tract_fips', 'cbg_fips'])

df_all['fips_len'] = df_all['fips'].astype(str).str.len()
df_all['fips_level'] = df_all['fips_len'].astype(str)
df_all['fips_level'] = df_all['fips_level'].replace({'2':"state", '5':"county", '11': 'tract', '12':'cbg'})

df_all.to_csv(fr'P:\Shared drives\NJIT_T5\safegraph_bias\sampling_rates_{YEAR}.csv', index=False)
df_all

,start_date,end_date,CBG_count,fips,device_count,population,year,aggre_column,sampling_rate,fips_len,fips_level
0,2021-01-04,2021-01-04,3438,01,394059,4876250,2021,01,0.080812,2,state
1,2021-01-04,2021-01-04,528,02,22125,733893,2021,02,0.030147,2,state
2,2021-01-04,2021-01-04,4177,04,313834,7050299,2021,04,0.044514,2,state
3,2021-01-04,2021-01-04,2147,05,217957,2999370,2021,05,0.072668,2,state
4,2021-01-04,2021-01-04,23192,06,1311949,39272874,2021,06,0.033406,2,state
...,...,...,...,...,...,...,...,...,...,...,...
11410434,2021-12-27,2021-12-27,1,721537505032,2,981,2021,721537505032,0.002039,12,cbg
11410435,2021-12-27,2021-12-27,1,721537506011,2,883,2021,721537506011,0.002265,12,cbg
11410436,2021-12-27,2021-12-27,1,721537506012,7,2523,2021,721537506012,0.002774,12,cbg
11410437,2021-12-27,2021-12-27,1,721537506013,8,991,2021,721537506013,0.008073,12,cbg
11410438,2021-12-27,2021-12-27,1,721537506021,3,1577,2021,721537506021,0.001902,12,cbg

In [480]:
df_all['sampling_rate'].mean(), df_all['sampling_rate'].max(), df_all['sampling_rate'].min()

(0.0539842884694264, 362.5, 0.0)

In [481]:
def time_aggregate(sampling_rate_df):
    
    rate_gb_df = sampling_rate_df.groupby(['year', 'fips']).agg(
                                      start_date=('start_date', 'first'), 
                                      end_date=('end_date', 'last'), 
                                      period_count=('start_date', 'count'), 
                                      CBG_count=('CBG_count', 'mean'), 
                                      device_count_mean=('device_count', 'mean'), 
                                      population=('population', 'mean'), 
                                      sampling_rate_mean=('sampling_rate', 'mean'),
                                      sampling_rate_max=('sampling_rate', max),
                                      sampling_rate_min=('sampling_rate', min),        
                                     )
    
    return rate_gb_df
    
rate_gb_df = time_aggregate(df_all.iloc[:]).reset_index()
# rate_gb_df.to_csv(r'P:\Shared drives\NJIT_T5\safegraph_bias\sampling_rates_yearly.csv', index=False)
rate_gb_df['fips_len'] = rate_gb_df['fips'].astype(str).str.len()
rate_gb_df['fips_level'] = rate_gb_df['fips_len'].astype(str)
rate_gb_df['fips_level'] = rate_gb_df['fips_level'].replace({'2':"state", '5':"county", '11': 'tract', '12':'cbg'})

rate_gb_df.to_csv(fr'P:\Shared drives\NJIT_T5\safegraph_bias\sampling_rates_{YEAR}_yearly.csv', index=False)

rate_gb_df

,year,fips,start_date,end_date,period_count,CBG_count,device_count_mean,population,sampling_rate_mean,sampling_rate_max,sampling_rate_min,fips_len,fips_level
0,2021,01,2021-01-04,2021-12-27,52,3503.615385,408712.230769,4.970024e+06,0.081901,0.103577,0.075744,2,state
1,2021,01001,2021-01-04,2021-12-27,52,32.615385,5263.519231,5.644500e+04,0.092875,0.115312,0.085645,5,county
2,2021,01001020100,2021-01-04,2021-12-27,52,2.038462,242.365385,2.031327e+03,0.118482,0.176618,0.100351,11,tract
3,2021,010010201001,2021-01-04,2021-12-27,52,1.019231,111.423077,7.440385e+02,0.148209,0.275342,0.093151,12,cbg
4,2021,010010201002,2021-01-04,2021-12-27,52,1.019231,130.942308,1.287288e+03,0.101300,0.123515,0.091053,12,cbg
...,...,...,...,...,...,...,...,...,...,...,...,...,...
297408,2021,721537506012,2021-01-04,2021-12-27,49,1.020408,4.816327,2.574490e+03,0.001869,0.012287,0.000000,12,cbg
297409,2021,721537506013,2021-01-04,2021-12-27,50,1.020000,3.480000,1.010820e+03,0.003471,0.019173,0.000000,12,cbg
297410,2021,72153750602,2021-01-04,2021-12-27,45,1.488889,2.733333,1.831867e+03,0.001405,0.005393,0.000000,11,tract
297411,2021,721537506021,2021-01-04,2021-12-27,41,1.024390,1.951220,1.615463e+03,0.001206,0.005073,0.000000,12,cbg
297412,2021,721537506022,2021-01-04,2021-11-22,25,1.000000,1.720000,6.480000e+02,0.002654,0.009259,0.000000,12,cbg

In [482]:
rate_gb_df['sampling_rate_mean'].mean(), rate_gb_df['sampling_rate_mean'].max(), rate_gb_df['sampling_rate_mean'].min()

(0.05389302167150877, 151.57692307692307, 0.0)

In [483]:
stop

NameError: name 'stop' is not defined

## Monthly

In [3]:
# weekly residing files
residing_all_df = pd.read_csv(r'J:\monthly_patterns_20211211\Panel_overview_data\MonthlyPattern\monthly_home_panel_summary.csv', dtype={'census_block_group':str})
# weekly_residing_df = weekly_residing_df.merge(sociala_variable_df, left_on='census_block_group', right_on='fips')
residing_all_df['census_block_group'] = residing_all_df['census_block_group'].str.zfill(12)
residing_all_df['date_range_start'] = residing_all_df['year'].astype(str).str.zfill(4) + residing_all_df['month'].astype(str).str.zfill(2)
residing_all_df['date_range_end'] = residing_all_df['date_range_start'] 
residing_all_df = residing_all_df.sort_values(['date_range_start', 'date_range_end'])
residing_all_df['date_range_start'] = residing_all_df['year'].astype(str).str.zfill(4) + residing_all_df['month'].astype(str).str.zfill(2)
residing_all_df

,year,month,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime,date_range_start,date_range_end
10569887,2018,1,ak,US,021880001002,9,5,201801,201801
10569888,2018,1,ak,US,021700006011,118,103,201801,201801
10569889,2018,1,ak,US,021220010001,120,93,201801,201801
10569890,2018,1,ak,US,021220006002,45,34,201801,201801
10569891,2018,1,ak,US,020200015003,42,38,201801,201801
...,...,...,...,...,...,...,...,...,...
220201,2022,1,wy,US,560119502001,86,60,202201,202201
220202,2022,1,wy,US,560199552003,62,52,202201,202201
220203,2022,1,wy,US,560159580003,83,54,202201,202201
220204,2022,1,wy,US,560250006002,90,67,202201,202201
220205,2022,1,wy,US,560210005015,43,28,202201,202201

In [4]:
YEAR = '2021'

if YEAR > "2019":
    acs_year = '2019'
else:
    acs_year = YEAR

In [5]:
residing_df = residing_all_df[residing_all_df["date_range_start"].astype(str).str.startswith(str(YEAR))] 
residing_df['date_range_start']

2640135    202101
2640136    202101
2640137    202101
2640138    202101
2640139    202101
            ...
439951     202112
439952     202112
439953     202112
439954     202112
439955     202112
Name: date_range_start, Length: 2640227, dtype: object

In [530]:
social_variable_df = pd.read_csv(fr'F:\USC_OneDrive\OneDrive - University of South Carolina\Research\Safegraph_bias\cbg_acs_{acs_year}_county_tract.csv', dtype={'fips':str})
social_variable_df['fips'] = social_variable_df['fips'].astype(str).str.zfill(12)
social_variable_df.columns

print("acs_year, US population, male, female:")
acs_year, social_variable_df['totalpopulation'].sum(), social_variable_df['male'].sum(), social_variable_df['female'].sum(), len(social_variable_df)

acs_year, US population, male, female:

('2019', 327939105, 161465237, 166551005, 220333)

In [531]:
residing_merged_df = residing_df.merge(social_variable_df, left_on='census_block_group', right_on='fips')
residing_merged_df

,year,month,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime,date_range_start,date_range_end,state_fips,county_fips,tract_fips,fips,state,totalpopulation,male,female,under5years,5to9years,10to14years,15to17years,18to24years,25to34years,35to44years,45to54years,55to64years,65to74years,75to84years,85yearsandover,whitealone,blackorafricanamericanalone,americanindianandalaskanativealone,asianalone,nativehawaiianandotherpacificislanderalone,someotherracealone,twoormoreraces,Hispanic_or_Latino,population25yearsandover,population25yearsandoverlessthanhighschool,population25yearsandoverhighschoolgraduateincludesequivalency,population25yearsandoversomecollege,population25yearsandoverbachelorsdegree,population25yearsandovermastersdegree,population25yearsandoverprofessionalschooldegree,population25yearsandoverdoctoratedegree,households,householdslessthan10000,households10000to14999,households15000to19999,households20000to24999,households25000to29999,households30000to34999,households35000to39999,households40000to44999,households45000to49999,households50000to59999,households60000to74999,households75000to99999,households100000to124999,households125000to149999,households150000to199999,households200000ormore
0,2021,1,ak,US,022400001002,28,22,202101,202101,2,2240,2240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
1,2021,2,ak,US,022400001002,15,14,202102,202102,2,2240,2240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
2,2021,3,ak,US,022400001002,21,21,202103,202103,2,2240,2240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
3,2021,4,ak,US,022400001002,26,18,202104,202104,2,2240,2240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
4,2021,5,ak,US,022400001002,31,22,202105,202105,2,2240,2240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2637927,2021,12,nc,US,370899801001,1,1,202112,202112,37,37089,37089980100,370899801001,nc,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2637928,2021,12,nj,US,340297360010,1,0,202112,202112,34,34029,34029736001,340297360010,nj,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2637929,2021,12,ny,US,360850228000,1,0,202112,202112,36,36085,36085022800,360850228000,ny,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2637930,2021,12,ny,US,360850244010,1,0,202112,202112,36,36085,36085024401,360850244010,ny,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2637931,2021,12,pr,US,721439900000,0,1,202112,202112,72,72143,72143990000,721439900000,pr,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [532]:
residing_merged_df['date_range_start'] = residing_merged_df['date_range_start'].astype(str).str[:10]
residing_merged_df['state_fips'] = residing_merged_df['state_fips'].astype(str).str.zfill(2)
residing_merged_df['county_fips'] = residing_merged_df['county_fips'].astype(str).str.zfill(5)
residing_merged_df['tract_fips'] = residing_merged_df['tract_fips'].astype(str).str.zfill(11)
residing_merged_df['year'] =  residing_merged_df['date_range_start'].astype(str).str[:4]
residing_merged_df.rename(columns={'fips':'cbg_fips'}, inplace=True)
residing_merged_df

,year,month,region,iso_country_code,census_block_group,number_devices_residing,number_devices_primary_daytime,date_range_start,date_range_end,state_fips,county_fips,tract_fips,cbg_fips,state,totalpopulation,male,female,under5years,5to9years,10to14years,15to17years,18to24years,25to34years,35to44years,45to54years,55to64years,65to74years,75to84years,85yearsandover,whitealone,blackorafricanamericanalone,americanindianandalaskanativealone,asianalone,nativehawaiianandotherpacificislanderalone,someotherracealone,twoormoreraces,Hispanic_or_Latino,population25yearsandover,population25yearsandoverlessthanhighschool,population25yearsandoverhighschoolgraduateincludesequivalency,population25yearsandoversomecollege,population25yearsandoverbachelorsdegree,population25yearsandovermastersdegree,population25yearsandoverprofessionalschooldegree,population25yearsandoverdoctoratedegree,households,householdslessthan10000,households10000to14999,households15000to19999,households20000to24999,households25000to29999,households30000to34999,households35000to39999,households40000to44999,households45000to49999,households50000to59999,households60000to74999,households75000to99999,households100000to124999,households125000to149999,households150000to199999,households200000ormore
0,2021,1,ak,US,022400001002,28,22,202101,202101,02,02240,02240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
1,2021,2,ak,US,022400001002,15,14,202102,202102,02,02240,02240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
2,2021,3,ak,US,022400001002,21,21,202103,202103,02,02240,02240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
3,2021,4,ak,US,022400001002,26,18,202104,202104,02,02240,02240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
4,2021,5,ak,US,022400001002,31,22,202105,202105,02,02240,02240000100,022400001002,ak,1289,618,671,99,66,76,28,38,127,127,127,127,127,29,6,965,0,280,11,0,0,33,8,982,84,320,127,73,127,7,0,521,32,26,26,30,26,0,33,22,6,31,64,41,73,43,35,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2637927,2021,12,nc,US,370899801001,1,1,202112,202112,37,37089,37089980100,370899801001,nc,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2637928,2021,12,nj,US,340297360010,1,0,202112,202112,34,34029,34029736001,340297360010,nj,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2637929,2021,12,ny,US,360850228000,1,0,202112,202112,36,36085,36085022800,360850228000,ny,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2637930,2021,12,ny,US,360850244010,1,0,202112,202112,36,36085,36085024401,360850244010,ny,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2637931,2021,12,pr,US,721439900000,0,1,202112,202112,72,72143,72143990000,721439900000,pr,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [533]:
import numpy as np
def get_sampling_rate(residing_df, aggre_columns):
    # residing_df['date_range_start'] = residing_df['date_range_start'].astype(str).str[:10]
    aggre_columns = ['date_range_start'] + aggre_columns
    
    sampling_rate_df = residing_df.groupby(aggre_columns).agg(
                                      
                                      start_date=('date_range_start', 'first'), 
                                      end_date=('date_range_start', 'last'), 
                                      # period_count=('CBG_count', 'count'), 
                                      CBG_count=('totalpopulation', 'count'), 
                                      fips=(aggre_columns[-1], 'first'), 
                                      device_count=('number_devices_residing', 'sum'), 
                                      population=('totalpopulation', 'sum'), 
                                      year=('year', 'first'),
                                      aggre_column=(aggre_columns[-1], 'first'), 
                                      # safegraph_ratio_max=('safegraph_ratio', max),
                                      # census_ratio=('census_ratio', 'mean'),
                                      # census_ratio_max=('census_ratio', max),
                                      # census_ratio_min=('census_ratio', min),
                                     )
    
    sampling_rate_df['sampling_rate'] = sampling_rate_df['device_count'] / sampling_rate_df['population']
    sampling_rate_df.replace([np.inf], np.nan, inplace=True)

    return sampling_rate_df.reset_index().iloc[:, 2:]


def save_df(df, save_name):
    
    print("Saved.")
    

def compute_sampling_rates(df, aggre_columns = ['state_fips', 'county_fips', 'tract_fips', 'cbg_fips']):
    df_list = []
    for c in aggre_columns:
        sampling_rate_df = get_sampling_rate(df, aggre_columns=[c])
        df_list.append(sampling_rate_df)
        
    df_all = pd.concat(df_list)
    
    return df_all

df_all = compute_sampling_rates(residing_merged_df, aggre_columns = ['state_fips', 'county_fips', 'tract_fips', 'cbg_fips'])
# df_all = compute_sampling_rates(df,                        aggre_columns = ['state_fips', 'county_fips', 'tract_fips', 'cbg_fips'])

df_all['fips_len'] = df_all['fips'].astype(str).str.len()
df_all['fips_level'] = df_all['fips_len'].astype(str)
df_all['fips_level'] = df_all['fips_level'].replace({'2':"state", '5':"county", '11': 'tract', '12':'cbg'})

df_all.to_csv(fr'P:\Shared drives\NJIT_T5\safegraph_bias\sampling_rates_{YEAR}_monthly.csv', index=False)
df_all

,start_date,end_date,CBG_count,fips,device_count,population,year,aggre_column,sampling_rate,fips_len,fips_level
0,202101,202101,3438,01,475154,4876250,2021,01,0.097443,2,state
1,202101,202101,533,02,31213,737054,2021,02,0.042348,2,state
2,202101,202101,4177,04,427128,7050299,2021,04,0.060583,2,state
3,202101,202101,2147,05,266447,2999370,2021,05,0.088834,2,state
4,202101,202101,23199,06,1821738,39277401,2021,06,0.046381,2,state
...,...,...,...,...,...,...,...,...,...,...,...
2637927,202112,202112,1,721537505032,1,981,2021,721537505032,0.001019,12,cbg
2637928,202112,202112,1,721537506011,1,883,2021,721537506011,0.001133,12,cbg
2637929,202112,202112,1,721537506012,1,2523,2021,721537506012,0.000396,12,cbg
2637930,202112,202112,1,721537506013,2,991,2021,721537506013,0.002018,12,cbg
2637931,202112,202112,1,721537506021,0,1577,2021,721537506021,0.000000,12,cbg

In [534]:
df_all['sampling_rate'].mean(), df_all['sampling_rate'].max(), df_all['sampling_rate'].min()

(0.07502739634419049, 639.5, 0.0)

In [ ]:
def weighted_average(dataframe, value, weight):
    val = dataframe[value]
    wt = dataframe[weight]
    # print("wt.sum:", wt.sum())
    return (val * wt).sum() / wt.sum()

In [535]:
def time_aggregate(sampling_rate_df):
    
    rate_gb_df = sampling_rate_df.groupby(['year', 'fips']).agg(
                                      start_date=('start_date', 'first'), 
                                      end_date=('end_date', 'last'), 
                                      period_count=('start_date', 'count'), 
                                      CBG_count=('CBG_count', 'mean'), 
                                      device_count_mean=('device_count', 'mean'), 
                                      population=('population', 'mean'), 
                                      sampling_rate_mean=('sampling_rate', 'mean'),
                                      sampling_rate_max=('sampling_rate', max),
                                      sampling_rate_min=('sampling_rate', min),        
                                     )
    
    return rate_gb_df
    
rate_gb_df = time_aggregate(df_all.iloc[:]).reset_index()
# rate_gb_df.to_csv(r'P:\Shared drives\NJIT_T5\safegraph_bias\sampling_rates_yearly.csv', index=False)
rate_gb_df['fips_len'] = rate_gb_df['fips'].astype(str).str.len()
rate_gb_df['fips_level'] = rate_gb_df['fips_len'].astype(str)
rate_gb_df['fips_level'] = rate_gb_df['fips_level'].replace({'2':"state", '5':"county", '11': 'tract', '12':'cbg'})

rate_gb_df.to_csv(fr'P:\Shared drives\NJIT_T5\safegraph_bias\sampling_rates_{YEAR}_monthly_yearly.csv', index=False)

rate_gb_df

,year,fips,start_date,end_date,period_count,CBG_count,device_count_mean,population,sampling_rate_mean,sampling_rate_max,sampling_rate_min,fips_len,fips_level
0,2021,01,202101,202112,12,3437.750000,485747.166667,4876250.0,0.099615,0.116666,0.093924,2,state
1,2021,01001,202101,202112,12,32.000000,6097.916667,55380.0,0.110110,0.126761,0.104153,5,county
2,2021,01001020100,202101,202112,12,2.000000,349.916667,1993.0,0.175573,0.214250,0.147015,11,tract
3,2021,010010201001,202101,202112,12,1.000000,199.083333,730.0,0.272717,0.345205,0.197260,12,cbg
4,2021,010010201002,202101,202112,12,1.000000,150.833333,1263.0,0.119425,0.138559,0.111639,12,cbg
...,...,...,...,...,...,...,...,...,...,...,...,...,...
297357,2021,721537506012,202101,202112,12,1.000000,8.916667,2523.0,0.003534,0.013872,0.000396,12,cbg
297358,2021,721537506013,202101,202112,12,1.000000,6.416667,991.0,0.006475,0.023209,0.001009,12,cbg
297359,2021,72153750602,202101,202112,12,1.833333,4.583333,2117.0,0.002091,0.006292,0.000000,11,tract
297360,2021,721537506021,202101,202112,12,1.000000,2.666667,1577.0,0.001691,0.005073,0.000000,12,cbg
297361,2021,721537506022,202101,202111,10,1.000000,2.300000,648.0,0.003549,0.009259,0.001543,12,cbg

In [536]:
rate_gb_df['sampling_rate_mean'].mean(), rate_gb_df['sampling_rate_mean'].max(), rate_gb_df['sampling_rate_mean'].min()

(0.07498375601505249, 270.125, 0.0)

In [537]:
stop

NameError: name 'stop' is not defined

In [ ]:
df = pd.DataFrame(columns=['C1', 'C2', "C3"])
df["C1"] = [2, 2, 2, 1, 1, 1]
df["C2"] = ["a"] * 2 + ["b"] * 2 + ["c"] * 2
df["C3"] = range(6)

df = df.groupby(['C1', 'C2']).agg(C4=('C3', 'mean'),)

df.loc[:, :]

In [ ]:
df.loc[:, ['a', 'c'], :]

In [ ]:
bias_gb_df.index.get_level_values(1)
bias_gb_df.loc[:, ['male', 'female'], :]

In [ ]:
# SC_residing_df.sort_values('date_range_start')

In [ ]:
# weekly residing files
weekly_residing_df = pd.read_csv(r'J:\weekly_patterns_20211211\Panel_overview_data\WeeklyPattern\weekly_home_panel_summary.csv')
weekly_residing_df

In [ ]:
ACS_csv = r'H:\covid_mobility_results\new_census_data\ACS_2019_5YR_BG\ACS_race_cbsa_income_2019_county_decile.csv'

ACS_df = pd.read_csv(ACS_csv)


sociala_variable_df = pd.read_csv(r'F:\USC_OneDrive\OneDrive - University of South Carolina\Research\Mobility_covid\social_variables.csv')


sociala_variable_df
sociala_variable_df['GEOID'] = sociala_variable_df['GEOID'].str[-12:]

In [ ]:
# sociala_variable_df

In [ ]:
def text2GEOID(text):
    # for state, county, tract, blockgroup level only
    county_fips = ''
    tract_fips = ''
    blockgroup_fips = ''    
    state_fips = ''
    try:
        state_fips = text.split('state:')[1][:2]
        county_fips = text.split('county:')[1][:3]
        tract_fips = text.split('tract:')[1][:6]
        blockgroup_fips = text.split('block group:')[1][:1]
        
    except Exception as e:
        print("Error in text2GEOID()", e)
        pass
    
    return state_fips + county_fips + tract_fips + blockgroup_fips
                            
# make a test
text = r'Block Group 1, Census Tract 113, Coffee County, Alabama: Summary level: 150, state:01> county:031> tract:011300> block group:1'

len(text2GEOID(text))

In [ ]:
# B01001_026E: SEX BY AGE: Female: Total population -- (Estimate)

# B01001_001E: SEX BY AGE: Total: Total population -- (Estimate)

def get_census(state_fips=['45'], county_fips=[], blockgroup_fips=[], fields=['B01001_001E', 'B01001_026E']):  
    # unfinished
    
    df_list = []
    
    for state in state_fips:
        try:
            cookbg = censusdata.download('acs5', 2019,
                                         censusdata.censusgeo([('state', state), ('county', '*'), ('block group', '*')]),
                                         ['B01001_001E', 'B01001_026E'])

            index = [text2GEOID(str(t)) for t in cookbg.index]
            cookbg.index = index
            cookbg.index = cookbg.index.set_names(['FIPS'])
            cookbg = cookbg.reset_index()
            df_list.append(cookbg)
        except Exception as e:
            print("Error in get Census data in :", state, e)
            continue
        
    return pd.concat(df_list)

# make a test

cookbg = get_census(state_fips=['45'], county_fips=[], blockgroup_fips=[])
len(cookbg)

In [ ]:
cookbg['Female_ratio']#mean()

In [ ]:
# state_fips = list(states.mapping('fips', 'abbr').keys())[:-1] # the last one is none, drop it using [:-1].

# get data of SC
state_fips = ['45'] # the last one is none, drop it using [:-1]
cookbg = get_census(state_fips=state_fips, county_fips=[], blockgroup_fips=[])

cookbg['ratio_female'] = cookbg['B01001_026E'] / cookbg['B01001_001E']


len(cookbg), cookbg['ratio_female'].mean()

cookbg['ratio_female']

In [ ]:
cookbg = cookbg.merge(sociala_variable_df, left_on=['FIPS'], right_on=['GEOID'])

In [ ]:
SC_residing_df = weekly_residing_df[weekly_residing_df["date_range_start"].str.startswith('2019')].query("region == 'sc'")
SC_residing_df

In [ ]:
SC_residing_df = SC_residing_df.merge(cookbg, left_on='census_block_group', right_on='FIPS')
SC_residing_df = SC_residing_df.query('B01001_001E > 1').dropna()
SC_residing_df

In [ ]:
columns = [ 'ratio_white', 'ratio_black', 'ratio_hispanic', 'ratio_high_school', 'ratio_senior']
columns = ['ratio_female', 'ratio_white', 'ratio_black', 'ratio_hispanic', 'ratio_high_school', 'ratio_senior']


def get_bias(df):
    
    # columns = ['ratio_female', 'ratio_white', 'ratio_black', 'ratio_hispanic', 'ratio_high_school', 'ratio_senior']
    state_total_device = df['number_devices_residing'].sum()
    state_total_pop = df['popu_cbg'].sum()
    
    result_df = pd.DataFrame(columns = [ 'variable', 'start_date', 'census_ratio', 'safegraph_ratio'],
                   index = columns)
    
    for column in columns:
        start_date = df.iloc[0]['date_range_start'][:10] 
        cbg_column_devices = df['number_devices_residing'] * df[column]
        cbg_device_ratio = cbg_column_devices.sum() / state_total_device 

        cbg_column_pop = df[column] * df['popu_cbg']
        
        census_ratio = cbg_column_pop.sum() / state_total_pop
        safegraph_ratio = cbg_column_devices.sum() / state_total_device
        
        result_df.loc[column]['variable'] = column
        result_df.loc[column]['start_date'] = start_date
        result_df.loc[column]['census_ratio'] = census_ratio
        result_df.loc[column]['safegraph_ratio'] = safegraph_ratio
        
        
        # print(f"{safegraph_ratio:0.3f}, {census_ratio:.3f}")
    # print(result_df)
    return result_df
bias_df = SC_residing_df.groupby('date_range_start').apply(get_bias)
bias_df.reset_index(drop=True, inplace=True)

# bias_df = bias_df[columns]


bias_gb_df = bias_df.groupby(['variable']).agg(census_ratio_mean=('safegraph_ratio', 'mean'), 
                                  census_ratio_min=('safegraph_ratio', min), 
                                  census_ratio_max=('safegraph_ratio', max),
                                  census_ratio=('census_ratio', max),
                                 )

bias_gb_df = bias_gb_df.loc[columns]

bias_gb_df['census_ratio_mean_to_census'] = bias_gb_df['census_ratio_mean'] / bias_gb_df['census_ratio']
bias_gb_df['census_ratio_min_to_census'] = bias_gb_df['census_ratio_min'] / bias_gb_df['census_ratio']
bias_gb_df['census_ratio_max_to_census'] = bias_gb_df['census_ratio_max'] / bias_gb_df['census_ratio']

bias_gb_df.round(2)

In [ ]:
#

In [ ]:
bias_df.reset_index(drop=True, inplace=True)

In [ ]:
SC_residing_df.columns

In [ ]:
cookbg

In [ ]:


# cookbg

In [ ]:
CENSUS_KEY = 'b12026d61228a4b0d441ae7aa93f1ea222877503'

# two packages can be use: Census (need a Census key), Censusdata (no key needed)


from census import Census
from us import states

c = Census(CENSUS_KEY)
c.acs5.get(('NAME', 'B25034_010E'),
          {'for': 'state:{}'.format(states.MD.fips)})

In [ ]:
Census.ALL

In [ ]:
# c.sf1.state_county_blockgroup('NAME', states.AK.fips, '170', Census.ALL)